### ISSUE TITLE
[BUG] Invasion does not end at morning, causing hidden invasion mobs to prevent sleeping, further invasions

### ISSUE THREAD

**Issue by barnabywalters** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1001]
### Describe the bug

If all invasion mobs are not killed by morning, the invasion does not end, preventing sleeping and further invasions from occurring. Due to invasion mobs being able to spawn in tiny pockets and not always being able to dig their way out, this can lead to stale invasions persisting for weeks if the player doesn’t tear the landscape apart trying to find the last remaining invasion mob.

### To Reproduce

1. Start a new world
2. Wait for the first invasion
3. Don’t kill all the mobs

### Expected behavior

At the end of an invasion night:
* the remaining invasion mobs should despawn
* the invasion bar should disappear
* sleeping should become possible
* further invasions should become possible

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

### Additional context

On day 12 of a new 3.1.1 world, I got the first invasion, the one with poisonous beasts. I killed most of them, but by morning I had not found all of them. Rather than the remaining invasion mobs despawning, the invasion bar remained, and I was unable to sleep or reset my spawn point. The remaining mobs also prevented further invasions from occurring, and by day 43 I had to use commands to apply the glowing effect to find one of the remaining mobs, and finally the killall mobs command to deal with the last one which I couldn’t find.

Weirdly, the killall command didn’t end the invasion (instead killing all passive and hostile mobs around me), but directly after executing it, a final invasion zombie spawned right beside me. Killing that zombie ended the invasion.

Possibly related to #846

**Comment by EliteMeats** [comment]
This issue will be "fixed" in 3.2.0 (or whatever we end up calling it), due to the removal of the Onslaught mod. If we ever use the mod again this might be worth relooking at.
