### ISSUE TITLE
[BUG] “Soulfire Chassis” link broken on The Harvester guide page

### ISSUE THREAD

**Issue by barnabywalters** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1004]
### Describe the bug

The link to the “Soulfire Chassis” page on The Harvester guide page is broken. Hovering over it displays the text “BAD LINK: slayers_journal/soulfire_core”. Additionally, the actual item being referred to is named “Spiritfire Chassis”.

### To Reproduce

1. Acquire the slayers journal
2. Open the guide
3. Open the slayers journal
4. Open the Harvester page
5. Attempt to click on the “Soulfire Chassis” link

### Expected behavior

The link should work, and correctly reflect the actual item name.

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

**Comment by barnabywalters** [comment]
Additionally, the Harvester page should probably mention that the harvester can only be fought during the night. This is currently not obvious unless you’ve watched some random youtube video (#644) which is a pity when the in-game guide does an excellent job of providing all necessary information about the boss already. Preventing summoning during the day with a message saying “The Harvester can only be summoned at night” or similar would prevent resource loss.

**Comment by Foreck1** [comment]
![image](https://user-images.githubusercontent.com/47757429/198754787-c9b60dcc-1956-4723-9ce8-27a26c24a66c.png)
