### ISSUE TITLE
[BUG] Active BWM Saw doesn’t cut logs

### ISSUE THREAD

**Issue by barnabywalters** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1005]
### Describe the bug

When a log blog is placed against the blade of a powered better with mods saw block, rather than being cut into 5 planks, bar and sawdust as stated in the recipe, nothing happens. Tested with both redwood and oak logs. The saw blade was powered and cuts planks into siding, molding as expected.

### To Reproduce

1. Set up a working better with mods saw
2. Place a log block against the blade
3. observe that nothing happens

### Expected behavior

Per the recipe, the saw block should cut a log block into five planks, some bark and some sawdust.

### Screenshots

![2022-10-29_17 21 22](https://user-images.githubusercontent.com/968350/198884361-d7c7aa03-2d6a-43a8-a1d6-dc6cace26a3e.png)
![2022-10-29_17 23 08](https://user-images.githubusercontent.com/968350/198884371-4eadca7b-b9d1-4700-a946-832e645ab2ea.png)

Note the black particles present around the axle in both screenshots indicating that the saw is powered.

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

**Comment by iEatShadows** [comment]
This is more of position issue. To cut logs, you don't place em directly at the saw but infront of the saw. I'm at work rn I will provide a pic once I get home to clarify what I'm saying.

**Comment by democat3457** [comment]
@barnabywalters you must place the log such that the end of the log is not facing the saw. it has to be one of the bark sides that is touching the saw

**Comment by barnabywalters** [comment]
Well that’s a bizarre inconsistency, but I suppose if that’s how BWM works then there’s probably nothing RotN could do to improve it anyway.

**Comment by democat3457** [comment]
yup its quite a strange requirement, we're seeing if we can get it removed in an eventual bwm fork
