### ISSUE TITLE
[BUG] game is kinda speeds up?

### ISSUE THREAD

**Issue by Baschkirium** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1011]
### Describe the bug

Whenever i move my character world disappears and after few seconds world loads again with my character moved to inverted direction (w - back, s - forward). After restarting the game, nothing changes. New world - same. Take a look at the video and it'll become more clear

https://user-images.githubusercontent.com/122177255/211168373-7185a252-32bf-40a5-9d3e-24a28c076efd.mp4

### To Reproduce

Idk, it just appeared when i loaded into world.

### Expected behavior

Playable game

### Screenshots

![изображение](https://user-images.githubusercontent.com/122177255/211168091-96e26e54-2c4b-45b2-ac8f-d417dae05418.png)
![изображение](https://user-images.githubusercontent.com/122177255/211168637-1c0a44e3-140f-4e71-bd65-0dd9cf9c6853.png)

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

**Comment by KaleThyself** [comment]
Did you alter the pack in any way?

**Comment by democat3457** [comment]
Do you have Taylor's algorithm for BetterFPS? If so, change it to anything else, Taylor's is known to be buggy.

**Comment by Baschkirium** [comment]
Yeah, it was, thx
