### ISSUE TITLE
[BUG] Coade StoneBrick Walls weak, like really weak.

### ISSUE THREAD

**Issue by TheLoneGoat** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1012]
### Describe the bug

Need I say more? Very weak compared to the whole block.

### To Reproduce

Just make it.

### Expected behavior

Expected to be very strong.

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

**Comment by KaleThyself** [comment]
I recommend moving this issue to #546.

**Comment by democat3457** [comment]
Moved to https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/546#issuecomment-1384589018
