### ISSUE TITLE
[BUG] Plenty o' Biomes Peaches not in creative menu

### ISSUE THREAD

**Issue by CatTheKitten** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1036]
### Describe the bug

Plenty o Biomes Peaches are not accessible by JEI or the creative menu. PoB Peaches are different than the ones that do appear in the menus.

### To Reproduce

Search for Peach in JEI or Creative Menu

### Expected behavior

To access the peach :(

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

### Additional context

Accidentally erased the peaches switching between gamemodes, couldn't get them back :(

**Comment by EliteMeats** [comment]
Fixed in the upcoming patch
