### ISSUE TITLE
[BUG] CAN'T ACESSS NETHER in multiplayer server

### ISSUE THREAD

**Issue by HOLYBANANAS** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1039]
### Describe the bug

Me and my buddies killed the harvester and one of us got the achievement for getting the last kill. As expected, all of the players online atm got their gamestage changed and we could acess the nether (but we chicken out after some minutes). But the next day it wasn't the same. We tried going into the nether (people that have killed the harvester and people who haven't) but it no longer lets us get into the dimension. I have tried killing the Harvester various times and removed the gamestage and adding it back. I have also tried removing the gamestage again and then killing the harvester but nothing changes.

### To Reproduce

Going to the nether portal to try and tp to the nether

### Expected behavior

Stuck on the particle effect that reproduces when you stand on the nether portal thingy until you walk away of the portal.

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

### Additional context

I think what have caused the problem is creating the nether. Acessing it with players who haven't killed the harvester maybe broke the portal permissions.

**Comment by Ar1ston909** [comment]
I had the same problem, we solved it this way. In the folder of the world you need to find the folder "playerdata", and in it "gamestages". There will be several files responsible for the progress of different players. In one of them there will be a line about killing Harvester, and in the others - not.  You just need to copy the file of the player who killed the Harvester and rename it as the file with your progress was named. Do this with each player’s file. This should help. Just in case, make a copy of the world file if something goes wrong, and good luck ;)
