### ISSUE TITLE
[BUG] Immersive Combat Issues

### ISSUE THREAD

**Issue by evilchin** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1040]
### Describe the bug

I understand that you guys can't really solve this most likely. I haven't seen much discussion about the issues with the immersive combat mod so I felt I would share my findings and provide useful information.

1. The config option S:"Reduce Fist & Non-Weapon Damage" is currently not working if set at 0.0 since the 5-30-22 version. This means that anything that isn't considered a weapon is always doing 0.5 less damage which is contrary to the config's listed usage. Significance: Minor

2. Anything considered a weapon is causing ghost blocks and de-sync when left clicking or trying to mine. This means axes can't mine leaves (Quark), sickles can't destroy foliage (Thermal Foundation), and swords can't destroy cobwebs (Vanilla). You can also break blocks with swords in creative and cause de-sync, but that isn't as significant as what was stated earlier. This issue seems to have popped up in the 5-30-22 version. Significance: Major

3. Anything that relies on left click or attack events AND is considered a weapon to the mod is not functioning. It seems immersive combat is aggressively handling anything related left clicking items it deems as weapons. Example of this being Botania's swords not having their special functions (mana blasts, falling stars, etc.). There is more than just this as the previous bullet point is realistically stemming from the same cause as this one. This issue seems to have popped up in the 5-30-2022 version. Significance: Major

4.  Attack indicator when wielding a single weapon in the dominant hand is offset since the 5-30-22 version. Could possibly be intended to work this way. Significance: Minor

5. Changes to strength and weakness potion effects are not functioning (at least on my end). Even on a fresh instance with just this mod and forge. It seems at least that the tooltips for the potion aren't reflecting the changes that immersive combat is trying to do in the background. Significance: Minor

### To Reproduce

1. Punching should do 1 damage (half a heart). Yet it doesn't.

2. Swing a diamond arming sword at vanilla foliage in creative for instance. It will create ghost blocks instantly. In RoTN 3.1.1 it seems like it wont work against cobwebs and other foliage, but this is reproducible on other packs. You also can't do stuff like mine statues with pickaxe for instance (according to the RoTN discord)

3. This is more of an issue for other packs as far as I'm aware as RoTN doesn't have anything like this. To easily reproduce you can install botania in RoTN to see the results. I figured I would add this info in case it help shine light on a unresolved issue for you guys.

4. Equip just a sword and you will see how the attack indicator (crosshair option) is offset. 

5. Look at the tooltips for strength and weakness potions. According to how the mod is configured in RoTN strength should be +10% damage and weakness should be -20%.

### Expected behavior

1. Non-weapons shouldn't be penalized.

2. Tools, and weapons especially, shouldn't create ghost blocks just from swinging at vanilla tall grass for instance.

3. Left clicks with weapons shouldn't cancel other mods effects and events.

4. Centered attack indicator if using just one weapon in dominant hand. Although this could be intended to work how it does now, I just haven't seen any documentation on it being changed.

5. Potions of strength and weakness should work correctly and their tooltips should reflect it. They at least seem to work correctly in RoTN 3.1.1, although the stats aren't reflected.

### Screenshots

Here is some proof for just bullet points 4 and 5. Sorry if the links aren't correct

4. https://media.discordapp.net/attachments/763312725971435550/1100662764965466112/image.png?width=248&height=116
5. https://media.discordapp.net/attachments/763312725971435550/1100663074316361768/image.png?width=294&height=147

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

### Additional context

I wrote most of this info already immersive combat's issue board. There is a small bit of more information there, but I felt it wasn't relevant to RoTN issue tracker.

**Comment by evilchin** [comment]
Ignore everything listed. New update fixed literally all of this. Haven't noticed  any bugs at all.

**Comment by KaleThyself** [comment]
> Ignore everything listed. New update fixed literally all of this. Haven't noticed any bugs at all.

Which new update are you referring to?

**Comment by evilchin** [comment]
So the immersive combat mod had issues like: the configs not doing what was listed, anything defined as a weapon would create ghost blocks for plants/leaves/cacti if swung at while not at a positive xz coordinate (and would insteaddelete them at postive coords, the attack indicator would offset even while you weren't dual wielding, certain left click event listeners would break (think terra sword from botania creating mana blasts as an example). 

Burgy updated it recently and you can finally download it on curseforge today and it seems to have fixed every issue with the old version. Really think you guys should devote some time to it as this new update is huge with adding stuff like attack animations (highly configurable), modifying attack speeds (which wasn't really possible for swords beforehand), and adding potion effects to any weapon. It seems to have revamped the attack indicator as well.

**Comment by Foreck1** [comment]
We know, we've been in talks with Burgy constantly over the past year for this update. These are all things we wanted and are aware of. It's not likely that they will make it into the next patch though.

**Comment by KaleThyself** [comment]
> Edit: It seems like I put the quintessence in the incorrect thing (right clicked the wrong item). Though this other weird thing with the boots still keeps occurring: opening the quintessence pouch will display a copy of the boots I'm currently wearing in my inventory even though I have it equipped. Moving the boots from the inventory to my hotbar/holding items will result in me unequipping it. Not sure if there are other issues when using the pouch atm.

Please refrain from commenting unrelated issues in unrelated bug threads. Additionally, this has already been reported in #938.
