### ISSUE TITLE
[BUG] Installation guide not working

### ISSUE THREAD

**Issue by Brensom** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1045]
### Describe the bug

https://wiki.rebirthofthenight.com/wiki/Installation not working:

> ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### Modpack Version

Other

### Server or singleplayer

Singleplayer

### Version the world was created on:

Other

**Comment by KaleThyself** [comment]
https://rotn.wiki.gg/wiki/Installation
