### ISSUE TITLE
[BUG] Chime Recipes are entirely incorrect

### ISSUE THREAD

**Issue by Unishine** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1052]
### Describe the bug

Dark Oak chimes want Acacia, Jungle chimes want Birch, Birch wants Spruce, Spruce wants Oak, Oak wants everything but the other names of chimes and there is no such thing as a chime made of Dark Oak.

### To Reproduce

Go to the JEI and look at the recipe for chimes.

### Expected behavior

A dark oak chime should use dark oak in its recipe, and vise versa for everything else. Oak actually makes sense though, it being the "default" wood.

### Screenshots

![2023-08-24_19 42 02](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/assets/101996181/07faf121-1945-4b69-8424-b7fd201dc971)

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

### Additional context

Only guess I have is that there are values that determine what wood goes where and it got misaligned for chime recipes.

**Comment by Foreck1** [comment]
Chimes got reworked for the upcoming 3.2 version, so it won't be a problem.

**Comment by Unishine** [comment]
oh nice. yipee!
