### ISSUE TITLE
[BUG] Invasions doesn't give rewards

### ISSUE THREAD

**Issue by SussyMan111** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1062]
### Describe the bug

After end of invasions theres no reward even if with free slots in inventory (long time had no rewards). Works normally if end it with command.

### To Reproduce

Create new world > wait for any invasion > end it by killing all

### Expected behavior

Receiving a reward for comlpeting invasion.

### Modpack Version

3.1.1a

### Server or singleplayer

Server, Singleplayer

### Version the world was created on:

3.1.1a

**Comment by Foreck1** [comment]
Irrelevant with the removal and discontinuation of Onslaught
