### ISSUE TITLE
[BUG] Nether invasion can't end

### ISSUE THREAD

**Issue by SussyMan111** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1063]
### Describe the bug

Nether invasion can't be completed, gets stuck at like 85% of bar.

### To Reproduce

Create new world > reach nether > wait for nether invasion > kill all mobs > no more mobs and it stuck

### Expected behavior

Nether invasion can be ended naturally (without command).

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

**Comment by Foreck1** [comment]
Irrelevant with the removal and discontinuation of Onslaught
