### ISSUE TITLE
[BUG] well water bug

### ISSUE THREAD

**Issue by SussyMan111** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1064]
### Describe the bug

By clicking on well with "iron bucket" it grabs water and also making a water source where you grabbed it.

### To Reproduce

Create new world > reach and place well > get iron bucket(one with 3 irons) > right click on well by it (must be empty)

### Expected behavior

Well will only fill a bucket

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

**Comment by democat3457** [comment]
duplicate of #591
