### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by idk3250** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1067]
### Describe the crash

Whenever I try to launch Minecraft, it keeps getting stuck on Earthworks-Constructing and then just crashes.

### To Reproduce

Launch Minecraft.

### Crash Logs

[crash-2024-03-19_05.49.06-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/14645997/crash-2024-03-19_05.49.06-client.txt)

### Modpack Version

3.1.1a

### Server or singleplayer

Server, Singleplayer

### Version the world was created on:

3.1.1a

**Comment by democat3457** [comment]
This is strange, try reinstalling?

**Comment by idk3250** [comment]
> This is strange, try reinstalling?

It had something to do with the mods, I did some troubleshooting and it's fixed now
