### ISSUE TITLE
[BUG] Unable to Convert Zombie Villagers

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1069]
### Describe the bug

When attempting to convert zombie villagers into normal villagers with the weakness + golden apple method, right clicking with a golden apple only makes the player proceed to eat the apple. 

### To Reproduce

1. Summon or find a zombie villager. 
2. Use a weakness potion source onto it.
3. Right click it with a golden apple. 

### Expected behavior

I expect zombie villagers to be able to be converted normally without IC right click conflicts. 

### Screenshots

N/A

### Modpack Version

Other

### Server or singleplayer

Singleplayer

### Version the world was created on:

Other

### Other...

v.3.2

### Additional context

This is due to IC most likely.

**Comment by Foreck1** [comment]
We hadn't planned for this, but vanilla villagers should not exist anymore, so this will not be fixed. If IC fixes this, then we'll proceed to disable it again somehow.
