### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sagecube1** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1102]
### Describe the bug

In the too many items pages, when you click on cloud in a bottle, it opens the recipe for fart in a bottle. Even when reclickng on cloud in a bottle or the bottle in the recipe itself, the recipe does not appear.

### To Reproduce

Open the recipe for cloud in a bottle in the too many items menu.

### Expected behavior

I expected the recipe for cloud in a jar to appear like the recipe for another item would. Or maybe the explanation of the item like some items have in the modpack,

### Screenshots

![Screenshot 2024-05-21 125103](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/assets/54958118/364fc44c-bc1f-4fbd-9008-07dce5bfbb85)

### Modpack Version

3.2

### Server or singleplayer

Server

### Version the world was created on:

3.2

**Comment by ProvidenceDaemon** [comment]
the cloud in a bottle is not a craftable item.
