### ISSUE TITLE
[CRASH] quest complete page

### ISSUE THREAD

**Issue by SussyMan111** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1113]
### Describe the crash

clicking quest complete page in advancements crashes world

### To Reproduce

create world > click quest complete (im at day 200+ so maybe something required) > disconnect

### Crash Logs

[crash-2024-06-21_21.18.04-client.txt](https://github.com/user-attachments/files/15931677/crash-2024-06-21_21.18.04-client.txt)

### Modpack Version

3.2

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

**Comment by Foreck1** [comment]
What quest do you mean? Village quest?

**Comment by SussyMan111** [comment]
"quest complete" page in advancements

**Comment by KaleThyself** [comment]
Can you take a screenshot of the GUI?

**Comment by SussyMan111** [comment]
![bandicam 2024-06-21 22-40-53-735](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/assets/151395170/ccfae9c3-23ed-4218-8d2e-9116e7986056)
trophy one

**Comment by KaleThyself** [comment]
I'm not seeing any quest complete tab. Did you modify the modpack in any way? What launcher are you using as well?
![image](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/assets/50285548/7825bdb9-82cc-417b-941e-2bdd792d0bf2)

**Comment by SussyMan111** [comment]
no modifiers. Tlauncher. copied save folder only

**Comment by KaleThyself** [comment]
TLauncher is unsupported by RotN. Mod support for pirated launchers is also not available, so we can't really help you here.
