### ISSUE TITLE
[BUG] Bauble bonuses not stacking/canceling out

### ISSUE THREAD

**Issue by fifciox** [Rebirth-of-the-Night/Rebirth-Of-The-Night#112]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
While having Balloon bauble without any bonuses and Forbidden Fruit bauble with jump height bonus the height of the jump is only boosted by the balloon itself meaning that the bonus of the Forbidden Fruit is ignored - character jumps up 3 blocks high. Additionally if the player is to equip Bezoar with jump height bonus the effects of the Balloon bauble is canceled and the player is able to jump up 2 blocks high.

**To Reproduce**
1. Equip Balloon bauble and test the jump height
2. Equip Forbidden Fruit bauble with jump height bonus and test the jump height
3. Equip Bezoar bauble with jump height bonus and test the jump height
4. Compare the results of each combination

**Expected behavior**
Bonuses and effects themselves of baubles are to stack logically.

**Screenshots**
Screenshots of used items:
![gtbgt](https://user-images.githubusercontent.com/61943430/76166903-8ee0ae00-6162-11ea-83d3-f5309c782994.png)
![srjt](https://user-images.githubusercontent.com/61943430/76166904-8f794480-6162-11ea-8d40-ea113ace8f60.png)
![srth](https://user-images.githubusercontent.com/61943430/76166905-9011db00-6162-11ea-9614-cc1e99e402fb.png)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
Please note that this most likely works with any bauble type. Additionally please test different configurations of bauble/bonus combinations as earlier the Balloon bonus was canceled just by wearing Bezoar with the jump height bonus but I was not able to reproduce it later on.

**Comment by CalaMariGold** [comment]
Sounds like an issue for the Bountiful Baubles or Quality Tools github. Not much we can do about this

**Comment by kil0byt3** [comment]
Issue opened with BB, waiting

**Comment by DarkEnchanter1** [comment]
Issue doesn't seem to be on our side. I believe the issue lies in how QualityTools adds to the jump height (instead of simply adding to it in the jump event it overwrites the jump height directly).

**Comment by kil0byt3** [comment]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2811433-quality-tools-randomized-qualities-for-your-tools?page=3#c57

**Comment by KaleThyself** [comment]
Issue can be closed since QualityTools qualities are no longer relevant in 3.0+.

**Comment by democat3457** [comment]
Baubles still have qualities

**Comment by KaleThyself** [comment]
> 
> 
> Baubles still have qualities

Are baubles with conflicting qualities such as the balloon and jump height still an issue then?

**Comment by democat3457** [comment]
Yes, baubles can have jump height qualities that conflict with the BB balloon (which I'm fairly certain can still be crafted)

**Comment by KaleThyself** [comment]
> 
> 
> Yes, baubles can have jump height qualities that conflict with the BB balloon (which I'm fairly certain can still be crafted)

Actually, the BB balloon isn't used anymore. It was replaced by the Artifacts Shiny Red Balloon which gives permanent jump boost 2 instead of modifying jump height directly. Thus, the conflicting interaction in the original bug report is no longer relevant. 
![image](https://user-images.githubusercontent.com/50285548/124674286-437e0300-de6f-11eb-9f08-468a98366b39.png)

**Comment by democat3457** [comment]
Ah. Also, nice setup you have there - a suggestion would be to add trapdoors as well to indicate approx. 1/4th of a block for more accuracy
