### ISSUE TITLE
[BUG] Can't apply Mending with True Enchanting Table

### ISSUE THREAD

**Issue by ErikAnpin** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1137]
### Describe the bug

I can't seem to add mending via True Enchanting Table, **the option is there** but it fails to apply.

### To Reproduce

1. Make a 3x3 floor of Blocks of Gold or similar
2. Place a True Enchanting Table in the middle
3. Try to add Mending to a Mythril Sword or other weapon
4. XP goes away for a second and it looks like it worked
5. Take sword off table and find out it's not Enchanted

### Expected behavior

The enchantment should be applied and XP should be taken from the player.

### Modpack Version

3.2

### Server or singleplayer

Server, Singleplayer

### Version the world was created on:

3.2

### Other...

Tested in both server and single player with curseforge's latest version.

### Additional context

I can't add Mending to the pickaxe either unless I also apply Magnetic at the same time. Different bookcase/true enchanting book numbers were tested.

**Comment by ErikAnpin** [comment]
Restarting the client seems to "fix" it, but it happened with multiple people so I'll leave this here.

**Comment by KaleThyself** [comment]
Mending is only intended to be obtainable as a daytime enchantment. At night, it cannot be applied.
