### ISSUE TITLE
[BUG] Block of Copper is incorrectly named Waxed Block of Copper

### ISSUE THREAD

**Issue by RivaledRandom** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1139]
### Describe the bug

9 Copper ingots create Waxed Block of Copper when it should be called Block of Copper, especially since there's already an actual Waxed Block of Copper that is it's own item and has it's own recipe.

### Screenshots

![image](https://github.com/user-attachments/assets/b4d942e6-d5e4-4c05-9abf-7f396d1f6386)
![image](https://github.com/user-attachments/assets/1bddea3e-5978-4e93-aefd-c6a49594a7a2)
![image](https://github.com/user-attachments/assets/61baf39d-703b-464a-a52d-006ed60ab971)

### Modpack Version

3.2

### Server or singleplayer

Server, Singleplayer

### Version the world was created on:

3.1.1a

**Comment by democat3457** [comment]
Fixed in stable
