### ISSUE TITLE
[BUG] Troll freezes when hitting a tree branch

### ISSUE THREAD

**Issue by BbachB** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1143]
### Describe the bug

When you bring a troll to a tree and make it try to hit you while hiding behind a branch, it freezes in place, loses its weapon, and strikes a pose

### To Reproduce

1.) Bring a troll to a tree
2.) Make sure tree has a branch sticking out that's about head level of the troll
3.) Make troll try to swing at you
4.) troll freezes

### Expected behavior

The troll to not freeze

### Screenshots

![image_2024-11-03_011125944](https://github.com/user-attachments/assets/a8c94a55-6139-4d0a-bbbd-264e14cec778)

### Modpack Version

3.2

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.2

### Additional context

If you leave and rejoin, the troll briefly returns back to normal but then strikes the same pose

**Comment by Hlodr2** [comment]
he touched the sun and turned into stone
