### ISSUE TITLE
[CRASH] Chameleon/Camo Armor + Dog Bed Crash

### ISSUE THREAD

**Issue by Dog780** [Rebirth-of-the-Night/Rebirth-Of-The-Night#117]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
I was hosting a LAN server with one other person and we were walking out of our house to chop trees then we crashed so I tried to start it up again and it continues to crash when I try to load it up
**To Reproduce**
Steps to reproduce the behavior: Load up the same world.

**Crash Log**
https://paste.dimdev.org/ewecohezik.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer, but LAN
 - Version the world was created on: 2.76.2

**Additional context**
A few minutes before the crash I moved a bed from doggy talents, but other than that I did get an error message when I killed a squirrel, but I hadn't done that since the start of the game a long time ago.

**Comment by Dog780** [comment]
I was able to get in to the world, while it was loading I spammed my keyboard and kept clicking my mouse and it let me in?

**Comment by Dog780** [comment]
A little before the crash I used a splash potion of invisibility

**Comment by Dog780** [comment]
I put a spruce dog bed down and it crashed again

**Comment by CalaMariGold** [comment]
I think a chameleon tried to walk on a doggy talents bed and didn't know what color to change to.

**Comment by kil0byt3** [comment]
Opened Primitive Mobs git issue, waiting

**Comment by democat3457** [comment]
DoggyTalents PR created https://github.com/percivalalb/DoggyTalents/pull/244

**Comment by democat3457** [comment]
So it's not a Primitive Mobs issue, but Prim Mobs dev is looking for a workaround on his side to not run code if Doggy Talents is installed. Waiting for either Doggy Talents dev to release a version with the null saveId workaround or for Prim Mobs to release their workaround.

**Comment by democat3457** [comment]
Need mod update.
