### ISSUE TITLE
[BUG] Milk gotten from Cows disappears upon picking it up in inventory

### ISSUE THREAD

**Issue by lizardolphin** [Rebirth-of-the-Night/Rebirth-Of-The-Night#139]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Upon milking a cow, the milk item appears in the inventory, but when it is left clicked in the inventory GUI, it reverts to an empty milk bucket. This happened with both a Jersey cow and a Fresian cow

**To Reproduce**
1) Feed and water the cow (Who has recently given birth)
2) Bucket in inventory turns into {Cow Breed} milk
3) Pick up bucket in inventory
4) Reverts to Bucket

**Expected behavior**
Expected the milk to be useable and craftable

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Both singleplayer and LAN
 - Version the world was created on: Modpack version 2.76.2

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Possibly a bug for the Animania github. I'll see if I can reproduce this.

**Comment by kil0byt3** [comment]
Existing issue in Animania Github, waiting for update

**Comment by SandwichHorror** [comment]
Mod author is aware and is "looking into it"

**Comment by democat3457** [comment]
should be fixed in next release, marked as "fixed in next release" four days ago
