### ISSUE TITLE
[BUG] Smelting Enchantment not giving EXP for certain ores

### ISSUE THREAD

**Issue by Eksekk** [Rebirth-of-the-Night/Rebirth-Of-The-Night#144]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Mining mythril ore with Smelting enchantment gives no EXP.

**To Reproduce**
Mine mythril ore using pickaxe with smelting enchantment.

**Expected behavior**
You get some experience, idk if that relates to experience gained by smelting.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
Viridium, silver, iron work fine. Others not tested.

**Comment by CalaMariGold** [comment]
Strange that viridium is working but not mythril. I don't know what could cause it in that case. Possibly a mod bug from simple ores or whatever mod smelting is from.

**Comment by democat3457** [comment]
smelting is from dungeontactics

**Comment by democat3457** [comment]
> idk if that relates to experience gained by smelting.

Pretty sure it does... not sure if this bug still exists on latest though.

**Comment by KaleThyself** [comment]
Currently in version 2.77.5 the Smelting enchantment does not give experience when you mine any ore that would normally drop itself such as iron, gold, tin, copper, etc. However, normal experience is given when mining gems and dust such as diamonds, coal, redstone, lapis, etc. 

Following those rules, Viridium ore does not give experience when mined with a pickaxe using the Smelting enchantment. The same can be said for Mythril ore as I just now tested.

**Comment by democat3457** [comment]
does this happen on 3.0 betas

**Comment by KaleThyself** [comment]
> 
> 
> does this happen on 3.0 betas

From the light testing I did in the 3.0 Betas, the Smelting enchantment is properly giving experience when mining normal ores including all of the above **except** for Mythril ore.

**Comment by democat3457** [comment]
:|

**Comment by KaleThyself** [comment]
Ah, I did not do enough testing and it turns out copper ore doesn't give exp either. I'll continue editing this comment if I find more.

**Comment by KaleThyself** [comment]
All ores seem to give exp base on rng now via the smelting enchantment. Issue can be closed now.

**Comment by EliteMeats** [comment]
smelting enchantment has been disabled so this is irrelevant now
