### ISSUE TITLE
[CRASH] Dungeon Tactics Harvesting Crash

### ISSUE THREAD

**Issue by RobertK1229** [Rebirth-of-the-Night/Rebirth-Of-The-Night#159]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Crash caused by failure to update while ticking player.

**To Reproduce**
Steps to reproduce the behavior: Unknown.

**Crash Log**
[crash-2020-03-23_22.03.36-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4372945/crash-2020-03-23_22.03.36-server.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: server
 - Version the world was created on: 2.74

**Additional context**
Initial crash stated error ticking entity: zombie pigman after exiting a nether portal.

**Comment by CalaMariGold** [comment]
Can you explain what you were doing when this crash happened?

**Comment by democat3457** [comment]
I suspect this may have something to do with the smelting enchantment bug... By any chance, @RobertK1229, did you use a tool with the smelting enchantment to harvest the crops? (Or is the title meaning that you used the harvesting enchant?)

**Comment by RobertK1229** [comment]
@democat3457 no. To my knowledge I was not using the harvesting or smelting enchantment. From what I remember all I was doing was exploring the nether and it crashed after a prolonged period of server stalling (mobs not moving, blocks I break not dropping).

**Comment by democat3457** [comment]
Hm. Can you open an issue on the Dungeon Tactics CurseForge?

**Comment by democat3457** [comment]
Actually, nevermind on that. Did you break any blocks before the crash, and what tool (with what enchants) did you break it with? @RobertK1229

**Comment by democat3457** [comment]
Closing because the `randomCount` issue has been solved to my knowledge.
