### ISSUE TITLE
[BUG] Plague sometimes reappears shortly after curing it with no mobs nearby

### ISSUE THREAD

**Issue by Eksekk** [Rebirth-of-the-Night/Rebirth-Of-The-Night#165]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
In title.

**To Reproduce**
1. Spawn any plague-inducing mob.
2. Cure it with any item, while avoiding mob attacks.
3. Wait a minute or so.
4. Do it repeatedly until plague reappears with no reason.

**Expected behavior**
Plague is reinflicted only on specific mob attacks.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.2

**Additional context**
N/A

**Comment by CalaMariGold** [comment]
@SandwichHorror

**Comment by SandwichHorror** [comment]
Plague also is passed to mobs when you interact with them (right click). If you've infected an animal and then right-click it again, you could acquire the plague.

**Comment by Eksekk** [comment]
Yes, but I didn't interact with any animals, was only opening chests.

**Comment by democat3457** [comment]
Wait, what are we waiting on? (send issue link)

**Comment by Eksekk** [comment]
https://github.com/Alex-the-666/Rats/issues/220

**Comment by democat3457** [comment]
Closing because age and plague rework. Reopen if issue persists on 3.0 beta 4 or higher.
