### ISSUE TITLE
[BUG] Cobalt shield/obsidian shield in bauble slot does not prevent knockback

### ISSUE THREAD

**Issue by Eksekk** [Rebirth-of-the-Night/Rebirth-Of-The-Night#167]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
In title. When holding them in offhand, they work correctly. Obsidian shield as bauble does prevent fire damage ticks, but not knockback.

**To Reproduce**
Equip them as bauble and get attacked.

**Expected behavior**
These shields equipped as bauble prevent knockback.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.2

**Additional context**
N/A

**Comment by CalaMariGold** [comment]
@Foreck1 🙃

**Comment by democat3457** [comment]
Does the cobalt shield's knockback resist work?

**Comment by democat3457** [comment]
oh wait didnt read title :/

**Comment by democat3457** [comment]
Opened https://github.com/CursedFlames/BountifulBaubles/issues/33

**Comment by democat3457** [comment]
apparently bountifulbaubles is no longer supporting 1.12

**Comment by CalaMariGold** [comment]
Closing because we'll be using Artifacts for the Cobalt Shield. Obsidian and Ankh shields are getting removed
