### ISSUE TITLE
[CRASH] with Enchanted Diamond Hoe, Quark.

### ISSUE THREAD

**Issue by CynicalButthole** [Rebirth-of-the-Night/Rebirth-Of-The-Night#170]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Right clicking crops (Hemp) with an enchanted Diamond Hoe (Fortune, Unbreaking) causes a reproducible crash

**Crash Log**
https://paste.dimdev.org/repiqibuku.mccrash

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76.2

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
Might be because we have the "right click to harvest" feature enabled from multiple mobs. We'll see what we can do.

**Comment by democat3457** [comment]
Can someone repost the crash log, the link is broken...

**Comment by democat3457** [comment]
Can someone test this on latest?

**Comment by KaleThyself** [comment]
> 
> 
> Can someone test this on latest?

I tested harvesting hemp by right clicking with an enchanted diamond hoe (same enchantments), but there was no crash in the latest version (2.77.5) on singleplayer. I'm confused about why "Quark" was added to the title.

**Comment by democat3457** [comment]
> I'm confused about why "Quark" was added to the title.

Probably because the crash screen mentioned the mod "Quark."
But since it doesn't happen anymore, it might've been a setting in Quark that got disabled. Do reopen if someone finds the same issue again.
