### ISSUE TITLE
[BUG] Enderman Able to Teleport Ender Dragon

### ISSUE THREAD

**Issue by Niner93R** [Rebirth-of-the-Night/Rebirth-Of-The-Night#175]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
When the dragon aggros endermen they attack it, if it's landed on the exit portal they can teleport him elsewhere which causes the dragon to get stuck, repeating the landed attack cycle.
**To Reproduce**
- Fight End Dragon
- Wait for an enderman to teleport it while landed

**Expected behavior**
Dragon will be teleport a number of blocks away and repeat the "landed" attack cycle for far longer than it should. Eventually it might resume flight.

**Screenshots**
[Landed dragon teleported](https://i.imgur.com/oNeC4hO.png)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76.2

**Additional context**
None at the time

**Comment by CalaMariGold** [comment]
So, this is an issue @SandwichHorror and I have been trying to fix. I believe it used to work, but I'm not sure what happened. Either way, we'll be doing what we can to fix this in 2.78.

**Comment by SandwichHorror** [comment]
Not really possible to do anything about it until Rough Mobs Revamped fixes the entity targeting blacklist.

**Comment by democat3457** [comment]
Has an issue been opened for this?

**Comment by SandwichHorror** [comment]
yeah mentioned it to Rough Mobs Revamped dev a while back, they haven't really updated the mod since then so I assume they're busy :cry:

**Comment by democat3457** [comment]
Did you open an issue for it?

**Comment by SandwichHorror** [comment]
not explicitly the same bug, but this bug being fixed ought to address it, I mentioned it in the comments at any rate 
https://github.com/p1ut0nium-git/Rough-Mobs-Revamped/issues/17

**Comment by democat3457** [comment]
Well, this was fixed in dev.
