### ISSUE TITLE
[BUG]Librarians selling disabled enchantment book.

### ISSUE THREAD

**Issue by ItzRaiderr** [Rebirth-of-the-Night/Rebirth-Of-The-Night#207]
**Describe the bug**
A librarian had a trade of selling a disabled book called "weapons" when I progressed in trading with him.

**To Reproduce**
Keep trading until there is a chance for disabled book to show up?

**Expected behavior**
No trade for disabled books

**Screenshots**
[http://prntscr.com/rv6byf](url)

**Info:**
 - Modpack Version: 2.77 pre-release
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 1.12.2 MC, v2.77 pre-release (modpack)

**Additional context**
**Why u sell me disabled enchantment book villager? >:(**

**Comment by CalaMariGold** [comment]
Not much we can do about this until 2.79.

**Comment by democat3457** [comment]
Was this fixed when we finally disabled the unused enchantments?

**Comment by CalaMariGold** [comment]
reopen if this is still an issue in 3.0
