### ISSUE TITLE
[BUG] Just a text bug

### ISSUE THREAD

**Issue by xennny** [Rebirth-of-the-Night/Rebirth-Of-The-Night#215]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
"ÂThe undead horde is approaching...

**To Reproduce**
During an Invasion

**Expected behavior**
no Â

**Screenshots**
https://cdn.discordapp.com/attachments/664351929505415168/697704349627056178/unknown.png

**Info (please complete the following information):**
 - Modpack Version: 2.77 Full Release
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77 Full Release

**Additional context**
Not a big deal, but hey, why not

**Comment by CalaMariGold** [comment]
@corosus pls muh immersion

**Comment by CalaMariGold** [comment]
oh fuck that actually pinged

**Comment by CalaMariGold** [comment]
thats not even the right corosus

**Comment by democat3457** [comment]
https://github.com/Corosauce/HostileWorlds_Invasions/issues/24 reference

**Comment by SandwichHorror** [comment]
Friendship ended with COROSUS
now CODETAYLOR is my best friend
