### ISSUE TITLE
[BUG] Mobs Spawning on top of Nether and no bedrock at bottom of nether

### ISSUE THREAD

**Issue by Niner93R** [Rebirth-of-the-Night/Rebirth-Of-The-Night#220]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
1. Mobs spawn on top of nether because all there is at the top is netherrack. This causes lots of lag, especially on server.
2. No bedrock at bottom of nether, so you can make void holes

**To Reproduce**
Enter nether. Mine up or down.

**Expected behavior**
Bedrock to be there, which isn't a spawnable block.
**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Both
 - Version the world was created on: 2.77

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
N/A

**Comment by CalaMariGold** [comment]
Nether bedrock is something for @Kompreya to fix.

I'll fix mobs spawning above

**Comment by kil0byt3** [comment]
@Kompreya are you still wanting to do this?

**Comment by SandwichHorror** [comment]
she's waiting for 2.8 where we'll have big vertical stacked dimension changes (nether under beneath etc)

**Comment by Kompreya** [comment]
Nether bedrock fixed in https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/f32600737e5fbec8742eb109d752a29a77432d8f
