### ISSUE TITLE
[BUG] Trash slot not visible when backpack is on.

### ISSUE THREAD

**Issue by mtressler** [Rebirth-of-the-Night/Rebirth-Of-The-Night#227]
![image](https://user-images.githubusercontent.com/59582863/78959446-f28b2d80-7ab8-11ea-851a-8756293c1cfc.jpg)
![image](https://user-images.githubusercontent.com/59582863/78959459-fdde5900-7ab8-11ea-92ba-54464c801a54.jpg)

**Comment by kil0byt3** [comment]
Got it. We'll look into this and get back to you. Issue with the mod, I'll open a github issue with them.

**Comment by democat3457** [comment]
I'd assume this is the issue? https://github.com/blay09/TrashSlot/issues/37

**Comment by CalaMariGold** [comment]
Fixed in 3.0 beta 3
