### ISSUE TITLE
[BUG] Quark Itemstack GUI Overrides all other GUI mods

### ISSUE THREAD

**Issue by Niner93R** [Rebirth-of-the-Night/Rebirth-Of-The-Night#255]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
What it says on the tin.
**To Reproduce**
Hold item with more in your inventory so itemstack pops up, GUI will dissapear for 3 seconds and re-appear, then itemstack dissapears itself

**Expected behavior**
All my GUIs playing nicely together like good boys and girls

**Screenshots**
![image](https://user-images.githubusercontent.com/49265152/79509484-d1669780-7ff8-11ea-87d9-ef5cd0c0aacd.png)
![image](https://user-images.githubusercontent.com/49265152/79509487-d3c8f180-7ff8-11ea-83c9-919499a6272d.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Both
 - Version the world was created on: N/A

**Additional context**
quark y u do dis

**Comment by kil0byt3** [comment]
Thanks. :D

**Comment by KaleThyself** [comment]
This issue may be closed as the item stack GUI for Quark no longer appears. 
![image](https://user-images.githubusercontent.com/50285548/180634047-39102b38-b2c8-464b-a601-d4545c691b6c.png)

**Comment by KaleThyself** [comment]
It appears that a player found another related GUI issue. 
![image](https://user-images.githubusercontent.com/50285548/194451211-c5bfcc0a-7f2d-4913-baa1-ff94c79960ab.png)
_"the quiver makes the armor, sat(uration), and thing behind the hunger bar disappear when in hotbar"_
