### ISSUE TITLE
[BUG] Ore randomly destroyed when mining

### ISSUE THREAD

**Issue by cheshyrp** [Rebirth-of-the-Night/Rebirth-Of-The-Night#262]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Some ores, most recently Icestone in the Aether, give a "DungeonTactics encountered a problem" error when mined with a smelting pickaxe. This destroys the ore and drops nothing. On my previous 2.76 world, this occured with Radiant Crystals.

**To Reproduce**
I occurs every time I mine said ore with a pick that has smelting on it. An unenchanted pickaxe works properly. If it helps, this ore is rendering incorrectly as well, displaying the Quicksoil Glass texture instead of the proper one.

**Expected behavior**
The ore should mine normally.

**Screenshots**
Not applicable

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

[crash-2020-04-18_12.42.36-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4497061/crash-2020-04-18_12.42.36-server.txt)

**Comment by CalaMariGold** [comment]
Issue for Dungeon Tactics GitHub

**Comment by cheshyrp** [comment]
Roger that. I've posted on their Curseforge page.

**Comment by democat3457** [comment]
https://www.curseforge.com/minecraft/mc-mods/dungeon-tactics/issues/132 just putting this here for reference

**Comment by kil0byt3** [comment]
^ Seems to be solved as per above link. Perhaps in next ver of mod

**Comment by democat3457** [comment]
Fixed in dev.
