### ISSUE TITLE
[BUG]Books with disabled enchantments spawn in roguelike dungeon chests

### ISSUE THREAD

**Issue by elephantae** [Rebirth-of-the-Night/Rebirth-Of-The-Night#263]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Pretty much the title. Roguelike dungeon chests still spawn with enchanted books that have disabled enchantments on them.

**To Reproduce**
Steps to reproduce the behavior:Go to the beneath and run around a dungeon in spec and check the chests until you find a book with a disabled enchantment.

**Expected behavior**
Disabled enchantments are expected to be removed from the loot tables.

**Screenshots**
![image](https://user-images.githubusercontent.com/36980723/79663161-077b5700-8172-11ea-98f4-1f7219a7b564.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer:Both
 - Version the world was created on:2.77

**Additional context**
This is unrelated to the bug however there is a very minor bug of every chest in the dungeon spawning facing north. Also unrelated, the loot from them feels a bit meh for the gamestage you're at there, maybe make the lowest levels' chests have chances to spawn mythril nuggets or ingots in addition?

**Comment by democat3457** [comment]
Eh? Upcoming fix?
