### ISSUE TITLE
[BUG] Invulnerable rats

### ISSUE THREAD

**Issue by Sissej** [Rebirth-of-the-Night/Rebirth-Of-The-Night#264]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Whether it is ranged, melee, drowning, traps, anything, rats who are not plagued does not take damage. They can't be tamed either. They hang around and attack any approaching player.
They appeared after a rat/flute invasion with the text "you hear the haunting melody of a flute growing louder".

**To Reproduce**
Wait out a rat invasion and attempt to kill the remaining rats without plague effect after the sun has risen. After the message "The mobs leave as the sun rises".

**Expected behavior**
The remaining rats without plague effect does not take any kind of damage no matter how it is dealt, and as a result, they don't die.

**Screenshots**
Well it's just a rat that doesn't take damage. 

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.76

**Additional context**
I haven't had acces to lava to test if that would kill them. Neither have i stacked up 128 blocks from sea level in attempt to despawn them faster. They are trapped under my base, so they are not exposed to sunlight, if that's of importance. I tried restarting the game to no avail.
They did eventually despawn, after waiting for one whole day/night cycle (~40 minutes).

**Comment by SandwichHorror** [comment]
add your thumbs-up and comment here
https://github.com/Alex-the-666/Rats/issues/163
