### ISSUE TITLE
[CRASH] Crash when breaking certain variants of the rat's garbage pile block

### ISSUE THREAD

**Issue by GoldenZdude** [Rebirth-of-the-Night/Rebirth-Of-The-Night#271]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Game crashes when breaking certain variants of the rats "garbage pile" in survival
**To Reproduce**
1. break rats:garbage_pile in survival
2. certain variants of the block will drop a missing texture, crashing the game

**Crash Log**
https://pastebin.com/9nN0MHtV

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by SandwichHorror** [comment]
Can you post this here
https://github.com/Alex-the-666/Rats/issues

Also how did you get the garbage block? It's supposed to be disabled - did it come from a villager trade?

**Comment by GoldenZdude** [comment]
yes, plague doctor trade.

**Comment by democat3457** [comment]
https://github.com/Alex-the-666/Rats/issues/241 reference
