### ISSUE TITLE
[BUG] Lunar Shield Tooltip

### ISSUE THREAD

**Issue by unicornbloods** [Rebirth-of-the-Night/Rebirth-Of-The-Night#272]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**

Lunar shield tooltip is not working correctly. Shows two tooltips.

**Expected behavior**

Should only show one tooltip

**Screenshots**

<img src="https://imgur.com/7lyTCCq.png">

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: server
 - Version the world was created on: 2.77.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by democat3457** [comment]
@unicornbloods does this happen with lunar edge as well?

**Comment by SandwichHorror** [comment]
Fixed in dev.
