### ISSUE TITLE
[BUG] Exploding Enchantment drops no experience on mob death

### ISSUE THREAD

**Issue by Insane96** [Rebirth-of-the-Night/Rebirth-Of-The-Night#276]
**Describe the bug**
While killing a mob with a Exploding Enchantment it drop no experience

**To Reproduce**
1. Get a Bow with Exploding (any level)
2. Kill a mob
3. (No) Profit (XP)

**Expected behavior**
Mobs should drop experience when killed with an Exploding Enchanted Bow

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77

**Comment by democat3457** [comment]
report to random enchantments github https://github.com/Tfarcenim/RandomEnchantments/issues

**Comment by SandwichHorror** [comment]
I think this is intended. The explosion destroys XP. You can either have a combustive finish to your arrows, or get XP from earning the kill like a real man.

**Comment by democat3457** [comment]
Makes sense to me.
