### ISSUE TITLE
[BUG]Dragon health displayed when riding

### ISSUE THREAD

**Issue by BBgunner007** [Rebirth-of-the-Night/Rebirth-Of-The-Night#288]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
A huge heart hit point display shows up on your screen when you ride your dragon.

**To Reproduce**
Tame a dragon by hatching one from an egg.  Grow until ride-able. Mount the dragon.

**Expected behavior**
No huge heart display which prevents visibility. 

**Screenshots**
Added
![image](https://user-images.githubusercontent.com/64240576/80298057-b31a3d80-8756-11ea-8978-af4a65073137.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
Other information includes the dragon was wearing iron armour.

**Comment by SandwichHorror** [comment]
Mount health is now off by default in BetterHUD. A workaround, and not a true solution, but if your dragon is really in danger you can still see its health bar via Neat.
