### ISSUE TITLE
[BUG] Block Dispenser and Dynamic Tree Saplings

### ISSUE THREAD

**Issue by JChiyah** [Rebirth-of-the-Night/Rebirth-Of-The-Night#289]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
The Block Dispenser, from Better With Mods, places vanilla tree saplings and not dynamic tree saplings.

**To Reproduce**

1. Place a Block Dispenser
2. Put some saplings inside the Block Dispenser
3. Give a redstone signal
4. A vanilla tree sapling is planted instead, not a dynamic tree seed

**Expected behavior**
A dynamic tree sapling should be planted, as when you (the player) plant a tree sapling by right-clicking.

**Screenshots**
![treebug](https://user-images.githubusercontent.com/12748955/80305788-058b4680-87b7-11ea-8972-979c66c13944.png)
[https://imgur.com/a/CRQ9bFs](https://imgur.com/a/CRQ9bFs)

The sapling on the left of the image was planted by the Block Dispenser, whereas the one on the right was planted right-clicking by the player

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.70 (confirmed in creative for world created in 2.77.1)

**Additional context**
Since vanilla tree saplings are disabled, these saplings never grow. I think this should either be turned off (the block dispenser placing these saplings) or allow the Block Dispenser to place Dynamic Tree saplings.
On the other hand, fixing this could allow for some tree farm automation towards mid game. Another alternative is to allow to plant trees by dispensing seeds. It would require more sophisticated setups to automate.
The option to allow seeds to plant themselves from Dynamic Trees is disabled in the mod config.

**Comment by ferreusveritas** [comment]
In the more recent versions of Dynamic Trees the sapling is placed like this but it will still grow into a Dynamic Tree. So this bug should be considered fixed in the mod.

**Comment by democat3457** [comment]
Also semi-related, but dispensers can't bonemeal dynamic trees from what I've heard? @ferreusveritas
