### ISSUE TITLE
[BUG] True Dark's Edge gives incorrect Personality on Hit

### ISSUE THREAD

**Issue by democat3457** [Rebirth-of-the-Night/Rebirth-Of-The-Night#293]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
After creating a True Dark's Edge in a steel anvil and hitting a mob with it, it turns into a Divine personality, but it should be Unholy instead. It is crafted with the Unholy personality, though.

**To Reproduce**
1. Forge a True Dark's Edge in a steel anvil.
2. Observe that the sword has the Unholy personality.
3. Hit a mob (tested on spiders and zombies).
4. Observe that the sword now has the Divine personality.

**Expected behavior**
The sword to retain its intended personality.

**Screenshots**
<img width="997" alt="Screen Shot 2020-04-27 at 1 45 11 PM" src="https://user-images.githubusercontent.com/32407067/80413525-35a91700-8895-11ea-95bc-277999e63d5b.png">

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
Tbh idk

**Comment by SandwichHorror** [comment]
Couldn't replicate this on dev 2.78 build after crafting and killing about three dozen enemies with different TDE, though I did notice several other problems.

**Comment by democat3457** [comment]
That's weird. I'll try a new world tomorrow.

**Comment by democat3457** [comment]
Hm I can repro on a different world.

**Comment by democat3457** [comment]
Happens with TLE on new world, 2.77.3

**Comment by SandwichHorror** [comment]
Think I know the problem here.

**Comment by SandwichHorror** [comment]
Update: I don't.

**Comment by democat3457** [comment]
lmao whatd you think it was?

**Comment by SandwichHorror** [comment]
In past testing I thought it was due to the 
[weight]
100

being off, since we don't have the expected "1 of X random personalities" but "Crafting these specific items always gets you X personality", but it was properly set to 100. Might be something wrong with the way the enchants are mapped

**Comment by CalaMariGold** [comment]
Still occurs in 3.0. Happens nearly every time for me. We need to commission a new living weapon mod in order to fix this.

**Comment by KaleThyself** [comment]
I'm unable to replicate this in 3.2.1a. The issue appears to be resolved.
