### ISSUE TITLE
[BUG] Invasions occur every 7.25 days

### ISSUE THREAD

**Issue by democat3457** [Rebirth-of-the-Night/Rebirth-Of-The-Night#298]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Invasions start off on days 7, 14, and 21, but then they add one for every four invasions, so 29, 36, 43, 50, (+1) 58, 65, 72, 79, (+1) 87, 94, 101, 108, etc. (Invasions occur every `floor(7.25x)`th night)

**To Reproduce**
1. Wait until day 27
2. Observe there is no invasion on the night of day 28.
3. Observe there is an invasion on the night of day 29.
4. Wait long enough to see a pattern.

**Expected behavior**
Invasions should occur every 7 days.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77

**Additional context**
I believe it's something wonky about HW Invasions' night checking thing, but I couldn't find the source of the bug.

**Comment by democat3457** [comment]
<img width="577" alt="Screen Shot 2020-04-30 at 6 13 15 PM" src="https://user-images.githubusercontent.com/32407067/80767805-634cc500-8b0e-11ea-9c45-a99ee04d878e.png">
Also this?

**Comment by kil0byt3** [comment]
we still need to look at this, does it still happen with the 9 day change?
