### ISSUE TITLE
[BUG] Blood Moon during day

### ISSUE THREAD

**Issue by JustinLTu** [Rebirth-of-the-Night/Rebirth-Of-The-Night#302]
**Describe the bug**
I got a Blood Moon during the day.

**To Reproduce**
Unsure

**Expected behavior**
I'm guessing Moon events should only happen at night?

**Screenshots**
![image](https://user-images.githubusercontent.com/13356915/80924258-c4f27680-8d3c-11ea-8dff-8ace46f2c337.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
It was also raining, when the Blood Moon rose.

**Comment by democat3457** [comment]
Have you touched the time at all? (Especially using `/time set` or `/time add`)

**Comment by JustinLTu** [comment]
I have not.

**Comment by SandwichHorror** [comment]
same as #458, closing as it's the same issue.
