### ISSUE TITLE
[Bug] [Vanishing Hippogryph]

### ISSUE THREAD

**Issue by Masecalibur** [Rebirth-of-the-Night/Rebirth-Of-The-Night#306]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
When I'm flying on a griffin i have tamed, the game may sometimes stop responding. i will reload and the game will return me to the location i was before i mounted my Hippogryph. My Hippogryph is then gone, forever.

**To Reproduce**
Steps to reproduce the behavior: Fly around on a Hippogryph, wait for game to stop responding. Reload game

**Expected behavior**
Either be back at my base or find my griffin at the place the program stopped responding

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
Sorry, i meant to say it stopped responding. I'm a bit new to this kind of thing.

**Comment by democat3457** [comment]
You said it crashes it, can we get the crash log?

**Comment by Masecalibur** [comment]
Sorry i meant to say it stops responding. I tried to find a crash report but there wasn't one.

**Comment by democat3457** [comment]
If I had to guess, this'd be the computer trying to catch up with chunk loading and skipping over or unloading entities as it works. Is this reproducible on latest?

**Comment by KaleThyself** [comment]
This issue does not appear to be reproducible on latest (2.77.5) as I've tried flying around on a hippogryph with various render distances without any issues such as the game not responding or crashing.

**Comment by democat3457** [comment]
Will close for now in that case. Hippogryphs are generally buggy anyway, especially on lower-end systems.
