### ISSUE TITLE
[BUG] Triple chest

### ISSUE THREAD

**Issue by democat3457** [Rebirth-of-the-Night/Rebirth-Of-The-Night#323]
**Describe the bug**
A triple chest can be created, with three times the storage, thanks to the pickup ability of chests.

**To Reproduce**
1. Place down a double chest.
2. Pick up a chest.
3. Stand beside the double chest (where the triple chest would go)
4. Put walls around you and a slab above you (so you are crouching with no way to go)
5. Die.
6. Observe that the chest was put down in the only available space, the spot next to the double chest.
7. Open the middle chest and see that it has triple the storage.

**Expected behavior**
Not to be able to drop the chest down and create a triple chest...? Sounds more like cheese...

**Screenshots**
![image](https://user-images.githubusercontent.com/32407067/81511600-21770800-92e0-11ea-87ac-27209f6a144f.png)
![image](https://user-images.githubusercontent.com/32407067/81511603-26d45280-92e0-11ea-9947-0cfd420d9405.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.1

**Additional context**
From CurtiAn#0395

**Comment by Eksekk** [comment]
very obscure bug, probably needs to be taken to CarryOn developers

**Comment by democat3457** [comment]
https://github.com/Tschipp/CarryOn/issues/238 CarryOn issue made

**Comment by democat3457** [comment]
Because this is such an edge case and has a really minor impact on the game, this will not be pursued any further.
