### ISSUE TITLE
[BUG] Door dupe

### ISSUE THREAD

**Issue by Von-Biscuit** [Rebirth-of-the-Night/Rebirth-Of-The-Night#339]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Breaking the top block of a bone-cincinnastite door causes it to duplicate

**To Reproduce**
Steps to reproduce the behavior: Place a bone-cincinnastite door and then break the top block to destroy it.

**Expected behavior**
Only one door should drop from breaking one.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.2.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
99% sure this was fixed a long time ago 
![image](https://user-images.githubusercontent.com/57605926/81863845-d22c1400-9539-11ea-9b1b-44065bdf905e.png)

**Comment by Von-Biscuit** [comment]
I just checked it in a single player world. It is just the bone-cincinnastite door, and only if you break the top block of the door.

**Comment by CalaMariGold** [comment]
Still an issue in 3.0. Probably can fix via dropt by removing the loot table then adding it back again

**Comment by democat3457** [comment]
Does this happen for bone reed doors as well?

**Comment by CalaMariGold** [comment]
Yes

**Comment by democat3457** [comment]
will be fixed in beta 5 with new betternether fork
