### ISSUE TITLE
[BUG] Pigtificate enchanter gives blank enchanted book

### ISSUE THREAD

**Issue by democat3457** [Rebirth-of-the-Night/Rebirth-Of-The-Night#346]
I**Describe the bug**
A trade can be found that gives a blank enchanted book for amethyst.

**To Reproduce**
1. Summon pigtificates until you get an enchanter with an enchanted book trade.
2. Look at the enchantments on the book.

**Expected behavior**
To give an enchanted book with enchantments.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.77.2.1
 - Server or Singleplayer: SP
 - Version the world was created on: 2.77.2.1

**Additional context**
🤷 config/netherex/trades/netherex/enchanter.json line 58?

**Comment by CalaMariGold** [comment]
probably trading an enchantment that's disabled, haven't checked that json yet

**Comment by CalaMariGold** [comment]
https://github.com/LogicTechCorp/NetherEx/issues/259

**Comment by CalaMariGold** [comment]
![image](https://user-images.githubusercontent.com/57605926/99337530-71ff8d00-2850-11eb-9398-559fb4c55dd9.png)
lmao well that's why the enchanted book specifically doesn't have any enchants

**Comment by CalaMariGold** [comment]
Fixed in 3.0
