### ISSUE TITLE
[BUG] Light Essence not appearing on the bottom of the end island

### ISSUE THREAD

**Issue by VaeVicti** [Rebirth-of-the-Night/Rebirth-Of-The-Night#361]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Light Essence not being below the end portal at the bottom of the end island

**To Reproduce**
Bug being there by default on the newest version

**Expected behavior**
Light Essence being added to the location

**Info (please complete the following information):**
 - Modpack Version: 2.77.4
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.4

**Additional context**
All I did was dig out every block beneath the end portal on the end dragon island and there was no light essence to be found. Either it is a bug or the description of the Item “Light Essence” is misleading.

**Comment by democat3457** [comment]
Temporarily fixed by 5048ecfc59ae7f2a2765ed2a07bd6cb654036a18

**Comment by democat3457** [comment]
@Foreck1 Can you OSV this?

**Comment by CalaMariGold** [comment]
fixed in 3.0
