### ISSUE TITLE
[BUG] Lighting Issue

### ISSUE THREAD

**Issue by Orangemes** [Rebirth-of-the-Night/Rebirth-Of-The-Night#370]
**Describe the bug**
Everything around me is dark, and  even glowstone dosent produce any light.

**To Reproduce**
Steps to reproduce the behavior: Close the game and start it again.

**Screenshots**
https://user-images.githubusercontent.com/65219829/83938869-99015f80-a7d8-11ea-98de-c74f7bdd8848.PNG

**Info (please complete the following information):**
 - Modpack Version: 2.6
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.6

**Additional context**
I believe some mod caused the lighting issue.

**Comment by democat3457** [comment]
This is a super old version, try updating and see if it fixes it?

**Comment by democat3457** [comment]
Also, are you using any shaders?

**Comment by SandwichHorror** [comment]
2.6 may as well be ancient history now.
