### ISSUE TITLE
[BUG] Mythril Bow dropping on ground when an enemy is hit with it

### ISSUE THREAD

**Issue by SlyCedix** [Rebirth-of-the-Night/Rebirth-Of-The-Night#376]
**Describe the bug**
Whenever an enemy is hit with an arrow or punched with the Mythril bow, it is dropped. If used from the offhand, the item in the main hand is dropped. It does not occur every time, probably around 90% of the time.

**To Reproduce**
Unknown, both myself and the other player on my server (a fresh 2.77.5 server files download with no changes) are experiencing this issue.

**Expected behavior**
The bow remains in the hand after using it.

**Screenshots**
https://files.catbox.moe/be3ezq.mp4
https://files.catbox.moe/4jwzp1.png

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.4

**Comment by democat3457** [comment]
Can you send a screenshot of the bow in your inventory (like the tooltip)?

**Comment by democat3457** [comment]
Oh it's on Discord already, nevermind.

**Comment by SlyCedix** [comment]
Updated issue with the screenshot so that there's no need to scroll through discord

**Comment by democat3457** [comment]
Does this happen with other mythril bows?

**Comment by SlyCedix** [comment]
Happens with the other person on the server's bow as well

**Comment by democat3457** [comment]
Does this happen on a new world?

**Comment by SlyCedix** [comment]
Looks like it does not, also the crafted one in the new world has phasing, whilst the ones in the world from 2.77.4 do not

**Comment by SlyCedix** [comment]
The NBT of the bow shows it has enchant 129, but when trying to manually apply enchant 129 to an item, including the mythril bow I get the following error https://files.catbox.moe/n2c6q4.png

**Comment by SlyCedix** [comment]
Just put it in a disenchanter and this is the book that came out: https://files.catbox.moe/rzr92q.png

**Comment by democat3457** [comment]
Strange... I just crafted a Mythril Bow in the dev version and got a bow with some form of levitation enchant that gives mobs levitation? It has ID 110 and also can't be cheated onto anything...

**Comment by democat3457** [comment]
Appaently it's an enchantment called Weapons that's also disabled

**Comment by democat3457** [comment]
Apparently it's actually supposed to be phasing... or is it supposed to be Homing? Idk, but its a very erratic bug.

**Comment by CalaMariGold** [comment]
Probably had the butterfingers enchant or something similar. You got the wrong enchant likely because you updated the modpack but started the world on an older version.
