### ISSUE TITLE
[CRASH] Pack Launch Crash

### ISSUE THREAD

**Issue by SlavvyMcStabby** [Rebirth-of-the-Night/Rebirth-Of-The-Night#381]
**Describe the crash**
I try to launch the pack, and it crashes without even launching after updating pack
**To Reproduce**
Try and launch the pack

**Crash Log**
https://paste.ee/p/VljTb
**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Neither
 - Version the world was created on: 2.77.5

**Additional context**
This crash only happens after I updated it

**Comment by democat3457** [comment]
Well you see, there are duplicate mods in the mods folder that have different versions (for example, AppleCore has both versions 3.2 and 3.4), meaning that it was updated incorrectly, I'd assume.
