### ISSUE TITLE
[BUG] Redstone circuits breaking certain objects when powered on/off

### ISSUE THREAD

**Issue by Dumbino** [Rebirth-of-the-Night/Rebirth-Of-The-Night#383]
**Describe the bug**
Simply put, any time seemingly any redstone object powers other things on/off (tested with the weather sensor and lever), it randomly breaks a few choice objects (for me, axles and redstone repeaters. It's uncommon, but might happen more depending on how long the line of redstone/mechanical stuff you have is. There is nothing wrong with the setup—it was working fine a few versions ago and I haven't changed it since then.

**To Reproduce**
Set up a long line of anything redstone powered (for consistency's sake, include redstone repeaters and/or axles in it) and repeatedly power it on and off using any method (try a lever). Certain pieces will break, seemingly at random. It's easiest to see with a long line of axles and gearboxes; a completely random few axles will break. The gearboxes don't seem to.

**Expected behavior**
For everything to stay put as tile entities and power as normal, rather than drop on the ground for no discernible reason.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.1

**Additional context**
Nothing really. I know it's happening with at least a few people and regardless of the setup, so it has to be some kind of bug with the new version (though I only played the world on 2.77.5 and 2.77.1). I tested it with my fancy windmill setup, which I just recently added a weather sensor to so it would power off during storms, and the one redstone repeater I'm using to help connect it through a wall just broke, so I know it's axles and redstone repeaters that can break and drop from being powered on or off. There are probably more than just those that are susceptible though.

**Comment by democat3457** [comment]
Axles are buggy from BWM, but redstone doesn't seem to have a problem. If this issue reoccurs with the redstone part (not the axles part) on 3.0, then reopen this issue.
