### ISSUE TITLE
[BUG] Chairs can't sit on

### ISSUE THREAD

**Issue by xoonsa** [Rebirth-of-the-Night/Rebirth-Of-The-Night#384]
**Describe the bug**

Chairs can't  sit on
**To Reproduce**
watch vid
**Expected behavior**

watch vid
**Screenshots**

https://gyazo.com/b89f790102846376daec40e642e49048 <<short vid here

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by democat3457** [comment]
What chair is that?

**Comment by xoonsa** [comment]
Rustic mod's chair

Colin Wong <notifications@github.com> 於 2020年6月12日 週五 下午10:50寫道：

**Comment by KaleThyself** [comment]
I can confirm that Rustic wood chairs have the same issues in RoTN 2.77.5 as shown in the gif OP linked. However, you're eventually able to sit on them by spamming the interact button repeatedly. This issue occurs with every type of wood chair from Rustic.

**Comment by democat3457** [comment]
Can also confirm on dev version

**Comment by KaleThyself** [comment]
This bug was magically fixed in 3.2.1a...
