### ISSUE TITLE
[BUG] Campfire destroy items

### ISSUE THREAD

**Issue by TBiscuit1** [Rebirth-of-the-Night/Rebirth-Of-The-Night#387]
**Describe the bug**
Campfire destroy items

**To Reproduce**
Either drop items on the campfire or cook items

**Expected behavior**
The campfire shouldn't destroy items

**Screenshots**
No screenshots

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer (also work on multiplayer)
 - Version the world was created on: 2.77.5
Infos are not neccesary but still gonna put them

**Additional context**
There is a new version of FutureMC that correct that bug, just need to update the mod

**Comment by democat3457** [comment]
Haha if you want to update it go ahead. The update introduces a very finicky mod id change that requires a total world reset. Futuremc update is planned and will be in 2.78 (check Trello).
