### ISSUE TITLE
Pack freezing on startup

### ISSUE THREAD

**Issue by wynn-nn** [Rebirth-of-the-Night/Rebirth-Of-The-Night#388]
**Describe the crash**
I opened ROTN 2.77.5 through the Twitch launcher (with Optifine) for the first time. The loading screen got stuck on “initialisation: mod pack config checker” and then Minecraft stopped responding. I tried reinstalling without adding Optifine, but got the exact same issue multiple times. I was using java 1.8.0.232 (64 bit) and I had ~5.5 gigs allocated (out of 8) to Minecraft.

**To Reproduce**
1. Download ROTN 2.77.5 through the Twitch launcher. It does not matter if Optifine is also installed.
2. Launch the modpack.

**Crash Log**
[debug.log](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4773816/debug.log)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: NA (pack did not load)
 - Version the world was created on: NA

**Additional context**
I am using a 2015 13-inch MacBook Pro with 8GB RAM. I usually do not have many issues running modded Minecraft (or vanilla Minecraft, for that matter).

**Comment by democat3457** [comment]
As far as I know, it's just taking a long time to load - it's going through all the entities and removing their spawn eggs.
