### ISSUE TITLE
[BUG] Non-vanilla chests not outputting to comparators in 2.77.5

### ISSUE THREAD

**Issue by Nyagi** [Rebirth-of-the-Night/Rebirth-Of-The-Night#390]
**Describe the bug**
Chests that are a part of that mod that makes them textured to the type of wood they are crafted with do not output to a comparator.

**To Reproduce**
Steps to reproduce the behavior: Place a chest textured to its wood type, fill it with items, and attempt to pull a signal out with a comparator. 

**Expected behavior**
No signal will be outputted unless it's a vanilla chest

**Screenshots**
![2020-06-13_03 01 27](https://user-images.githubusercontent.com/33533469/84562388-35b88580-ad22-11ea-940a-f9ca3f5270e0.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Comment by democat3457** [comment]
https://github.com/CharsetMC/Charset/issues/446

**Comment by asiekierka** [comment]
Fixed as of Charset Lib 0.5.6.5.
