### ISSUE TITLE
[BUG] Barako VIllage Spawns in Nether

### ISSUE THREAD

**Issue by MaxKelton** [Rebirth-of-the-Night/Rebirth-Of-The-Night#398]
**Describe the bug**
A Barako village from the mod Mowzie's Mobs has spawned in the Nether.

**To Reproduce**
Go in the Nether and look around I guess

**Expected behavior**
A Barako village has a chance to generate in the Nether, including the sun chief

**Screenshots**
![2020-06-16_13 29 17](https://user-images.githubusercontent.com/9955652/84825354-2c574380-afd6-11ea-9662-d463dfa8dfa8.png)
![2020-06-16_13 29 50](https://user-images.githubusercontent.com/9955652/84825365-2eb99d80-afd6-11ea-82a9-350ad1c2cdba.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by SandwichHorror** [comment]
fixed in the next version on mowzies mobs' end
