### ISSUE TITLE
Tide Arrow Dupe, Shoot and pick up tide arrow[DUPE]

### ISSUE THREAD

**Issue by CristoZDG** [Rebirth-of-the-Night/Rebirth-Of-The-Night#399]
**Describe the bug**

When you shoot a tide arrow at the floor it dupes.
**To Reproduce**
Enchanted Mythril Bow, Diamond Quiver (unsure)

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.4

**Additional context**

**Comment by Feivian4** [comment]
It seems to be an issue with the mythril bow, it dupes any arrow

**Comment by dekuraan** [comment]
I'm pretty sure if you put arrows in your hotbar and shoot them from a mythril bow it results in a dupe.

**Comment by CalaMariGold** [comment]
Intended behavior. The "Efficiency" tooltip means that you get extra arrows. We'll fix up the tooltip to be more clear.
