### ISSUE TITLE
[BUG] Spider hitbox acting strange

### ISSUE THREAD

**Issue by Daardain** [Rebirth-of-the-Night/Rebirth-Of-The-Night#402]
**Describe the bug**
The 'spider' mobs doesn't have an accurate hitbox while wielding a saber, requiring players to usually strike the centre from above in order to land a strike.

**To Reproduce**
Try to hit it with a saber.

**Expected behavior**
It will be very, very difficult, and roughly half the strikes from the front will not affect it.

**Screenshots**
https://clips.twitch.tv/DeadAliveTigerStrawBeary

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: SMPRebirth
 - Version the world was created on: 2.77

**Additional context**
I've only seen it happen with the saber, but I've noticed whiffs every so often with other weapons that I just assumed were my screw-ups. The saber misses more times than reasonable.

**Comment by democat3457** [comment]
Can't reproduce on dev.

**Comment by SandwichHorror** [comment]
This may be related to spiders being able to hit through blocks, but I've encountered that in personal packs as well. Spiders can be a bit wonky even in vanilla 1.12.2.

**Comment by kil0byt3** [comment]
Likely duplicate of #204. Stale.
