### ISSUE TITLE
[BUG] Cave roots follow old food system

### ISSUE THREAD

**Issue by yareyaredazeu** [Rebirth-of-the-Night/Rebirth-Of-The-Night#407]
**Describe the bug**

Cave roots still follow the old food system and take a long time to eat
**To Reproduce**
eat a cave root
**Expected behavior**

the root should be eaten at a normal speed
**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer:
 - Version the world was created on:
2.77.5
**Additional context**

**Comment by democat3457** [comment]
As far as I can tell, the difference is, maybe, a second more than a carrot. Really not quite much of a difference. Also, I doubt we can change how fast you eat certain foods.
