### ISSUE TITLE
[BUG] Moving Powered Block Dispensers Deletes Stored Items 

### ISSUE THREAD

**Issue by AceScizor** [Rebirth-of-the-Night/Rebirth-Of-The-Night#408]
**Describe the bug**

If a block dispenser is powered before or during being moved by a piston, and not un-powered, the dispenser will place/dispense its currently selected item and be pushed by the piston; all remaining items inside the dispenser will be deleted.  This does not occur if the dispenser is un-powered before being pushed.

**To Reproduce**
Option A:
  1. ) Place items in block dispenser
  2. ) Power block dispenser
  3. ) Move block dispenser with piston

Option B:
  1. ) Place items in block dispenser
  2. ) Power block dispenser and piston at the same time

**Expected behavior**

Block dispenser will place/dispense its currently selected item from its inventory, then be pushed by the piston and retain its remaining inventory.

**Screenshots**

![2020-06-24_17 04 42](https://user-images.githubusercontent.com/67394455/85632395-de2cea80-b63c-11ea-922c-3d25509fbf46.png)
Both situations result in deleted inventories.

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

I would prefer this issue to remain unfixed rather than have block dispensers removed or be unable to be pushed by pistons.

**Comment by kil0byt3** [comment]
Edge case. Quark’s TE moving ability is obviously conflicting with how BWM does inventory for BDs. As Quark no longer updates old versions this may have to be part of QuarkFork. Easy solution would be making BDs unpushable but all the redstone nerds will be up in arms :)

**Comment by KaleThyself** [comment]
Closed due to inactivity and wontfix.
