### ISSUE TITLE
[BUG]Monitoring crystal chat spam

### ISSUE THREAD

**Issue by Nattas** [Rebirth-of-the-Night/Rebirth-Of-The-Night#410]
**Describe the bug**
Chat spam when replacing monitoring crystals, then opening a manifest lectern spams user chat.

**To Reproduce**
- Place monitoring crystal on inventory item (chests, cabinets, etc.)
- Break then replace monitoring crystal
- Open up manifest lectern

**Expected behavior**

Chat not to be spammed when opening manifest lectern

**Screenshots**

https://imgur.com/NDnxRxO

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5

**Additional context**

Replacing multiple times duplicates spam message

**Comment by democat3457** [comment]
Opened issue report: https://github.com/AranaiRa/ArcaneArchives/issues/100

**Comment by democat3457** [comment]
Fixed in Arcane Archives dev version, waiting on mod update.

**Comment by democat3457** [comment]
Mod update dropped 30 minutes ago. Will look into it tmrw.
