### ISSUE TITLE
[BUG] DT Error When Breaking Aether Ores

### ISSUE THREAD

**Issue by toErIpNid** [Rebirth-of-the-Night/Rebirth-Of-The-Night#412]
**Bug With Fortune on Diamond Pic**
Whenever I try to mine ice stone or zanite ore with a diamond pic which has fortune 3 the dungeon tactics bug shows up in the corner of the screen.

**To Reproduce**
Enchant dia pic with fortune 3 and try to mine zanite ore.

**Expected behavior**

Me to get zanite gemstones. Only for them to not drop and the bug to appear.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singlepalyer.
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by democat3457** [comment]
Send log pls

**Comment by democat3457** [comment]
Also, have you tried placing a torch and breaking it with your fist before mining it?

**Comment by democat3457** [comment]
Common issue, and inactive. Closing
