### ISSUE TITLE
[BUG] Sorting in Radiant chests is buggy

### ISSUE THREAD

**Issue by BurgerFan45** [Rebirth-of-the-Night/Rebirth-Of-The-Night#419]
**Describe the bug**
Pressing the sort key while in a radiant chest will move items irregularly and split full stacks into multiple non-full stacks

**To Reproduce**
Open radiant chest
Put like 500 rottenflesh & bones in it
Press whatever button you set sort to
watch how it splits the items into multiple stack of weird numbers and generally acts weird.

**Expected behavior**
It should be stacking up to it's limit like it does in a vanilla chest/ double chest and not put rotten flesh into a row of bones.

**Screenshots**
![2020-07-04_13 57 31](https://user-images.githubusercontent.com/24676340/86504750-f7cdef00-bdff-11ea-82a9-da4ef8cc8f37.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: does the same on both
 - Version the world was created on: 2.77.5

**Additional context**
Probably an incompatibility between the sorting mod and arcane archives.

**Comment by BurgerFan45** [comment]
Pressing merge also doesn't work with radiant chests

**Comment by democat3457** [comment]
Sorting system is no longer planned in 1.12 by ArcArc, so closing as cant/wontfix
