### ISSUE TITLE
(possibly) bugged achievements [BUG]

### ISSUE THREAD

**Issue by TheSupremeOreo** [Rebirth-of-the-Night/Rebirth-Of-The-Night#422]
**Describe the bug**

Multiple broken/bugged achievements
**To Reproduce**
just check achievements
**Expected behavior**

to be able to complete the achievements
**Screenshots**

![2020-07-09_14 10 51](https://user-images.githubusercontent.com/67926334/87083426-32fe6280-c1f2-11ea-9bbf-fc652c4b1bc3.png)
![2020-07-09_14 18 26](https://user-images.githubusercontent.com/67926334/87083428-3396f900-c1f2-11ea-90b3-b7d5d832dac1.png)
![2020-07-09_14 18 39](https://user-images.githubusercontent.com/67926334/87083431-3396f900-c1f2-11ea-8a3e-94fec309c2e7.png)
![2020-07-09_14 18 43](https://user-images.githubusercontent.com/67926334/87083433-342f8f80-c1f2-11ea-985d-6d83f9aaac41.png)
![2020-07-09_14 18 56](https://user-images.githubusercontent.com/67926334/87083435-342f8f80-c1f2-11ea-8213-a5c17571cd7c.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: single
 - Version the world was created on: 2.77.3

**Additional context**

ill just go over the achievements
1. the "Hydra Chop, Baby!" achievement is impossible to get based on my testing, you cant eat at 0 hunger and 0 hunger is instadeath either way.
2. the "Planters" achievement isn't a "bug" per se but i think the description could use some more context, i've been unable to get it myself even after doing what i thought you're supposed to.
3. In 2 of 3 worlds i've made the "Heart Broken" achievement didn't register even though i had mined the ore multiple times
4. There are 3 achievement that don't count towards anything in the Perfectly Ready tab, ill show the screenshot

**Comment by democat3457** [comment]
The mod achievements I'm pretty sure we can't change
