### ISSUE TITLE
[BUG] Honey from the Nether Wasp hives has no use and is not compatible with other honey mods/recipes in its current implementation.

### ISSUE THREAD

**Issue by ThetasFiasco** [Rebirth-of-the-Night/Rebirth-Of-The-Night#423]
**Describe the bug**
The honey from the Nether Wasp hives, both in the liquid and block forms, is both useless in its current implementation and does not appear in JEI. The honey blocks and bottles of honey are not compatible with crafting recipes that require blocks or bottles of honey, and there's no way that's made clear to turn either form of this honey into a usable form.

**To Reproduce**
Steps to reproduce the behavior: It's just how the game is, man, I don't know what else you want me to tell you...

**Expected behavior**
Honey that takes a considerable amount of effort to get shouldn't be absolutely useless?

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Both
 - Version the world was created on: 2.77.5

**Additional context**
Not additional context, but an additional bug. The liquid honey can be used to create equally useless (as far as JEI is concerned) mead, and the process can lead to free repair of clay buckets. Simply put a damaged bucket full of useless honey into the input of a brewing barrel and BAM! Brand new clay bucket. At least this shit's worth something, even if it's unintended.

**Comment by democat3457** [comment]
Info: Honey obtained is BOP Honey. Use `/give @p biomesoplenty:honey_block` to obtain the honey block. The BOP Honey liquid is finite and spreads across ground, while also giving Slowness III for a few seconds after passing through the honey. When honey touches another liquid (I think), the block that had liquid honey turns into a BOP honey block.

**Comment by democat3457** [comment]
honey rework happened pog
