### ISSUE TITLE
[BUG] Wolf cape not providing modifier stats when worn in bauble slot

### ISSUE THREAD

**Issue by Lucria** [Rebirth-of-the-Night/Rebirth-Of-The-Night#425]
**Describe the bug**
Wolf capes worn on bauble slot does not provide any stats or quality bonus. It will only provide these stats when worn in chestplate slot.

**To Reproduce**
Put wolf cape with stats (jump height or speed boost) in chestplate versus putting wolf cape with stats in bauble (body) slot.

**Expected behavior**
Wolf cape should provide its stats and buffs when placed in bauble (body) slot.

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5

**Comment by Kompreya** [comment]
I just took a look at this.

Quality Tools has slot-specific qualities. Example, you might have a quality that says "When on body: +4% projectile damage"

Having slot specific qualities is intended, however, it seems like we didn't create any qualities for bauble slots for the capes. So I can fix this for next update. Less of an actual bug and more of an 'oops we forgot to change configs to make them useful in bauble slots'
