### ISSUE TITLE
[BUG] Exp Pylon+Learning Buff 

### ISSUE THREAD

**Issue by TheoVwj** [Rebirth-of-the-Night/Rebirth-Of-The-Night#429]
**Describe the bug**
So to keep it short, basically if you have the learning buff (full diamond armor) and you use the exp pylon, you can create infinite exp, which doesn't hurt at first,(excluding the fact that the pylon is now at -xxx levels) but once you die, you can crash servers.

**To Reproduce**
 Step 1: Wear full diamond armor (we used full mythrill with a sword and shield)
 Step 2: Use exp pylon (Set to spray)
 Step 3: Die
 Step 4: World domination (RIP [server)](url)

**Screenshots**
![2020-07-19_23 47 12](https://user-images.githubusercontent.com/68532141/87907913-5c04cb80-ca1a-11ea-914a-3d5e5a42bb66.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.6
 - Server or Singleplayer: Both
 - Version the world was created on: 1.12.2 (?)

**Additional context**
I am assuming this is because of the insane amount of exp drops it basically crashes any server.

**Comment by kil0byt3** [comment]
bruh

**Comment by Foreck1** [comment]
I'm probably going to remove the pylo altogether and replace it with an XP book mod

**Comment by democat3457** [comment]
pylon's alread gone
