### ISSUE TITLE
[CRASH] Stone Cutter

### ISSUE THREAD

**Issue by DraGoNaHE** [Rebirth-of-the-Night/Rebirth-Of-The-Night#432]
**Describe the crash**
 My game crashed when I attended on using the Stone Cutter, when making Stone Bricks specifically. A messaged popped up saying something like "crash happened because of 'Future MC'".

**To Reproduce**
Steps to reproduce the behavior: I was using this yellow-ish, mustard-y colored Stone in the Stone Cutter GUI, I hope that helps lol.

**Crash Log**
 
[crash-2020-07-23_18.42.39-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/4967842/crash-2020-07-23_18.42.39-client.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: The most recent one, I downloaded the Modpack on Monday

**Additional context**

**Comment by democat3457** [comment]
Did you shift-click on the output?

**Comment by democat3457** [comment]
Duplicate of #24 after reading identical crash logs.
