### ISSUE TITLE
[BUG] BoP Flower Fields dont Register on antique Atlas

### ISSUE THREAD

**Issue by CorporalHam** [Rebirth-of-the-Night/Rebirth-Of-The-Night#433]
**Describe the bug**

**To Reproduce**
Get an Antique Atlas

**Expected behavior**

Register Flower Fields on the map
**Screenshots**

https://i.imgur.com/GLgnIU9.png
**Info (please complete the following information):**
 - Modpack Version: Latest as of 7/23/2020
 - Server or Singleplayer: Server
 - Version the world was created on: Latest on 7/22/2020

**Additional context**

**Comment by democat3457** [comment]
Is that a flower field or a flower island, because 2.77.5 released with flower islands having water texture in the atlas. Dev version it's fixed, iirc.
