### ISSUE TITLE
[Breaking Quartzite Brick Slabs turns them into Andesite Brick Slabs]

### ISSUE THREAD

**Issue by Slapstickguy** [Rebirth-of-the-Night/Rebirth-Of-The-Night#434]
**Describe the bug**

**To Reproduce**
-Break Quartzite Brick Slab with Pickaxe

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by democat3457** [comment]
Duplicate of #362
