### ISSUE TITLE
[BUG] Potioncore.digSpeed (including Quality tools dig modifiers) and Living enchantment's leveling does not affect digging speed at all.

### ISSUE THREAD

**Issue by GitDiv7** [Rebirth-of-the-Night/Rebirth-Of-The-Night#435]
**Describe the bug**
potioncore.digSpeed attribute and living enchantment does not affecting digging speed at all.

**To Reproduce**
I've tried to change potincore.digSpeed or weapon's tag dig speed via nbtedit to 2048 (max digspeed value) and it does not work at all. But on clean minecraft installation with only PotionCore and QualityTools it works. Same for LivingEnchantment mod.

**Expected behavior**
Changing potioncore.digSpeed to 2048 -> destroying blocks like in creative mode (at least soft blocks).

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Both
 - Version the world was created on: 2.77.5

**Additional context**
Probably some of the mods constantly overrides digging speed

**Comment by CalaMariGold** [comment]
Confirmed and reproduced

**Comment by Kompreya** [comment]
Tried a few things myself. I even changed the operator to 2 (so it's a stacking %, wearing 4 baubles with 5% each should have increased dig speed by 20%), and still does not work. (Tested by mining obsidian with a diamond pick, same break time with and without baubles equipped)  

Other potion core attributes seem to work, such as jump height.

Reached out to dev on CF.

**Comment by Kompreya** [comment]
Bug found with Wards. PR submitted: https://github.com/OrderedChaos-Dev/Wards/pull/15

Awaiting update.

**Comment by democat3457** [comment]
fixed in wards fork
