### ISSUE TITLE
ClassNotFoundException loading server 2.77.5

### ISSUE THREAD

**Issue by klugemonkey** [Rebirth-of-the-Night/Rebirth-Of-The-Night#436]
**Describe the crash**
Stacktrace of ClassNotFoundException.  Server full stop.

**To Reproduce**
Install the server on Pterodactyl using Curseforge egg.  After successful installation, start server.  Its crashes during startup with 6GB ram.

**Crash Log**
https://paste.md-5.net/edipucucaj.sql

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 1.12.2

**Additional context**
First attempt at running the server.

**Comment by democat3457** [comment]
Send crash report in `crash-reports` folder.

**Comment by klugemonkey** [comment]
I think it was trying to load with minecraft_server not forge.
