### ISSUE TITLE
[CRASH] Crashing whenever i open my inventory (Due to jei.)

### ISSUE THREAD

**Issue by EchoTheNerd** [Rebirth-of-the-Night/Rebirth-Of-The-Night#437]
**Describe the crash**
 Basically, i was trying to find a better way of storing my items, so i looked up "Storage" in JEI, and as i was typing it, my modpack crashed. It said it was a problem with JEI and Arcane Archieves. So far, i can log in fine, but if i go back into my inventory it crashes. (This was a one time thing btw.)

**To Reproduce**
Steps to reproduce the behavior: honestly no idea

**Crash Log**
 Get link doesn't work, so im gonna use pastebin; https://pastebin.com/nJtKgGZ9

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on:  2.77.5

**Additional context**
 definitely a problem rendering an item in JEI.

**Comment by democat3457** [comment]
Do you have shaders installed? If so, try removing those - the Radiant Storage doesn't like displaying in JEI with shaders on.

**Comment by democat3457** [comment]
Inactivity.
