### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by dragonhunterpw** [Rebirth-of-the-Night/Rebirth-Of-The-Night#442]
**when i'm trying to download modpack i get information that it's missing some kind of addon **

**To Reproduce**

**Crash Log**

**Info (please complete the following information):**
 - Modpack Version: 
 - Server or Singleplayer:
 - Version the world was created on:

**Additional context**

**Comment by democat3457** [comment]
Known, it's a bug with Twitch and Curse. Apparently someone has been scraping Curse and downloading every site, making the site extremely laggy. Curse can't do anything about it and so it should last a few more days. For now, use MultiMC.

**Comment by dragonhunterpw** [comment]
Okay thank you for help

czw., 13 sie 2020, 06:16 użytkownik Colin Wong <notifications@github.com>
napisał:
