### ISSUE TITLE
[BUG] Getting killed by End Guard clears your inventory.

### ISSUE THREAD

**Issue by Kars3r** [Rebirth-of-the-Night/Rebirth-Of-The-Night#443]
**Describe the bug**
Going into the end and getting killed by an End Guard has a small chance to clear your inventory.

**To reproduce**
Steps to reproduce the behavior: Go to the end and get killed by an End Guard.

**Expected behavior**
To not clear the inventory.

**Info (please complete the following information):**

- Modpack Version: 2.77.5
- Server or Singleplayer: Server
- Version the world was created on: 2.77.5

**Comment by democat3457** [comment]
Do you know the exact chance? What exactly were you killed by (what did death message say)?

**Comment by Kars3r** [comment]
It said "slain by End Guard" and no I do not know the exact chance.

**Comment by listofwords** [comment]
had a similar issue, was killed by a parasite and my hotbar+armour was cleared, though I didn't lose my baubles

**Comment by CalaMariGold** [comment]
Reopen this if it happens again in 3.0
