### ISSUE TITLE
[BUG] when zombies break Ice it doesn't create water

### ISSUE THREAD

**Issue by listofwords** [Rebirth-of-the-Night/Rebirth-Of-The-Night#445]
**Describe the bug**
when a humanoid mob breaks ice above a lake it does not create the expected water block that would appear if a player broke it.

**To Reproduce**
-go to a frozen lake or wait until winter season
-get a zombie or something
-sit below the ice
-ice is deleted by mob mining it to pathfind to you

screenshot:
![2020-08-15_12 18 29](https://user-images.githubusercontent.com/69692590/90311413-8b600880-def2-11ea-9f81-956ec0cfb07b.png)

**Expected behavior**
for the ice to act like how it would if a player were to break it

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Singleplayer
 - Version the world was created on: 2.77.5

**Comment by Foreck1** [comment]
This can probably be fixed using Fragile Blocks but will fit better in a rework of water mechanics. My proposal being not being able to place ice blocks down anymore to get water out of where it's supposed to be.

**Comment by CalaMariGold** [comment]
Can't be fixed. This on EpicSiegeMod, which is no longer being maintained.

**Comment by CalaMariGold** [comment]
Fixed in a future beta (probably beta 4)
