### ISSUE TITLE
[BUG] Glaretorch Duplication (With torch rain)

### ISSUE THREAD

**Issue by dekuraan** [Rebirth-of-the-Night/Rebirth-Of-The-Night#448]
**Describe the bug**
Glaretorches duplicate if you put a single one in your off hand, have a stack of blocks in your main hand and have crouch bound as ctrl, crouch + jump + click to torch rain -> duplication (x64)

**To Reproduce**
Bind crouch to ctrl, put a single glare torch in your off hand, stack of items in main hand, then torch rain

**Expected behavior**
It shoots a single glaretorch

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by dekuraan** [comment]
@democat3457 Upon rereading my description, I realized it was not clear that you only need to have one glaretorch in your offhand when you do the torch rain action (it shoots however many items are in your main hand). I believe that it is taking the item count from your main hand, even though the single glaretorch is in your offhand.

**Comment by democat3457** [comment]
Ahhh gotcha.

**Comment by democat3457** [comment]
Actually this bug would be fixed in 2.78 because torch rain is removed. :D
