### ISSUE TITLE
[BUG] Having Too Much Fun

### ISSUE THREAD

**Issue by RoTNFan** [Rebirth-of-the-Night/Rebirth-Of-The-Night#449]
**Describe the bug**
This mod is well-made, and incredibly entertaining. This is causing me to get left behind in the real world. I haven't showered in a year, now. Please stop letting me play this mod. Help. Help me, help me please.

**To Reproduce**
Play mod.

**Expected behavior**
 Have usual amounts of fun.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 
 - Server or Singleplayer:
 - Version the world was created on:

**Additional context**

**Comment by CalaMariGold** [comment]
Hmm. I'm not sure we can fix this one honestly. Oh well

**Comment by RoTNFan** [comment]
Aw darn. I would stop playing but...- 
I can't.
I guess I'm trapped forever then.
Oh well, could be worse.
