### ISSUE TITLE
[BUG] Lighting breaks on grove sprites when you pick them up

### ISSUE THREAD

**Issue by DoctorNutmeg** [Rebirth-of-the-Night/Rebirth-Of-The-Night#451]
When you pick up a grove sprite, their lighting bugs out and they go all black.

**To Reproduce**
Pick up a grove sprite in-game.

**Expected behavior**
The grove sprite model continues to react to light normally.

**Screenshots**
![2020-08-21_00 40 06](https://user-images.githubusercontent.com/16837271/90853315-cd9ca600-e347-11ea-8a62-80e5a8ec3389.png)
![2020-08-21_00 40 58](https://user-images.githubusercontent.com/16837271/90853332-d7bea480-e347-11ea-8c01-3f337319d277.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Single Player
 - Version the world was created on: 2.77.5

**Additional context**
It's possible that this may be an issue with some other entities as well, though I haven't encountered that.

**Comment by SandwichHorror** [comment]
This is a consequence of entities having multiple possible textures and being picked up with CarryOn. The same issue can be observed with Pots from Rustic. I suspect that whatever system CarryOn uses to render the entity cannot handle multiple textures based on metadata, so it just turns black.

Not sure what can be done about it, but I consider this low priority.

**Comment by democat3457** [comment]
Created CarryOn issue here: https://github.com/Tschipp/CarryOn/issues/249

**Comment by Tschipp** [comment]
Do you have optifine? I'm not sure this issue is on my end though. Flickering is frequent with some carried entities, because they get recreated when they're rendered. Maybe this is the same issue here?

**Comment by democat3457** [comment]
Ah, yeah, this pack has optifine.

**Comment by democat3457** [comment]
Likely OptiFine problem. Just gotta deal with it then.
