### ISSUE TITLE
[SUGGESTION] Change Log

### ISSUE THREAD

**Issue by AdityaKumar5155** [Rebirth-of-the-Night/Rebirth-Of-The-Night#454]
Today, I take a look at changelog and found that on few mods like wings, Backpack Baubles(for Quark), have a horizontal line intersecting them. Is it mean that they will not add on the next update? If yes, then please try not to remove Backpack Baubles because equipping Backpack on the chest plate slot is very annoying.

**Comment by democat3457** [comment]
The strikethrough means they are tentative. Wings is likely getting moved to 2.78.1 (as seen on Trello), and Backpack Baubles currently has a game-breaking crash that remains to be fixed.

**Comment by AdityaKumar5155** [comment]
Thanks for Replying!
