### ISSUE TITLE
[BUG] grappling the ground and eating makes you eat 2x faster

### ISSUE THREAD

**Issue by kil0byt3** [Rebirth-of-the-Night/Rebirth-Of-The-Night#455]
![image](https://user-images.githubusercontent.com/39413400/91612816-0eda1a80-e933-11ea-954a-2a3bafe936a1.png)

what the fuck

**Comment by ZacDelves** [comment]
ah yes a little nugget of comedy gold when browsing #github-progress. lmfao

**Comment by CalaMariGold** [comment]
we're removing grappling hook mod
