### ISSUE TITLE
[INFORMATION] Got "Snatching" Enchantment

### ISSUE THREAD

**Issue by AdityaKumar5155** [Rebirth-of-the-Night/Rebirth-Of-The-Night#456]
Hi Developer,
I am using v.2,77.5.
I have got an enchantment book while fishing which contains Looting II and Snatching. When I take a close look at the book, there was written "IF YOU ARE SEEING THIS INFORM TO DEV", Is there something wrong with that enchantment?
I'll wait for your reply.

**Comment by democat3457** [comment]
Thanks, the snatching enchantment is supposed to be disabled for a likely game-breaking reason. Try not to use it.
