### ISSUE TITLE
Harvest Moon in the afternoon when thunderstorm started

### ISSUE THREAD

**Issue by AsterixxxGallier** [Rebirth-of-the-Night/Rebirth-Of-The-Night#457]
Time: sun icon exactly at the third strike
Weather: thunderstorm, was clear seconds ago
Chat: `The Harvest Moon is rising...` in blue
Moon event: Harvest Moon, was none seconds ago
Log file: [latest.log](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5176967/latest.log); nothing special though I think

**Comment by democat3457** [comment]
Follow the template, please.

**Comment by AsterixxxGallier** [comment]
I didn't even know one existed

bruh

**Comment by democat3457** [comment]
![image](https://user-images.githubusercontent.com/32407067/92289037-a95ad080-eed4-11ea-935b-300752682617.png)

bruh to you
you didn't see the big green buttons?

**Comment by AsterixxxGallier** [comment]
no, I didn't, I did not even see the screen, I just clicked on "New issue", logged in, and was presented to an empty issue editor. bruh back to you

**Comment by AsterixxxGallier** [comment]
#458 is the official one now
