### ISSUE TITLE
[BUG] Nyx Lunar Events can occur during thunderstorms in the day

### ISSUE THREAD

**Issue by AsterixxxGallier** [Rebirth-of-the-Night/Rebirth-Of-The-Night#458]
**Describe the bug**

A moon event (Harvest Moon) started during the day (more precisely, in the afternoon), directly after a thunderstorm began.

**To Reproduce**
1. Play RotN, always skip nights for efficiency
2. See if this bug happens again
3. Repeat if no
4. Profit?

**Expected behavior**

The day should have just continued normally, I did not expect a moon event.

**Screenshots**

https://cdn.discordapp.com/attachments/620840315502198785/751543110903005315/unknown.png
Time of day ingame:
https://cdn.discordapp.com/attachments/620840315502198785/751543844818124810/unknown.png

**Info (please complete the following information):**
 - Modpack Version: 
2.77.5
 - Server or Singleplayer:
Singleplayer
 - Version the world was created on:
2.77.5
- Log file:
[latest.log](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5176967/latest.log); nothing special though I think

**Additional context**

**Comment by CalaMariGold** [comment]
Possibly due to how Nyx detects if it's night.

**Comment by AsterixxxGallier** [comment]
yes
and in a creative test world I did, for testing purposes, and it happened again afterwards, also exactly when the rain started:
![full moon](https://user-images.githubusercontent.com/48604279/92310429-7d138280-efae-11ea-8fe2-61e590d6dba5.png)

**Comment by democat3457** [comment]
Yea that's why, messing with `/time set` messes up internal clocks like Nyx and invasions.

**Comment by democat3457** [comment]
We can't do anything about that, unfortunately, since Nyx was a commission and any bug-fixing will require more moolah (I think).

**Comment by AsterixxxGallier** [comment]
sorry for the confusion this caused, but in my survival world (from the original issue text) I never changed the time at all (contrary to what I mistakenly stated earlier), only in the creative testing world
in that world it happened a few more times btw, always directly after it started to rain, and monsters started to spawn then too

I think this should be reopened, because it is only more frequent when tampering with time, but not limited to that

**Comment by kil0byt3** [comment]
> We can't do anything about that, unfortunately, since Nyx was a commission and any bug-fixing will require more moolah (I think).

Can’t do anything. Mod dev doesn’t want to fix any bugs. Game considers Thunderstorms “night”

**Comment by CalaMariGold** [comment]
The hell? Can we stop jumping to conclusions?? Even if it does require more money, I'll pay for it. He said he can do it. Chill out.
