### ISSUE TITLE
[BUG] Spiders attacking through 1 block thick walls

### ISSUE THREAD

**Issue by boxfoxbox** [Rebirth-of-the-Night/Rebirth-Of-The-Night#459]
any spiders will attack through 1 block thick walls/ceilings if they are clinging below or above

- To replicate, get a spider and a wall, put a block on the wall to prevent the spider from going on top of it, then stand on that block
- spider will attack you 
- also works if the spider is above you at your height 1 block away

 - Modpack Version: v2.77.5
 - Server or Singleplayer: singleplayer
 - Version the world was created on: v2.77.5

**Comment by kil0byt3** [comment]
duplicate of #204
