### ISSUE TITLE
[BUG] Horse infinite taking damage animation.

### ISSUE THREAD

**Issue by EndangeredPootis** [Rebirth-of-the-Night/Rebirth-Of-The-Night#460]
**Describe the bug**

**To Reproduce**
No idea due to finding it randomly in the wild.

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: LAN Server 
 - Version the world was created on: 1.12.2

**Additional context**

**Comment by democat3457** [comment]
No screenshots? Did it appear to be suffocating or stuck in a block or anything of the source? Did it eventually die?

**Comment by democat3457** [comment]
Gon close this to inactivity
