### ISSUE TITLE
[CRASH] Instant Crash on opening RotN

### ISSUE THREAD

**Issue by LeeDassin** [Rebirth-of-the-Night/Rebirth-Of-The-Night#463]
**Describe the crash**
I opened up MultiMC today and tried to log into RotN and the game open with the loading screen before going straight to a crash saying that something was wrong with Embassy

**To Reproduce**
Opened MultiMC
Clicked to Open RotN

**Crash Log**
https://pastebin.pl/view/5f82a19f

Apologies for not using the link provided in the crash but it failed when I clicked for it to send me the link.

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Either, game will not even open
 - Version the world was created on: 2.77.5
**Additional context**

**Comment by democat3457** [comment]
Solved.
