### ISSUE TITLE
[CRASH] Seems ruins mod corrupted my single player save when power went out

### ISSUE THREAD

**Issue by sentriegun16** [Rebirth-of-the-Night/Rebirth-Of-The-Night#464]
[crash-2020-09-10_15.57.31-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5204985/crash-2020-09-10_15.57.31-server.txt)

**Comment by democat3457** [comment]
If your save corrupted, then we can't do anything about it. Also, it wasn't ruins mod that corrupted it, even though the crash screen might say so, since the stacktrace details an entity entering a chunk to be loaded.
