### ISSUE TITLE
[BUG] Camera gone haywire

### ISSUE THREAD

**Issue by Tomato-No-Mae** [Rebirth-of-the-Night/Rebirth-Of-The-Night#465]
**Describe the bug**
When moving the first-person camera will go absolutely bonkers, and spin out of control everywhere

**To Reproduce**
I am unsure of how this came to be but it happens every time I move

**Expected behavior**
I expected to move normally, like how I used to.

**Screenshots**
   https://giphy.com/gifs/xPId1gjf2Ra55FxBpu
**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

I'm running this on multimc and accidentally clicked the kill button, I also attempted to copy the mod and config files over to a server that I'm running, in the process I moved some of the files around but I think I got everything back in the right places

**Comment by SandwichHorror** [comment]
Please do not take the following comment as offensive. I'm just trying to explain a concept.
>  I also attempted to copy the mod and config files over to a server that I'm running, in the process I moved some of the files around but I think I got everything back in the right places


Here is how I read this. You have just visited a doctor and said:

>  I accidentally drank a little bleach, I also attempted to reorganize my medicine, in the process I mixed up a bunch of my pills and their correct dosages but I think I got everything back in the right places

This is not viable. If you stick with that system, something is going to go terribly wrong. Please reinstall the modpack normally, completely, and try again, and I would strongly advise you to stay away from Davinci's Vessels. That mod is known for corrupting worlds and will be removed in the next update.

**Comment by SandwichHorror** [comment]
Call me in the morning if you experience any more crashes after doing that.

![docs-orders](https://user-images.githubusercontent.com/59847281/93414616-a6b29080-f86f-11ea-9ef8-984eaa0865c5.png)

**Comment by kil0byt3** [comment]
also change your betterfps algorithm, but please reinstall the pack first
