### ISSUE TITLE
Crash permanently broke game. Had to relaunch everything.

### ISSUE THREAD

**Issue by ThreeForths** [Rebirth-of-the-Night/Rebirth-Of-The-Night#469]
I was just running along harmlessly through some caves, and my game freaked out. No clue what caused it.

I hit the ground in a cave and died, my screen freaked out then this happened.

![unknown](https://user-images.githubusercontent.com/56747631/93938012-9fb7d200-fcf6-11ea-8aa6-f9ca19f5a2ab.png)
[crash-2020-09-22_17.07.55-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5264024/crash-2020-09-22_17.07.55-client.txt)

**Comment by ferreusveritas** [comment]
Just fixed this in Dynamic Trees 0.9.15
