### ISSUE TITLE
[BUG] Zombies in Skeleton horde?

### ISSUE THREAD

**Issue by AdityaKumar5155** [Rebirth-of-the-Night/Rebirth-Of-The-Night#471]
**Describe the bug**
In Skeleton raids, Zombies are also able to detect me from 20-30 blocks away like in zombie raid.

**To Reproduce**
Trigger the Skeleton raid

**Expected behavior**
Only Skeletons should able to detect me from a far distance

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by CalaMariGold** [comment]
Intended. Zombies with pickaxes spawn to break down your house so the skeletons can come in.
