### ISSUE TITLE
[CRASH] Not 100% sure on what causes this just kinda out of the blue

### ISSUE THREAD

**Issue by Tomato-No-Mae** [Rebirth-of-the-Night/Rebirth-Of-The-Night#473]
**Describe the crash**
this has happened multiple times now, its not quite upon world join but maybe a few minutes after, I was just standing around and then got sent to the main screen

**To Reproduce**
Just lucky I guess

**Crash Log**
[crash-2020-09-24_17.44.10-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5279783/crash-2020-09-24_17.44.10-client.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.77.5

**Additional context**
I've got nothin

**Comment by Tomato-No-Mae** [comment]
it also doesn't resolve itself by relogging

**Comment by democat3457** [comment]
Apparent fix (resolved in Discord): turning off sounds.
