### ISSUE TITLE
Upside down saw stays on.[BUG]

### ISSUE THREAD

**Issue by ThreeForths** [Rebirth-of-the-Night/Rebirth-Of-The-Night#474]
**Describe the bug**
While running a water mill hooked up to a gearbox hooked up to a gearbox plugged into an upside down sawmill when turned off sometimes makes the sawmill stay on even after being disconnected from the gearbox.

**To Reproduce**
Unsure exactly if reproduceable.  Hook up a sawmill to a watermill via 2 wooden gearboxes with 3 axles each then connect that to an upside down saw mill. Like this.

![image](https://user-images.githubusercontent.com/56747631/94227737-40f68200-fec9-11ea-8526-abf249a4c293.png)

**Expected behavior**
I expected the Saw to turn off when I flipped the lever, and also expected it to shut off when I disconnected the axles.

**Screenshots**
![image](https://user-images.githubusercontent.com/56747631/94227344-3be50300-fec8-11ea-92f3-a57d378214ea.png)

 - Modpack Version: 2.77.5
 - Server or Singleplayer: Single Player Lan World with my wife.

 - Version the world was created on: 2.77.5

**Additional context**
I honestly have no clue why this happened. It completely bamboozled me.

![Hnet-image (3)](https://user-images.githubusercontent.com/56747631/94227894-9763c080-fec9-11ea-936c-c9a48eefbbbb.gif)

**Comment by kil0byt3** [comment]
Could be related to the bug in 2.77's version of BWM with disappearing axles

**Comment by democat3457** [comment]
Seeing as there's no reliable way to reproduce this and could be attributed to desync, this issue will be closed. If it occurs again on a recent version, feel free to reopen it.
