### ISSUE TITLE
[BUG] Cloud staff is working even without you holding it

### ISSUE THREAD

**Issue by Tomato-No-Mae** [Rebirth-of-the-Night/Rebirth-Of-The-Night#475]
**Describe the bug**
The effects of the cloud staff, shooting out two cloud/ice balls, linger after you stop having it in your mainhand

**To Reproduce**
this is just what I did right before it happened
1. Use cloud staff normally, left and right clicking
2. keep it in your mainhand
3. open chest
4. move it to your inventory
5. left/right click with any other hotbar slot, even another item

**Expected behavior**
for there not to be cloud staff projectiles

**Screenshots**
![image](https://user-images.githubusercontent.com/67121000/94331508-2cc68980-ff8a-11ea-9028-25fef8982c42.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

was opened to LAN but no one other than me was connected

**Comment by CalaMariGold** [comment]
iirc aether fixed quite a few things in a recent update, including cloud staff. reopen this issue if it still happens in 3.0
