### ISSUE TITLE
[BUG] axles get broken on relaunching

### ISSUE THREAD

**Issue by AdityaKumar5155** [Rebirth-of-the-Night/Rebirth-Of-The-Night#476]
**Describe the bug**

I have made a windmill setup. i was working fine till 1-2 days But after that whenever I relaunch the game, I found 1-2 wooden axles missing from the windmill tower.
First, I thought maybe any mob is breaking it. So, I covered it with dirt blocks but still got missing.

**To Reproduce**
Make a windmill around 16-17 blocks height and then relaunch game (Not sure)

**Expected behavior**

It should not be missing from windmill setup on relaunching.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

My PC RAM is 4GB. So, maybe is it due to the low memory of my PC?

**Comment by democat3457** [comment]
It's a bug with BWM. No fix other than to try to have 1-block long axles by putting more gearboxes down.

**Comment by democat3457** [comment]
Fixed in beta 6

**Comment by AdityaKumar5155** [comment]
Thanks for update

**Comment by SekretOne** [comment]
Confirmed.

```gherkin
Given a windmill
And axles at 1 block in length
And axles at 2 blocks in length
And axles at 3 blocks in length
When the world is reloaded
Then the axles are "not broken"
```

![2021-05-06_16 18 06](https://user-images.githubusercontent.com/5504626/117360367-b3c7d280-ae86-11eb-916c-571291cbcaf4.png)
