### ISSUE TITLE
[BUG] Grappling hook makes poison/wither damage the player faster (Lan world)

### ISSUE THREAD

**Issue by CreeperMan114** [Rebirth-of-the-Night/Rebirth-Of-The-Night#477]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 
 - Server or Singleplayer:
 - Version the world was created on:

**Additional context**

**Comment by SandwichHorror** [comment]
Please use the issue template. Anyway, this bug is known and the grappling hook will be removed in 3.0

**Comment by CreeperMan114** [comment]
sorry i tried my english are bad XP


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Απαλλαγμένο
από ιούς. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Στις Κυρ, 27 Σεπ 2020 στις 2:47 π.μ., ο/η Sandwich Horror <
notifications@github.com> έγραψε:
