### ISSUE TITLE
[CRASH] MC crashes at about 16%, crash links won't work.

### ISSUE THREAD

**Issue by archspore** [Rebirth-of-the-Night/Rebirth-Of-The-Night#488]
**Describe the crash**
When launching the mod from from as a starting point, it loads to about 16% then freezes and brings me to a crash page. The link on it doesn't actually work, but it did produce a crash log.

**To Reproduce**
Steps to reproduce the behavior: No idea. I had just restarted my PC, but besides that everything was normal.

**Crash Log**
https://pastebin.com/UVG8vXHW

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 1.12.2

**Additional context**
N/A

**Comment by democat3457** [comment]
reinstall appears to have fixed it. closing
