### ISSUE TITLE
Mythril bow deletes items

### ISSUE THREAD

**Issue by DestroyerDuck2** [Rebirth-of-the-Night/Rebirth-Of-The-Night#489]
**Describe the bug**
Mythril bow does infinite damage to targets, then deletes items and drops.

**To Reproduce**

Not sure, as this seems to have been a once off occurrence. Said bow has the Light buff and regular arrows

**Expected behavior**
I expected the bow to only slightly increase in damage. 

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5

**Additional context**
Bow was created after day 185, and I accidentally hit my friend with it.

**Comment by democat3457** [comment]
what the fork

**Comment by kil0byt3** [comment]
my god

**Comment by CalaMariGold** [comment]
What enchantment(s) did it have

**Comment by democat3457** [comment]
closing due to lack of information. probably attributed to the random enchantment bug on mythril bows.
