### ISSUE TITLE
nether wasp[CRASH]

### ISSUE THREAD

**Issue by SpGilbert** [Rebirth-of-the-Night/Rebirth-Of-The-Night#491]
**Describe the crash**
sometimes when you kill a nether wasp your game continues running but mobs cant be attacked and don't move. while blocks can be broken but don't drop. When you leave the world the game crashes and when you relog it is corrupted and you need to delete the nether dimension in order to continue.

also when I managed to relog after serval attempts I was able to get on but several issues emerged
first being my difficulty was set to peaceful which was the last mode I hade it on while using creative trying to find my mount that glitched. the second I was getting a crash log from breaking blocks with a pick of mine. 
**To Reproduce**
enter the nether and when you kill a nether wasp it will sometimes corrupt the game possibly depending on where you are in the world and if something loads not sure.

the second issue just relog a few times and you get on (this only happened my second time with this bug.

also deleting the nether fixes it as well but (for my first attempt.
**Crash Log**

don't have a crash log but I have the latest file no crash report due to the kind of crash)
none of the websites seem to be able to support the latest lof of this size sadly.
 not even paste.gg can support it.
says it to large.

For the second crash from logging in is 
http://hastebin.net/ohefobonal.rb

**Info (please complete the following information):**
 - Modpack Version:  2.77.5
 - Server or Singleplayer: single player
 - Version the world was created on 2.77.5

**Additional context**
 from what I can tell. possibly open JDK (I can't seem to delete it even from the consol controles possibly has to do with the gd launcher) this is all I can gather I am also using 5 extra mods which should not impact it in the slightest (2 dynamic tree addon mods being aether and twilight forest. also using mending fix, torch slab, and smooth scrolling everywhere.)

the time of posting this crash this is my second time encountering it the first time I fixed it by deleting the nether the second I reblogged and have yet to delete the nether. (I don't know what latest log and crash log are for the original crash)

**Comment by democat3457** [comment]
So do you or do you not have the first issue's log?

**Comment by democat3457** [comment]
Also second issue is known, place and break a torch with your fist to prevent the crash.

**Comment by SpGilbert** [comment]
the first encoanters log is probaly burried but the second log I have for the bug its just I cant upload it its apearly to large for the paste websites

**Comment by SpGilbert** [comment]
even github said it cant hollow it (its 86583 lines long XD) how much of the log do you need?

**Comment by democat3457** [comment]
rip, probably only the latter third or fourth depending on when you closed the game

**Comment by SpGilbert** [comment]
https://gist.github.com/SpGilbert/be07dca4c2775a8d9d8c048c17acf806 nevermind 3rd attempt

**Comment by democat3457** [comment]
oh
nice

**Comment by SpGilbert** [comment]
irs 2 hours long

**Comment by SpGilbert** [comment]
thats proably why its over 86k lines

**Comment by democat3457** [comment]
I see no error message, is that the debug.log or the latest.log?

**Comment by SpGilbert** [comment]
latest I can grab the debug.

**Comment by SpGilbert** [comment]
but I think those may be lost since I have created an instace since then

**Comment by democat3457** [comment]
does debug.log not get put into the tar.gz or .zip files?

**Comment by SpGilbert** [comment]
found it but it may be even longer

**Comment by SpGilbert** [comment]
almost 320k lines yikes

**Comment by SpGilbert** [comment]
github crashed

**Comment by SpGilbert** [comment]
https://web.archive.org/web/20180320091844/https://gist.github.com/ this may work not sure

**Comment by democat3457** [comment]
dunno if you're linking that for your reference or as a log, because that just redirects to the default site (on the archive ofc)

**Comment by democat3457** [comment]
you could also probably trim down the first 3/4ths of it

**Comment by SpGilbert** [comment]
it crashed and all I got was that trying again to post the log will try and shorten it to 10000 lines if it does not work this time

**Comment by SpGilbert** [comment]
last second of the debug log 6.5k lines https://gist.github.com/SpGilbert/041eae992e6e0190121780d1ead8d2fe

**Comment by democat3457** [comment]
It appears that the problem is the attachment of BWM breeding harnesses on Animania entities?

**Comment by SpGilbert** [comment]
huh I dont have breeding harnesses

**Comment by kil0byt3** [comment]
Stale; seems to be going nowhere (a fix has been provided for 1/2 issues)
