### ISSUE TITLE
Already Existing Chunk Loading Error

### ISSUE THREAD

**Issue by griffsmith** [Rebirth-of-the-Night/Rebirth-Of-The-Night#499]
**Describe the bug**

Preexisting chunks near my base are suddenly elevating 10 to 20 blocks.
**To Reproduce**
N/A
**Expected behavior**

Not have preexisting chunks suddenly elevate.
**Screenshots**

https://drive.google.com/drive/folders/18x-F6IUPh_fAmVNK3rYIVAuxGWOLFoX9?usp=sharing
**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 1.12.2

**Additional context**

**Comment by CalaMariGold** [comment]
The heck? Could you send latest.log in the logs folder?

**Comment by kil0byt3** [comment]
Need logs, this looks like world corruption

**Comment by kil0byt3** [comment]
Stale
