### ISSUE TITLE
Hamster Vehicle causing crash on loadup

### ISSUE THREAD

**Issue by ajh579** [Rebirth-of-the-Night/Rebirth-Of-The-Night#508]
Im pretty sure I left the game with a hamster on my shoulder, and now when attempting to load the save, it crashes. The report says when rendering a hamster, there is a null pointer error for the entitys vehicle. This is my main survival world and now i cant get into it, which sucks.

[crash-2020-11-12_11.22.17-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5532242/crash-2020-11-12_11.22.17-client.txt)

**Comment by democat3457** [comment]
Remove namepain and get the hamster off ye.

**Comment by democat3457** [comment]
Opened issue https://github.com/capnkirok/animaniamod/issues/468

**Comment by kil0byt3** [comment]
We could remove Name Pain if needed, iirc it's aesthetic only (I forget why I added it)

**Comment by CalaMariGold** [comment]
Namepain was added to disable the floating names from vanilla since we use Neat. Wait shit im supposed to be on break YOU SAW NOTHING

**Comment by kil0byt3** [comment]
Thanks Mari, now get outta here
