### ISSUE TITLE
[CRASH] Unexpected crash due to mods

### ISSUE THREAD

**Issue by AdityaKumar5155** [Rebirth-of-the-Night/Rebirth-Of-The-Night#510]
**Describe the crash**

I usually use MultiMC Launcher to play ROtN but yesterday i try to use TLauncher. So, i installed ROtN(with all additional files) in TLauncher and launch it and found it crashed at 13% and saying it crashed due to "Embassy". So, i tried to launch it in MultiMC and found it crashed at 16% and saying it crashed due to "B.A.S.E" and "Content Tweaker". I have all requirements installed and not getting what happened, it was working well before i installed TLauncher. So, i try to uninstall it and launch the instance in MultiMC but again same error.

**To Reproduce**
Install TLauncher.
Install the ROtN instance by TL mods menu.
Put all the additional files in Instance folder.
Launch the pack.

**Crash Log**
MultiMC crash-report:- https://pastebin.com/isGU59qn

MultiMC latest-log:- https://pastebin.com/ALCXeryM

TLauncher crash-report:- https://pastebin.com/8qJ9Yahx

Tlauncher latest-log:- https://pastebin.com/28aHp9eb

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by democat3457** [comment]
Reinstall the pack. Also, TLauncher is **not** supported because it's a cracked launcher and also causes many issues with player UUID (for example, Arcane Archives).

**Comment by AdityaKumar5155** [comment]
Okay! Thanks for help.
