### ISSUE TITLE
Mythril Bow Duplicating Spartan Weaponry Arrows

### ISSUE THREAD

**Issue by SirenOfDarkness** [Rebirth-of-the-Night/Rebirth-Of-The-Night#514]
Using the mythril bow with infinity and quickdraw 4(unsure if this is a factor) you can shoot arrows from Spartan Weaponry and duplicate them endlessly.

**To Reproduce**
Mythril bow w/ infinity + quickdraw 4 
Shoot arrow at a wall or something
Pick up arrows and do it again 

**Expected behavior**
For the arrow count to stay the same / for the one arrow to stay in my inventory because I have infinity

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5

**Additional context**
It's either a server side issue or the arrows responding negatively with the mod imo

**Comment by CalaMariGold** [comment]
Fixed next patch
