### ISSUE TITLE
Pam's Harvestcraft Hunger Discrepancies [Vegemite] 

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#516]
**Describe the bug**
harvestcraft:vegemiteitem happens to restore 3.5 hunger bars and 5.5 saturation, while the foods it builds into restore much less hunger and saturation. 

**To Reproduce**
1. Check JEI
2. Look at Vegemite hunger stats and compare to what Vegemite can be added to. 

**Screenshots**
![image](https://user-images.githubusercontent.com/50285548/101544567-c0d5a980-395a-11eb-8303-6a06a7dbf078.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer via LAN 
 - Version the world was created on: 2.77.5

**Comment by SenatorSupreme** [comment]
Yeah the food system is quite whack atm. It's getting completely redone in 3.0 so it'll actually make sense.

**Comment by democat3457** [comment]
Yup it's getting fixed in 3.0.
