### ISSUE TITLE
[BUG] Duplicating pet dragons with just a debuff and the dragon horn

### ISSUE THREAD

**Issue by VlinyXTerragon** [Rebirth-of-the-Night/Rebirth-Of-The-Night#517]
Duplicating pet dragons

1. Have plague debuff
2. Go near dragon to give dragon plague
3. Put dragon into dragon horn
4. Unload the chunks which the dragon was in
5. Go back and see if there's a dragon
6. If dragon isn't there then it might be another issue

I expected it to just have the dragon go into the dragon horn and nothing else.

![2020-12-09_20 39 14](https://user-images.githubusercontent.com/30903182/101722311-cddbc100-3a5e-11eb-8eb5-8d220aa4b183.png)

Here's some screenshots to go with it.

 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.775

It's probably the plague debuff messing with the dragon and all that. Dunno what else
also if you need to ask me any other questions i'm always on discord so just dm me any questions you have.
TempoFlow#2493

**Comment by KaleThyself** [comment]
Is this bug replicable? (Have you tried recreating it again?)

**Comment by democat3457** [comment]
Closing due to lack of information, possibly not replicable. If this issue occurs on 3.0, feel free to reopen it.
