### ISSUE TITLE
[BUG]Mythril Bow w/ Diamond Arrows Inventory deletion

### ISSUE THREAD

**Issue by SirenOfDarkness** [Rebirth-of-the-Night/Rebirth-Of-The-Night#519]
Mythril bow(with or without diamond arrows) glitches someone in creative mode with a spam death animation, and on player kill deletes inventory.

**To Reproduce**
Mythril bow w/ diamond arrows
Shoot another player
Inventory deleted

One shot player, but don't delete inventory. 

**Screenshots**
https://imgur.com/a/2UV7LvF

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5 

**Additional context**

**Comment by democat3457** [comment]
Does the Mythril Bow have any enchants? And are the arrows tipped?

**Comment by SirenOfDarkness** [comment]
Oh yeah I meant to include that. It's enchanted the same way as it was in my other post about the bow:
Power V, Quickdraw IV, Infinity, and Unbreaking I. 
The arrows are not tipped, just plain basic diamond arrows

**Comment by democat3457** [comment]
Cannot reproduce reliably. If the bug reoccurs on 3.0, feel free to reopen it.
