### ISSUE TITLE
[BUG] Saving and exiting while carrying a grove sprite permanently crashes the world

### ISSUE THREAD

**Issue by TheNelston** [Rebirth-of-the-Night/Rebirth-Of-The-Night#521]
**Describe the bug**
Holding a grove sprite of any kind with two hands and exiting the world makes it crash repeatedly upon rejoining.

**To Reproduce**
1) Shift right click on a grove sprite with both hands empty
2) Save and exit
3) Attempt to open the world again to find it crashing

**Expected behavior**
Being able to load the save

**Screenshots**
<img width="1440" alt="Screen Shot 2020-12-16 at 3 28 33 PM" src="https://user-images.githubusercontent.com/6257326/102418827-63250b00-3fb3-11eb-8586-123e301986b1.png">

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**
The crash screen says Name Pain, Primitive Mobs, and Carry On are the culprits.

**Comment by CalaMariGold** [comment]
Can someone try to reproduce this on our dev build please

**Comment by democat3457** [comment]
Unable to repro on dev

**Comment by democat3457** [comment]
And anyway, it's fixed in dev.

**Comment by naqaden** [comment]
I'd like to see this crash log in case it's my mod, Name Pain. I have a hunch it is.
