### ISSUE TITLE
[BUG] Putting rotten flesh blocks in a soaking pot of coal tar crashes the world when you hover over the item in inventory

### ISSUE THREAD

**Issue by TheNelston** [Rebirth-of-the-Night/Rebirth-Of-The-Night#522]
**Describe the bug**
Putting rotten flesh blocks in a soaking pot of coal tar crashes the world when you hover over the resultant item in your inventory. 

**To Reproduce**
1) Fill a soaking pot up with coal tar
2) Put in the rotten flesh block and wait the ~5 minutes for crafting
3) Take out the item
4) Hover over the item to see its tooltip in your inventory

**Expected behavior**
Expected to read the tooltip

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**
No idea

**Comment by democat3457** [comment]
Fixed in dev
