### ISSUE TITLE
[BUG] Horse and Wolf despawning immediately

### ISSUE THREAD

**Issue by Sky-Loves-You** [Rebirth-of-the-Night/Rebirth-Of-The-Night#523]
**Describe the bug**
Wolves with the talent doggy dash and horses despawn immediately.

**To Reproduce**
Steps to reproduce the behavior: Get on a horse and ride it far away from spawn. Get off of it and it will despawn. Get wolf with doggy talent doggy dash. Wolf will despawn immediately.

**Expected behavior**
The animals to not despawn immediately.

**Info (please complete the following information):**
 - Modpack Version: v2.77.5
 - Server or Singleplayer: Singeplayer
 - Version the world was created on: v2.77.5

**Comment by CalaMariGold** [comment]
Vanilla bug. Relog
