### ISSUE TITLE
[CRASH] Server crashes when using enchanted hoe with fortune III to harvest crops

### ISSUE THREAD

**Issue by JaxienGit** [Rebirth-of-the-Night/Rebirth-Of-The-Night#525]
**Describe the crash**
Enchanted a diamond hoe with Fortune III, then right clicked to gather some tea leaves, server crashed. 

**To Reproduce**
 Enchant a diamond hoe with Fortune III and right click a fully grown crop 

**Crash Log**
 Sorry, didn't grab the log when it happened.  

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5

**Additional context**
N/A

**Comment by democat3457** [comment]
crash report in `crash-reports` folder

**Comment by JaxienGit** [comment]
[crash-2020-12-27_03.45.59-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5749939/crash-2020-12-27_03.45.59-client.txt)
[crash-2020-12-27_03.46.17-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5749940/crash-2020-12-27_03.46.17-client.txt)

Here's both crashes. Seems I remembered wrong. I was playing on a server, but it was my client that crashed not the server.

**Comment by democat3457** [comment]
Appears to be the DungeonTactics rand error. *Could* be fixed in dev, not sure.

**Comment by CalaMariGold** [comment]
Fixed in 3.0
