### ISSUE TITLE
[BUG] Buggy Blocks in Structure Spawning

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#526]
**Describe the bug**
When exploring the overworld, you may come across a barn house that seems normal at first glance, but has some incorrect block values. 

**To Reproduce**
1. Explore until you find the barn house structure shown in the screenshot below (minus the windmill and chests). 
2. Attempt to mine the top two layers of blocks on the roof with an axe. 
3. HWYLA will show the vanilla wooden slab blocks to be breakable _with a pickaxe_ instead of an axe. 
4. After breaking the wooden slabs at the very top with a pickaxe, they will drop as missing texture vanilla stone slabs. 

**Expected behavior**
It is to be expected that wooden slabs would drop as themselves and not have stone stab values when placed. 

**Screenshots**
[Structure]: 
![2020-12-28_20 56 25](https://user-images.githubusercontent.com/50285548/103260353-29101d80-4952-11eb-8047-a06fd784a504.png)
[Item data in question]:
![2020-12-28_21 19 39](https://user-images.githubusercontent.com/50285548/103260433-73919a00-4952-11eb-98ed-b0c5de5ffd36.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5 

**Additional context**
The only structure tested with this bug has been the one in the screenshot.

**Comment by Foreck1** [comment]
I'll look into it

**Comment by democat3457** [comment]
Fixed by https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/f8d01429c27be635a8886ff435611f169da12179
