### ISSUE TITLE
[BUG] False triggering of the script about the complication of the game when receiving a full set of the same armor

### ISSUE THREAD

**Issue by Chyrrof** [Rebirth-of-the-Night/Rebirth-Of-The-Night#527]
**Describe the bug**

I found a bug. During the horde of zombies, I picked up 3 pairs of chain mail boots and one chain mail helmet as loot. During the battle, I did not have time to think about it, but it was already too late. The achievement "Chivalry is not dead" worked and the script complicates the game along with it. This is the one that is activated by getting a full set of the same armor. A bit strange in my opinion 

**To Reproduce**

**Expected behavior**

**Screenshots**

![TWb9Yr0BPI](https://user-images.githubusercontent.com/76962523/103557707-6b4ad900-4ed5-11eb-8edf-1e65f777ee30.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by CalaMariGold** [comment]
Dunno what the problem is. Either way its changed in 3.0
