### ISSUE TITLE
[BUG] Shift Clicking Stone Cutter Blocks on Server Boots Player  (v2.77.5)

### ISSUE THREAD

**Issue by Gnomey123** [Rebirth-of-the-Night/Rebirth-Of-The-Night#529]
**Describe the bug**
When putting any stone (more than one) into the GUI, selecting the preferred block and shift-crafting it kicks the player

**To Reproduce**
Make RoTN server (v2.77.5), (mine was run on Ubuntu 18.04 Server), then join.
When doing the steps shown in the bug description, it will kick only the player who crafts the item (I had another player on my server and he nor I was additionally booted off)

**Expected behavior**
To give me my stack of stone (without clicking and breaking my finger or the use of a macro)

**Screenshots**
![bad](https://user-images.githubusercontent.com/34148010/103841100-d96fd700-5060-11eb-8052-28e3d10a26fb.gif)

**Info (please complete the following information):**
 - Modpack Version: v2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: v2.77.5

**Additional context**
Here's that crash log txt file:

https://pastebin.com/K2wLeZF4

**Comment by CalaMariGold** [comment]
Already fixed. Please search the closed issues before making a new one.

**Comment by Gnomey123** [comment]
cool cool. sorry about that

**Comment by democat3457** [comment]
(#24) tbf, github recognizes a difference between "stonecutter" and "stone cutter"

**Comment by Gnomey123** [comment]
Yeah, I did a mass search for the term, and didn't find it.
Should have just look myself manually for the past 5 ones :P
