### ISSUE TITLE
Getting blown up by a creeper seems to trigger every creeper-related achievement[BUG]

### ISSUE THREAD

**Issue by SenatorSupreme** [Rebirth-of-the-Night/Rebirth-Of-The-Night#530]
**Describe the bug**

Getting killed by a creeper unocks every single one of the "die to a creeper X times" achievements
**To Reproduce**
Die by a creeper
**Expected behavior**

to trigger the correct achievement
**Screenshots**

![image](https://user-images.githubusercontent.com/73618518/103974404-59687080-5137-11eb-9497-ab3c2ad403a4.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 BETA

**Additional context**

not really context but slightly related, the achievements that get triggered by this don't show up at all beforehand. The tab for it just isn't there.

**Comment by CalaMariGold** [comment]
Yeah i noticed this too, will try to fix it for next beta

**Comment by democat3457** [comment]
Fixed in one of these betas
