### ISSUE TITLE
Dying to any mob makes you drop your entire inventory[BUG]

### ISSUE THREAD

**Issue by SenatorSupreme** [Rebirth-of-the-Night/Rebirth-Of-The-Night#531]
**Describe the bug**

Dying to any mob makes you drop your entire inventory
**To Reproduce**
die to any mob
**Expected behavior**

to keep your hotbar
**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA
 - Server or Singleplayer: SP
 - Version the world was created on: 3.0 BETA

**Additional context**

1. one of the 5 times i tested this i ended up keeping some berries after dying, not sure why.
2. at first i thought this was just a part of the new death punishment system Mari has talked about a few times, but there's nothing in the changelog about it so I'm not sure if its intentional or not.

**Comment by CalaMariGold** [comment]
We changed this. This is intended.
