### ISSUE TITLE
Custom music not working[BUG]

### ISSUE THREAD

**Issue by SenatorSupreme** [Rebirth-of-the-Night/Rebirth-Of-The-Night#532]
**Describe the bug**

The auto-downloaded custom music isnt working at any volume no matter what i try.
**To Reproduce**
just log on
**Expected behavior**

for there to be custom music
**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA
 - Server or Singleplayer: SP
 - Version the world was created on: 3.0 BETA

**Additional context**

Both me and someone else have encountered this so afaik it's not a random crappy install or one time thing.

**Comment by CalaMariGold** [comment]
Restart the game. This happens sometimes. Still waiting on a fix from the dev.

**Comment by democat3457** [comment]
Does this bug happen on 3.0 Beta 4?

**Comment by democat3457** [comment]
Gonna assume this doesn't happen anymore. If it does, feel free to reopen this issue.
