### ISSUE TITLE
[BUG] OpenGL Rendering Errors ingame

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#533]
**Describe the bug**
After cloning the repo of RoTN from Github, I installed the pack manually into MultiMC. When launching the game and beginning to play, I was hit with multiple OpenGL errors while looking at a certain downwards angle in my world while simultaneously being able to see through multiple chunks. **OpenGL Error: 1281 (Invalid value)**

**To Reproduce**
1. Git clone latest 3.0 Beta build of RoTN from Github. 
2. Launch a new world after installing with the seed _6713374663423443545_
3. Notice the errors and ghosting chunks immediately. 

**Expected behavior**
I did not expect OpenGL errors to occur as the last time I encountered them was way back with SevTech: Ages. 

**Screenshots**

![2021-01-08_08 59 41](https://user-images.githubusercontent.com/50285548/104042899-e6d7af00-518f-11eb-978b-ee59dbc9c46e.png)

**Water appearing invisible as well**
![2021-01-08_09 03 48](https://user-images.githubusercontent.com/50285548/104043304-78472100-5190-11eb-8267-a7db9dc2f30e.png)

**Info (please complete the following information):**
 - Modpack Version: Github repository version 3.0 of RoTN (non-Curseforge) 
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: Same as Modpack Version 

**Additional context**
Console appears to be spammed with OpenGL errors at a high rate. 
Latest Logs:
[Latest Log.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5788467/Latest.Log.txt)

Optifine 1.12.2 Version F5 was added manually into the loader mods.

**Comment by democat3457** [comment]
Are VBOs on?

**Comment by KaleThyself** [comment]
Turning VBOs off seems to have fixed the issues.

**Comment by democat3457** [comment]
noice
