### ISSUE TITLE
[BUG] Cannot craft a chest with willow planks.

### ISSUE THREAD

**Issue by cyantifical** [Rebirth-of-the-Night/Rebirth-Of-The-Night#534]
**Describe the bug**
Using willow planks to craft a chest yields no result. 

**To Reproduce**
1. Open crafting table
2. Place willow planks in manually, or through jei's autofill

**Expected behavior**
Either manually or with jei's autofill, I expected a chest to be crafted. If I'm incorrect and this isn't how to craft a chest, I wouldn't expect jei to fill in a recipe that can't be crafted.

**Screenshots**
[Crafting the chest](https://imgur.com/jbnCqbx)

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 Beta

**Additional context**
I checked for ghost items in the middle crafting slot, and although jei sometimes puts in items like dried plant fibre or stone rocks, I couldn't find a solution.

**Comment by Foreck1** [comment]
I'm working on a fix for this
