### ISSUE TITLE
[BUG] Mob skull bug

### ISSUE THREAD

**Issue by Stargen45** [Rebirth-of-the-Night/Rebirth-Of-The-Night#535]
**Describe the bug**
When breaking normal skeleton skulls an item appears that is not a skeleton skull 

**To Reproduce**
Break a skeleton skull and the item should be the same one in the image below.

**Expected behavior**
meant to normally drop a skeleton skull

**Screenshots**

![image](https://user-images.githubusercontent.com/68275796/104055504-d141a400-51e6-11eb-94ce-57f3b7a5b57e.png)

**Info (please complete the following information):**
 - Modpack Version:  3.0 beta
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 beta

**Additional context**

**Comment by CalaMariGold** [comment]
We are aware of this and working on a fix.

**Comment by KaleThyself** [comment]
Resolved?
![image](https://user-images.githubusercontent.com/50285548/176381711-11bdf6ae-1d84-453c-82a5-0867ca299ac1.png)

**Comment by democat3457** [comment]
i guess its fixed then
