### ISSUE TITLE
[BUG] Killing a vindicator and piper seems to be broken with drops and arcane world

### ISSUE THREAD

**Issue by SoulRacer65** [Rebirth-of-the-Night/Rebirth-Of-The-Night#539]
**Describe the bug**
when killing either of the mobs a pop up shows saying something game breaking had happened

**To Reproduce**
Steps to reproduce the behavior: kill either a vindicator or piper

**Expected behavior**
I was expecting to receive their proper loot

**Screenshots**
no screenshot but a link to the crash https://haste.antti.codes//ofibesilik.mccrash

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta
 - Server or Singleplayer: single player
 - Version the world was created on: 3.0 beta

**Additional context**

**Comment by kil0byt3** [comment]
Looks like an issue with Arcane World calling drops when those mobs are killed. Thanks for the report. We'll look into it.

**Comment by kil0byt3** [comment]
https://github.com/Lemonszz/ArcaneWorld/pull/23

**Comment by democat3457** [comment]
Fixed by #760
