### ISSUE TITLE
[BUG] Server Crash Upon Entity Bounding Box & Entity Player Render

### ISSUE THREAD

**Issue by CyborgPotato** [Rebirth-of-the-Night/Rebirth-Of-The-Night#540]
**Describe the bug**
When playing on a server players joining are disconnected due to bounding box error
On LAN disconnected when rendering another player

**To Reproduce**
Start ROTN BETA server/LAN with AquaAcrobatics installed

**Expected behavior**
Player to join gracefully

**Info (please complete the following information):**
 - Modpack Version: ROTN BETA 2.0 [Pulled 17:28 Jan 9th]
 - Server or Singleplayer: Server
 - Version the world was created on: ROTN BETA 2.0 [Pulled 17:28 Jan 9th]

**Additional context**
It appears this is a known issue, I don't know if there are any compat problems with the latest version of Aqua but the latest 1.2 version fixes the bounding box error on client connect see [Here](https://github.com/Fuzss/aquaacrobatics/issues/9)

**Comment by CalaMariGold** [comment]
Do not report LAN crashes or any bugs that occur on a LAN server.

**Comment by CyborgPotato** [comment]
I shouldn't have included that. I was trying to illustrate that the issue occured on both server and LAN. I will leave out the LAN portion. Should I create a new issue or edit this accordingly?

**Comment by CyborgPotato** [comment]
Just tested w/ Pull from Master at 17:28, mods removed from server: wildlyeat, soundreloader & LagGoggles [Yet known how to fix on my own]. LagGoggles removed on Client.

When using AquaAcrobatics version 1.1.3 on client & server I am unable to connect, client is disconnected instantly due to bounding box error on server.

Updating AquaAcrobatics to version 1.2.3 on client and server fixed this issue.

I apologize again for having mentioned LAN in the issue as it is irrelevant

**Comment by CyborgPotato** [comment]
Just tested further, latest pull I was able to create a working server instance where mods removed from master pull for the server were soundreload & wildlyeat.

Fix for this to run was updating AquaAcrobatics to 1.2.3, LagGoggles no longer generated crashes for me either, seemed to be a red herring for me
