### ISSUE TITLE
Player data not saving after relog[BUG]

### ISSUE THREAD

**Issue by SenatorSupreme** [Rebirth-of-the-Night/Rebirth-Of-The-Night#541]
**Describe the bug**

after exiting the world and going back in my player data seems to have reset to what it was ~30 minutes ago, but everything about the world was the same as i left it. 
**To Reproduce**
relog
**Expected behavior**

playerdata should be up to date
**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA
 - Server or Singleplayer: SP
 - Version the world was created on: 3.0 BETA

**Additional context**

**Comment by kil0byt3** [comment]
did you hard exit or did it fully close back to menu with no errors logged?

**Comment by SenatorSupreme** [comment]
Just back to the menu

**Comment by democat3457** [comment]
Does this happen on other worlds?

**Comment by CalaMariGold** [comment]
Please send the latest.log for when this happened.

**Comment by SenatorSupreme** [comment]
> 
> 
> Please send the latest.log for when this happened.

pastebin just freezes whenever i try to put it in lmao, is there certain info/parts you need?

**Comment by SenatorSupreme** [comment]
> 
> 
> Does this happen on other worlds?

i couldnt replicate it in 2 different worlds, i relogged 10ish times of each of them.

**Comment by SenatorSupreme** [comment]
> 
> 
> Please send the latest.log for when this happened.

pastebin just freezes whenever i put the log in, is there a certain part/ certain info you need?

**Comment by democat3457** [comment]
Well if you can't replicate it and no one else has this issue, then it can probably be closed - plus it's on an old BETA version.
