### ISSUE TITLE
[BUG] items in cosmetic armor slots not saved on death

### ISSUE THREAD

**Issue by Geekdude325** [Rebirth-of-the-Night/Rebirth-Of-The-Night#543]
**Describe the bug**

When armor is in a cosmetic slot on death, it drops along with other items instead of staying in the players inventory

**To Reproduce**
1. equip an armor piece in a cosmetic slot
2. die

**Expected behavior**

I expected the cosmetic armor to be saved along with normal armor
**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by CalaMariGold** [comment]
Fixed in 3.0
