### ISSUE TITLE
[BUG] Some Harvestcraft foods not being able to be cooked on a Campfire

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#544]
**Describe the bug**
Pam's Harvestcraft food cooking compatibility with the FutureMC mod's campfire. 

**To Reproduce**
1. Attempt to cook raw squid into calamari (or any other tofu based meats into their cooked counterparts) using a campfire from the futuremc mod. 
2. The campfire will drop nothing when finished cooking and remove the food from existence. 
3. JEI recipes show the lack of an output for those food items. 

**Expected behavior**
I expect the food to cook and finish like vanilla campfires do. 

**Screenshots**
![2021-01-09_21 30 53](https://user-images.githubusercontent.com/50285548/104115241-fc4cf600-52c1-11eb-9ac9-d1a098d8c67f.png)

**Info (please complete the following information):**
 - Modpack Version: RoTN Beta 3.0s5 (cloned from Github) 
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0s5
 
 **Additional context**
 This issue also occurs with the futuremc's smoker.

**Comment by Landsurfer2000** [comment]
futuremc campfire is to be disabled eventually, as pyrotech's pyro campfire will be used in it's place (these are default recipes auto generated by futuremc, and causes issues like the image provided when working with modded raw to cooked varients). futuremc smoker IS planned to be used, but it is unfinished. so to answer your question, this is still WIP, and it is actively being worked on!
