### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ThreeForths** [Rebirth-of-the-Night/Rebirth-Of-The-Night#545]
**Describe the bug**
Unable to craft Oak Wood into Planks in your inventory crafting grid.

**To Reproduce**
Place logs in your crafting grid.

**Expected behavior**
You expect to get 3 pieces of wood from the logs, just like you can when using the crafting table.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 Beta

**Additional context**
I believe someone set the logs a specific crafting recipe on the crafting bench which might have broken it. Create a crafting recipe to turn logs into planks in the inventory

**Comment by democat3457** [comment]
Works as intended, not supposed to be crafted in inventory
