### ISSUE TITLE
[BUG] Saw doesn't chop logs

### ISSUE THREAD

**Issue by cyantifical** [Rebirth-of-the-Night/Rebirth-Of-The-Night#547]
**Describe the bug**
The saw chops other blocks, like planks, but not logs.

**To Reproduce**
1. Setup a saw
2. Test with other blocks to make sure it works
3. Try to chop logs, and nothing will happen

**Expected behavior**
JEI says that it should chop into 5 planks among other things. 

**Screenshots**
[Log infront of running saw](https://imgur.com/JYkfZI6)

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 beta 2

**Additional context**
If this is an intended change, JEI still reflects the old system.

**Comment by Stargen45** [comment]
The log is the wrong way, it must be facing upwards

**Comment by cyantifical** [comment]
gosh i could've sworn i tried that, must've been to tired last night. thank you

**Comment by democat3457** [comment]
(It's also in #faq)
