### ISSUE TITLE
[BUG]Magical trees chapters only have placeholder text in them

### ISSUE THREAD

**Issue by Gibusek** [Rebirth-of-the-Night/Rebirth-Of-The-Night#550]
Describe the bug
Alicio tree and magical tree chapters only have placeholder text under them in the survival handbook

To Reproduce
Go into the survival handbook ,magic category, dunamis in nature, magical trees and click on the alicio tree or magical tree chapters.

Expected behavior
Functionality and the materials you get from the trees

Screenshots
https://user-images.githubusercontent.com/77245136/104133991-f406c080-537e-11eb-8eb4-b938313d20a8.png
https://user-images.githubusercontent.com/77245136/104134014-07b22700-537f-11eb-854e-af00117d1c43.png

Info:
 - Modpack Version: 3.0 BETA 2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 BETA 2

**Comment by CalaMariGold** [comment]
Are you seriously reporting this knowing that the version you're playing is called BETA? Did you read the part in the changelog that said: "THINGS ARE NOT FINISHED"? 

Just, wow.
