### ISSUE TITLE
[BUG] Rocks and trees spawning in midair in swampy biome

### ISSUE THREAD

**Issue by sethpbauman** [Rebirth-of-the-Night/Rebirth-Of-The-Night#551]
**Describe the bug**
Rocks and trees spawning in midair in swampy biome

**To Reproduce**
not sure

**Expected behavior**
rocks to spawn directly on top of blocks, not hovering in midair

**Screenshots**
![image](https://user-images.githubusercontent.com/50850890/104134848-02ce8280-5341-11eb-89e2-2ff37dad0fde.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 3.0 Beta 2

**Additional context**
Seems like an issue with the puddles part of the biome generation conflicting with the rock/tree generation part, but idk.

**Comment by CalaMariGold** [comment]
Is that floating tree dynamic?

**Comment by Foreck1** [comment]
These puddles are probably generating at a later stage than they should, no idea how to fix this from our side.

**Comment by sethpbauman** [comment]
> 
> 
> Is that floating tree dynamic?

yea it is. the large mushrooms and bushes are also spawning in the air in a similar manner. 

it's not a rampant problem, only in a few spots.

**Comment by democat3457** [comment]
Extremely low priority and almost impossible to fix without reworking the world generation.
