### ISSUE TITLE
Breaking crates and replacing them produces infinite sawdust

### ISSUE THREAD

**Issue by Joshbbi** [Rebirth-of-the-Night/Rebirth-Of-The-Night#554]
**Describe the bug**
Breaking crates, placing them, and breaking again causes infinite sawdust to be produced.

**To Reproduce**
Steps to reproduce the behavior: Break a crate, place it, and break it again

**Expected behavior**
For the crate to drop only.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Server
 - Version the world was created on: 3.0 Beta 2

**Additional context**

**Comment by CalaMariGold** [comment]
Where did you find the crate

**Comment by Joshbbi** [comment]
It was in a swamp building, I think it may have been a witch hut.

**Comment by CalaMariGold** [comment]
Fixed in https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/7b5e83068d7db602e36e6a51c1380fccd0e722cb
