### ISSUE TITLE
[BUG] smoker deletes sweet potatoes

### ISSUE THREAD

**Issue by elipol02** [Rebirth-of-the-Night/Rebirth-Of-The-Night#555]
**Describe the bug**
Sweet potatos are deleted inside of a smoker after cooking, with both wood and charcoal

**To Reproduce**
Put charcoal in the bottom and sweet potato in the top
**Expected behavior**
After cooking the sweet potatoes, I expected there to be baked sweet potatoes in the right side of the smoker

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 2
 - Server or Singleplayer: single player 
 - Version the world was created on: 3.0 beta 2

**Additional context**

**Comment by kil0byt3** [comment]
seems to be working in dev, likely fixed in next beta

**Comment by CalaMariGold** [comment]
Also occurs with raw calamari (heh). Can't seem to reproduce with any other food other than calamari and sweet potato.

**Comment by CalaMariGold** [comment]
> mods.futuremc.Smoker.addRecipe(calamari, cookedCalamari);

The CT script for the smoker doesn't work. Will require a PR

**Comment by democat3457** [comment]
But a PR for what? Do *all* of the `Smoker.addRecipe()` lines not work?

**Comment by CalaMariGold** [comment]
Yes there's only 2

**Comment by CalaMariGold** [comment]
fixed in beta 4
