### ISSUE TITLE
[BUG] scroll of new life obstruction

### ISSUE THREAD

**Issue by elipol02** [Rebirth-of-the-Night/Rebirth-Of-The-Night#556]
**Describe the bug**

**To Reproduce**
Use the scroll, fill that area with blocks, and then die

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 2
 - Server or Singleplayer: singleplayer 
 - Version the world was created on: 3.0 beta 2

**Additional context**

**Comment by CalaMariGold** [comment]
Huh? What? Huh?

**Comment by elipol02** [comment]
I think my description didn’t save

**Comment by elipol02** [comment]
Fixed it, I also fixed my other bug report

**Comment by elipol02** [comment]
> Huh? What? Huh?

I messed up the description at first, this is an actual bug

**Comment by CalaMariGold** [comment]
Nothing we can do about this. This is vanilla behavior

**Comment by democat3457** [comment]
Also that is kinda your fault for obstructing your spawnpoint or using the scroll too early...
