### ISSUE TITLE
[BUG] Glass breaking with the smallest touch

### ISSUE THREAD

**Issue by Chrisyknow** [Rebirth-of-the-Night/Rebirth-Of-The-Night#559]
Glass blocks and glass panes break with just the slightest touch. Is glass really supposed to break just because one is looking out the window? Or because a furnace, crafting table or such is placed next to a window?
Seems like a bug...

**Comment by CalaMariGold** [comment]
You're supposed to use our issues template. Either way I'll adjust the values

**Comment by CalaMariGold** [comment]
Adjusted in one of our commits
