### ISSUE TITLE
[BUG] Trolls causes massive flinch/complete loss of control of camera

### ISSUE THREAD

**Issue by Kalminious** [Rebirth-of-the-Night/Rebirth-Of-The-Night#561]
**Describe the bug**

Being struck by a troll will send your camera straight upwards, and turns you in random directions. This causes a complete loss of control of the camera.

**To Reproduce**

Steps to reproduce the behavior: Get hit by a troll.

**Expected behavior**

A knockback, maybe some flinch. 

**Screenshots**

[https://imgur.com/a/jsJI3tF] **(GIF)**

**Info (please complete the following information):**

 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Server and Singleplayer
 - Version the world was created on: 3.0 Beta 2

**Additional context**

Only thing I can add is I've seen someone report something very similar to this in Discord, only it was the wroughtnaut instead of a troll. Perhaps something to do with block displacement..?

**Comment by kil0byt3** [comment]
I've noticed this in other packs as well, always with Optifine - wondering if it's related. Thanks for the report!

**Comment by Power625** [comment]
This also happens when the Ferrous Wroughtnaut hits you.

**Comment by Fate1098** [comment]
Experiencing this issue with the trolls on both singleplayer and on my server. When the troll attacks me, my screen is forced upward and I am unable to move for a few seconds.

Modpack Version: 3.0 Beta 2
Server or Singleplayer: Akliz Server and Singleplayer
Version the world was created on: 3.0 Beta 2

**Comment by CalaMariGold** [comment]
Fixed in https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/dd236dd7a9d6e243e403b008bd5ed854a066bed3
