### ISSUE TITLE
[BUG] placed Wither Skeleton Heads not dropping

### ISSUE THREAD

**Issue by caramelliaa** [Rebirth-of-the-Night/Rebirth-Of-The-Night#565]
**Describe the bug**
When placed Wither Skeleton skulls are broken, they turn into two placeholder MHF player heads (MHF_WSkeleton) instead of the actual item

**To Reproduce**
Place down a wither skeleton skull on the top face of a block (not sideways) then break it

**Expected behavior**
The skull drops itself as the actual item usable for crafting recipes and summoning withers

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Server and Singleplayer
 - Version the world was created on: 3.0 Beta 2

**Comment by democat3457** [comment]
intended
