### ISSUE TITLE
[BUG] infinite flimsy buckets

### ISSUE THREAD

**Issue by cbass177** [Rebirth-of-the-Night/Rebirth-Of-The-Night#566]
**Describe the bug**
Putting a dirt bucket in any crafting interface allows you to make flimsy buckets infinitely

**To Reproduce**:
Place a bucket of dirt in any crafting interface and either shift-click to fill inventory or left flick over and over

**Expected behavior**
 As many flimsy buckets as you want.

**Screenshots**
![2021-01-12_16 59 43](https://user-images.githubusercontent.com/77362692/104379792-fb050e80-54f7-11eb-856f-af799bb49460.png)
![2021-01-12_17 00 05](https://user-images.githubusercontent.com/77362692/104379806-fd676880-54f7-11eb-8852-890f007c4094.png)

**Info (please complete the following information):**
 - Modpack Version:3.0 beta 2
 - Singleplayer
 - Version the world was created on: 3.0 beta 2

**Additional context**

**Comment by CalaMariGold** [comment]
I just removed the recipe altogether. It shouldn't have been giving back the dirt bucket

https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/70234ef20eae7f3f0c18d9bc57ca34e101b6f0a2
