### ISSUE TITLE
[BUG] Wood Chip Dupe

### ISSUE THREAD

**Issue by ThatOne4205** [Rebirth-of-the-Night/Rebirth-Of-The-Night#567]
**Describe the bug**
The "Pile of Wood Chips" item is a byproduct from processing logs in a saw. 4 piles can be processed in a compacting bin to make a "Block of Wood Chips", which, when placed, breaks in 4 stages. Each stage drops 2 piles of wood chips. 4 piles go in, 8 come out. This is a major issue as you can use pit burning to process the blocks into charcoal flakes, creating an infinite supply of fuel for smelting items.

**To Reproduce**
Put 4 piles of wood chips in a compacting bin
Right click with a shovel a few times
Place the block of wood chips
Break it

**Expected behavior**
To either only get 4 piles out of breaking the block or for the block to require 8 piles to make. Either or, as long as there is no longer a discrepancy between the creation cost and yield of breaking.

**Info (please complete the following information):**
 - Modpack Version: 3.0 B2
 - Server or Singleplayer: Single Player
 - Version the world was created on: 3.0 B2

**Comment by Foreck1** [comment]
Good catch, thanks for letting us know

**Comment by democat3457** [comment]
Fixed by https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/22312060831f51675e14f265c2d1d66961c49d0e
