### ISSUE TITLE
[BUG] (Mining level inconsistency) Stone Bricks have different mining levels depending on block form

### ISSUE THREAD

**Issue by cocona20xx** [Rebirth-of-the-Night/Rebirth-Of-The-Night#569]
**Describe the bug**
For some reason, stone bricks made of Underground Biome stone types have differing mining levels depending on the block form; this behavior is also inconsistant across block types.
**To Reproduce**
Check the mining levels of the blocks. Stabs and stairs almost always have the Sturdy mining level, all other forms almost always Crude.
**Expected behavior**
All stone brick block forms of this sort have the same mining level.

**Screenshots**
https://user-images.githubusercontent.com/24525012/104394405-8ee4d380-5514-11eb-8b9d-d5347aff9026.mp4

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA 2
 - Server or Singleplayer: Singleplayer
 
 - Version the world was created on: 3.0 BETA 2

**Additional context**
This is probably due to inconsistencies caused during the mining rework. Similar in scope to #546

**Comment by cocona20xx** [comment]
Also similar to #362; but the issue effects more than just slabs. May be worth it to just merge it with that one.

**Comment by democat3457** [comment]
Can probably just make it a comment on #546
