### ISSUE TITLE
[BUG] Inconsistent mining levels for some types of wood

### ISSUE THREAD

**Issue by Power625** [Rebirth-of-the-Night/Rebirth-Of-The-Night#570]
**Describe the bug**
Some types of wood have a mining level higher than crude.
List of wood:
Ironwood planks (sturdy)
Ironwood fence (sturdy)
Ironwood fence gate (sturdy)
Ironwood stairs (sturdy)
Ironwood slab (sturdy)
Olive wood planks (sturdy)

**To Reproduce**

**Expected behavior**
For them to have a mining level of crude.

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 beta 2

**Comment by democat3457** [comment]
#546 can you open a comment here and close this one
