### ISSUE TITLE
[BUG] Beneath not working on servers

### ISSUE THREAD

**Issue by caramelliaa** [Rebirth-of-the-Night/Rebirth-Of-The-Night#572]
**Describe the bug**
The Beneath is not accessible in multiplayer server

**To Reproduce**
Break down to the beneath on a multiplayer server, remove the first layer of arcane barrier with intended method of magic bomb/arcane focus. The second layer onwards are unbreakable even with pickaxes beyond diamond tier and even creative mode

**Expected behavior**
Beneath barrier breaks opening up the portal

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Server
 - Version the world was created on: 3.0 Beta 2

**Additional context**

**Comment by CalaMariGold** [comment]
Sigh... Apparently I accidentally deleted the entire beneath mod in the server pack. Will be fixed in Beta 3
