### ISSUE TITLE
[BUG] Villager trades disabled/removed after trading once

### ISSUE THREAD

**Issue by SomeoneNew2502** [Rebirth-of-the-Night/Rebirth-Of-The-Night#573]
**Describe the bug**

After trading with a Villager that trades Emeralds --> Bones & letting his trades refresh all trades get disabled/removed & an error message appears at the top right side of the screen.

**To Reproduce**
- Find a Villager that trades Emeralds --> Bones.
- Trade anything with him.
- Exit out of the trading UI to let his trades refresh.
- Try trading with him again.

**Expected behavior**

Expected more trades to appear instead of all of them to disappear.

**Screenshots**

![image](https://user-images.githubusercontent.com/50101688/104452206-53491880-55ab-11eb-8f34-bba48648896f.png)
![image](https://user-images.githubusercontent.com/50101688/104452264-6e1b8d00-55ab-11eb-9fa0-6b799ba57fed.png)

**Info (please complete the following information):**
 - Modpack Version: v2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: v2.77.5

**Additional context**

Crash Report: https://pastebin.com/iT18HgRj

**Comment by CalaMariGold** [comment]
Reopen issue if this still occurs in 3.0 beta 4 or later. its probably fixed
