### ISSUE TITLE
[BUG] There are no mobs during invasion

### ISSUE THREAD

**Issue by OneBakaBoi** [Rebirth-of-the-Night/Rebirth-Of-The-Night#574]
**Describe the bug**
We are playing on a server with my friends, and currently whenever an invasion occurs there will no extra mobs attacking us. There is barely any mobs at all.

**To Reproduce**
Other than having a server, I don't know how to reproduce it. 
**Expected behavior**
Mobs should be swarming us during invasions.

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta v2
 - Server or Singleplayer: Server
 - Version the world was created on: 3.0

**Additional context**
The only thing I have changed is the world spawn, with the /setworldspawn command, so new players wouldn't have to travel too far to find us.
I also set the difficulty with the command /difficulty hard , because the server would reset it with every startup.
My only guess that the worlspawn command could have broken the invasion, but other than that no idea.

**Comment by CalaMariGold** [comment]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/74cc19db37ad20e0768b407faff38b24221e5c62
