### ISSUE TITLE
[BUG] Trolls get stuck in place and cannot be damaged

### ISSUE THREAD

**Issue by DoctorNutmeg** [Rebirth-of-the-Night/Rebirth-Of-The-Night#577]
**Describe the bug**
Trolls seem to be able to get stuck in a falling animation and freeze up, unable to be damaged.

**To Reproduce**
Not entirely sure, the guy just kinda walked off a ledge and got stuck like this.

**Expected behavior**
The troll uh, doesn't do that.

**Screenshots**
![2021-01-13_18 36 32](https://user-images.githubusercontent.com/16837271/104527461-c2863300-55d2-11eb-8e7d-c34214237e90.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA 2
 - Server or Singleplayer: Server
 - Version the world was created on: 3.0 BETA 2

**Additional context**
A quick search in the discord shows that this isn't a new issue: https://discord.com/channels/620840315498004480/620840315502198785/708103415900667944

**Comment by KaleThyself** [comment]
The troll was turned into stone due to being exposed to sunlight. This feature is intended by Ice and Fire devs. (Can close issue)

**Comment by democat3457** [comment]
huh.
