### ISSUE TITLE
[BUG] After hit a nether zombie mob or hit by it cause players kicked out of server

### ISSUE THREAD

**Issue by MAGXENO** [Rebirth-of-the-Night/Rebirth-Of-The-Night#578]
**Describe the bug**
After hit a nether zombie mob or hit by it cause players kicked out of server

**To Reproduce**
After we get the nether portal. It shows the "nether"(fire) mobs will spawn in overworld. In an invasion, the fire zombie will cause player kicked out of server after the hits, also when player try to deal damage on it will be kicked, either.

**Expected behavior**
Expect not be kicked.

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Server 
 - Version the world was created on: 3.0 Beta 2

**Comment by democat3457** [comment]
Send server logs

**Comment by CalaMariGold** [comment]
I've reproduced it. 
![image](https://user-images.githubusercontent.com/57605926/104974457-1c696d00-59c6-11eb-9be2-81389876d964.png)

Nothing appeared in the logs.

**Comment by CalaMariGold** [comment]
[crash-2021-01-18_19.52.25-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5832945/crash-2021-01-18_19.52.25-client.txt)
This appeared after trying to rejoin a few times

**Comment by CalaMariGold** [comment]
https://github.com/zabi94/ExtraAlchemy/issues/90
