### ISSUE TITLE
[BUG] doMobSpawning doesn't work

### ISSUE THREAD

**Issue by TheNelston** [Rebirth-of-the-Night/Rebirth-Of-The-Night#580]
**Describe the bug**
Setting the gamerule doMobSpawning to false does not prevent any mobs from spawning.

**To Reproduce**
1. /gamerule doMobSpawning false
2. Mobs still spawn despite the gamerule being false
3. pain

**Expected behavior**
For mobs (both hostile and passive) to stop spawning

**Info (please complete the following information):**
 - Modpack Versions: 2.77.5, 3.0 Beta 2
 - Server or Singleplayer: Singleplayer & Server
 - Versions the world were created on: 2.77.5, 3.0 Beta 2

**Additional context**
probably incontrol or smt being funky

**Comment by CalaMariGold** [comment]
Nothing we can do about this
