### ISSUE TITLE
[BUG] Can't put anything in the Reforging Station 

### ISSUE THREAD

**Issue by J0shh** [Rebirth-of-the-Night/Rebirth-Of-The-Night#582]
**Describe the bug**
I can put the ore in the second slot but after trying to put tools/armour in the correct first slot it just doesn't go in the slot.

**To Reproduce**
Steps to reproduce the behaviour:
Try to put any tool/armour piece in the reforging station.

**Expected behaviour**
You should be able to put them in the slot to reforge your item.

**Info (please complete the following information):**
Modpack Version: 3.0 Beta2
Server or Singleplayer: Server
Version the world was created on: 3.0 Beta2

**Comment by democat3457** [comment]
Tools and armor don't have qualities

**Comment by Kompreya** [comment]
I'll make a note to document this better somewhere.
But, yes, it's planned that only baubles can be reforged.
