### ISSUE TITLE
[BUG] Bucket Duping using Dirt (BETA 2.0 on Creation and Gamplay, Singleplayer)

### ISSUE THREAD

**Issue by MRS0Taken** [Rebirth-of-the-Night/Rebirth-Of-The-Night#583]
You can use dirt to dupe flimsy buckets by crafting them into a dirt bucket and then creating a regular flimsy bucket from the recipe, unlike the expected result which would be to either have only one bucket outcome from the dirt bucket recipe or to disable making buckets from dirt buckets

![image](https://user-images.githubusercontent.com/77527948/104806982-04d28e80-57e4-11eb-894c-41fcb820c568.png)

**Comment by CalaMariGold** [comment]
already fixed, please search through the issues and also use our template

**Comment by MRS0Taken** [comment]
I see
