### ISSUE TITLE
[BUG] Certain Recipes not working

### ISSUE THREAD

**Issue by Fate1098** [Rebirth-of-the-Night/Rebirth-Of-The-Night#584]
**Describe the bug**
1.) Can't put butterflies into the arcane mortar (used to craft transformation quintessence).
~~2.) Can't craft altar of summoning even though all ingredients are in the mage's workstation.~~

**To Reproduce**
1.) Right click a arcane mortar with a butterfly (in this case, the butterfly was manually acquired in the wild).
~~2.) Put the ingredients for a altar of summoning in the mage's workstation.~~

**Expected behavior**
1.) The arcane mortar accepts the butterfly as a valid ingredient.
~~2.) The mage's workstation crafts the altar of summoning.~~

**Screenshots**
1.)
![image](https://user-images.githubusercontent.com/70050676/104827556-86e2a780-5824-11eb-9737-09f8c28a1b22.png)

2.)
![image](https://user-images.githubusercontent.com/70050676/104827544-6e728d00-5824-11eb-882e-afac97f8c562.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Akliz Server
 - Version the world was created on: 3.0 Beta 2

**Additional context**
2.) Note: Many different types of butterflies were used (gray old butterfly, common white old morpho, etc.). All types used were unaccepted by the arcane mortar.

*Any other bugged recipes that I discover will be posted down below.

**Comment by Fate1098** [comment]
3.) Crafting the rune of transformation does not consume all six of the transformation quintessence (recipe asks for six).

**Comment by democat3457** [comment]
altar of summoning recipe fixed in https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/bdfda658f744246c2215d0c8c801afee35239ade

**Comment by democat3457** [comment]
> 3.) Crafting the rune of transformation does not consume all six of the transformation quintessence (recipe asks for six).

(this is actually how it is for *all* rune recipes 😳)

**Comment by democat3457** [comment]
butterfly recipes: opened issue https://github.com/codetaylor/advancedmortars/issues/48

**Comment by democat3457** [comment]
rune recipes fixed in https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/2d0001074426e249b7e14d313f59b0508f82ccc9

**Comment by Kompreya** [comment]
Butterfly issue fixed https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/af9143529150699944d86dfe9106bf757922a667
