### ISSUE TITLE
[BUG] Goose Item pick up + Being killed by ANY Skyroot weapon = Double items

### ISSUE THREAD

**Issue by iEatShadows** [Rebirth-of-the-Night/Rebirth-Of-The-Night#585]
**Describe the bug**
So when you kill a goose with an item in its beak it will drop that item. However killing a Goose with an item in its beak with ANY Skyroot weapon results in the item being duped. (You get 2 of the same item)
All the Skyroot weapons has a special enchantment/effect that when you kill a mob it will drop **Double the drops**. Regular weapons with looting does not reproduce this Dupe because its looting enchantment is different.
**To Reproduce**
Have/get a Skyroot Weapon first
1. Spawn a Goose or find one in the overworld.
2. Drop any item.
3. Let the Goose pick up item.
4. Kill the Goose with the Skyroot weapon.
5. It will drop 2 of the exact same item from what you dropped earlier.

**Expected behavior**
You get a free item copy

**Video**
https://www.youtube.com/watch?v=-CkIBKU2TaA

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2.
 - Server or Singleplayer: Singleplayer in the video but I am sure it works in servers too.
 - Version the world was created on: 3.0 Beta 2

**Additional context**
This should also work on rebirth of the night version 2.77 or any version with the Goose (better animals plus) and Any skyroot weapon (any skyroot weapon that spartan weaponry adds).

**Comment by CalaMariGold** [comment]
Thanks for this report. We'll have to remove Skyroot weapons honestly since they allow for duping boss drops. We can add it back in the future if the Aether devs decide to give us more config options for the ability.

**Comment by CalaMariGold** [comment]
Does this work with skyroot tools?

**Comment by iEatShadows** [comment]
> Does this work with skyroot tools?

it shouldnt. all skyroot weapons all have the "Double the drops" effect so it should just be the weapons, unless theres a skyroot pickaxe, which I couldn't find.

**Comment by democat3457** [comment]
Fixed in https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/a4d2b02955ea4a1fcfbc4b22a1c8ea1b61137ad4 by removing skyroot weapons
