### ISSUE TITLE
[BUG] Well bugs with flimsy buckets

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#591]
**Describe the bug**
Pam's Harvestcraft's Well block has various bugs when combined with Pyrotech's buckets: 

**Most Likely Intentional**

- `pyrotech:bucket_wood` is unable to interact with the `harvestcraft:well`. 
- `pyrotech:bucket_clay` is unable to interact with the `harvestcraft:well`. 

**Not Intentional**

- `pyrotech:bucket_stone` aka the Flimsy Bucket gives an error when attempting to fill it with water via the Well depending on how many buckets are in the main hand stack. 
> Error: stack cannot be null
- When using 1 Flimsy Bucket, you receive no bucket back after one right click, consuming the bucket into nonexistence and showing an error in chat. 
- When using 2 Flimsy Buckets, you receive 1 Water Flimsy Bucket back after one right click, while the other is consumed into nonexistence and showing an error in chat. 
- When using 3 Flimsy Buckets, you receive 2 Water Flimsy Buckets back after one right click, while the last one stays empty without showing an error in chat. 
- When using 4 Flimsy Buckets, you receive 2 Water Flimsy Buckets back after one right click, while the last two stay empty without showing an error in chat. 

**To Reproduce**
1. Acquire Flimsy Buckets and right click them on your Well from Pam's Harvestcraft that you placed down. 
2. Results are expected as discussed above. 

**Expected behavior**
I expect the well to work like a normal infinite water source with buckets. 

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 Beta 2 

**Additional Context**
The `crafttweaker:quality_bucket` aka `minecraft:bucket` has no issues with the Well as expected.

**Comment by democat3457** [comment]
oops i probably switched some values around in the events.zs script, because thats whats handling the flimsy bucket's behavior on wells

**Comment by KaleThyself** [comment]
_Well, well, well..._

Using a `pyrotech:flimsy_bucket` on the `harvestcraft:well` still results in a second block of water on the face of the well that was interacted with. 

![2022-06-29_00 53 40](https://user-images.githubusercontent.com/50285548/176383147-e6e19f63-6b4a-4c0e-9057-e630a698c337.png)

Additionally, the `pyrotech:bucket_wood`, `pyrotech:bucket_clay`, and `aether_legacy:skyroot_bucket` are unable to fetch water from the Well while the `minecraft:bucket` aka Quality Bucket works perfectly fine.

**Comment by KaleThyself** [comment]
_Well would you look at that;_ well interactions with pyrotech buckets are fixed in 3.2.1b.
