### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Priestofchaos** [Rebirth-of-the-Night/Rebirth-Of-The-Night#593]
**Describe the bug**

Flimsy buckets, can be duplicated, through the dirt bucket crafting grid
**To Reproduce**
Create Bucket of dirt and then put it in a 2*2/3*3 grid, and take the flimsty bucket out of the grid
**Expected behavior**

It is suppoed to take te dirt out of the bucket, but instead creates a new one.
**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: beta 3.0
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 3.0

**Additional context**

I think it might be something about the consumption tags or, buckets durabillity

**Comment by KaleThyself** [comment]
Known issue. (can be closed)
