### ISSUE TITLE
[CRASH]Can't join game

### ISSUE THREAD

**Issue by RainSeaiZinc** [Rebirth-of-the-Night/Rebirth-Of-The-Night#595]
**Describe the crash**
When the game loads to 95%, it shows Completed: AntiqueAtlas CraftTweaker Adapter, the process will be unresponsive and the last line in the log will show [Client thread/ INFO)[toolprogression]: Finished doing stupid things

**To Reproduce**
Install this Modpack and then start the game using the default settings.

**Crash Log**
https://paste.ubuntu.com/p/hP9zwvgjkS/

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA3
 - Server or Singleplayer: Singleplayer

**Comment by democat3457** [comment]
It doesn’t actually crash; turn off vsync, make sure you have optifine, allot more ram, and minimize the game.

**Comment by CalaMariGold** [comment]
Duplicate of #4
