### ISSUE TITLE
[BUG] Block Dispensers and Soul Forged Steel rods void OreVariant ores

### ISSUE THREAD

**Issue by Nyagi** [Rebirth-of-the-Night/Rebirth-Of-The-Night#597]
**Describe the bug**
Block Dispensers and Soul Forged Steel rods void OreVariant ores

**To Reproduce**
Attempt to break an OreVariant ore with either a Block Dispensers or a Soul Forged Steel rod

**Expected behavior**
For the Block dispenser nothing should happen as those are suppose to be nerfed in 3.0 to not break ores

For the SFS rod the appropriate item should drop as if broken with a non fortune tool, of below obsidian level (anything higher should not break either)

**Screenshots**
![2021-01-23_21 03 47](https://user-images.githubusercontent.com/33533469/105619240-84e98d00-5dbe-11eb-837f-cba514c09afe.png)
![2021-01-23_21 03 49](https://user-images.githubusercontent.com/33533469/105619242-85822380-5dbe-11eb-8769-b2f958639716.png)

**Info (please complete the following information):**
 - Modpack Version: Beta 3 of 3.0
 - Server or Singleplayer: Single Player
 - Version the world was created on: Beta 3 of 3.0

**Comment by Foreck1** [comment]
After consulting with OSV's developer, it appears that this issue is on how Quark handles the drops from blocks broken by Rods; in his own words: 
> I'm pretty sure it's just how this mod is getting the drops. I bet it isn't "breaking" the ores, but rather just deleting them and manually adding in the drops.
Sorry @democat3457, can I bother you with this?

**Comment by democat3457** [comment]
ofc :) looking at it now

**Comment by democat3457** [comment]
made a comment in the osv (technically personthecat's) discord
