### ISSUE TITLE
[BUG] Can't convert modded chests into vanilla chests via crafting

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#599]
**Describe the bug**
Even though it's shown in JEI, we're unable to convert modded chests into vanilla ones in the crafting table. 

**To Reproduce**
1. Craft different variations of wood chests. 
2. Attempt to craft those wooden chests into vanilla chests. 

**Expected behavior**
I would expect modded chests to be able to be converted into vanilla ones as shown in JEI. 

**Screenshots**
In this example, I'm using an Oak Wood Varnished Chest. 
![2021-01-23_22 28 33](https://user-images.githubusercontent.com/50285548/105623007-1fe86400-5dcb-11eb-9780-a25dce673cd0.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Server
 - Version the world was created on: 3.0 Beta 3

**Comment by democat3457** [comment]
Is there just no output, or is it conflicting with another recipe?

**Comment by KaleThyself** [comment]
> Is there just no output, or is it conflicting with another recipe?

There is no output shown when inputting the chest.

**Comment by CalaMariGold** [comment]
confirmed, `minecraft:chest` can't be in the output for some reason, it worked when i changed the output to something else. just gonna remove the recipe for now. we'll think of other ways or will try to fix the recipe later

**Comment by CalaMariGold** [comment]
![image](https://user-images.githubusercontent.com/57605926/107867136-18563100-6e46-11eb-8c5c-7a5eb8ccac6c.png)

**Comment by democat3457** [comment]
it appears thats a mod config option https://github.com/CharsetMC/Charset/blob/0ae154b11cb08c4f60d72a0d860b7f981c71ae12/src/main/java/pl/asie/charset/module/storage/chests/CharsetStorageChests.java#L119
