### ISSUE TITLE
eating stews duplicates bowls [BUG]

### ISSUE THREAD

**Issue by DIVIDERE** [Rebirth-of-the-Night/Rebirth-Of-The-Night#600]
**Describe the bug**
when eating mushroom stew made from a cauldron you're given back 2 bowls instead of 1

**To Reproduce**
1: cook mushroom stew using a cauldron
2: eat a bowl of stew

**Expected behavior**
the player should only be given 1 bowl back

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 3
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 3.0 beta 3

**Additional context**
giving yourself mushroom stew using creative then eating it in survival does not cause the problem

**Comment by democat3457** [comment]
Known, awaiting a mod update

**Comment by KaleThyself** [comment]
This is no longer an issue for duplicating bowls, but now, the Inventory Tweaks Auto-refill feature deletes singular bowls if it procs while the player eats single-stack mushroom stews (and only mushroom stew). Perhaps this also has something to do with mushroom stew being able to be stacked as well?

**Comment by Foreck1** [comment]
I cannot replicate this currently. Eating either from a single item stack or from several, separated or not, with empty bowl or not, does not delete or duplicate anything for me.

**Comment by KaleThyself** [comment]
Fixed in version 3.2.1a.
