### ISSUE TITLE
The generation rate of Nether Cities is far too high, and results in extremely strange terrain generation in the Nether[BUG]

### ISSUE THREAD

**Issue by CJGithub310** [Rebirth-of-the-Night/Rebirth-Of-The-Night#603]
**Describe the bug**
The Nether generates way too many Nether Cities, and when this happens the area the structure spawns in replaces many blocks in the terrain of the Nether (if it didn't take away some blocks, the buildings would be filled with Netherrack, of course) but the generation of Nether Cities is extremely high. This means that finding actual solid ground in the Nether is much harder than before, and also means that some buildings are cut off when they meet another generation zone for a different Nether City. 

**To Reproduce**
Just go into the Nether, it will be clear when you look around the lava seas.

**Expected behavior**
Lower the spawn rate of Nether Cities by about 5-10x, but in turn make it so the Ghast Queen has a higher chance of spawning so that it isn't incredibly rare.

**Screenshots**
I would but I use MultiMC and the screenshot system on that is confusing lol

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Singleplayer, though it shouldn't change on servers
 - Version the world was created on: 3.0 Beta 3

**Additional context**

**Comment by TheNelston** [comment]
https://github.com/paulevsGitch/BetterNether/issues/25

**Comment by CalaMariGold** [comment]
nothing we can do about this until a modder takes up my commission for a fork. Literally just have to wait until someone feels like making the fork

**Comment by Nuclearfarts** [comment]
just going to note here for future reference that `CityGridSize` in the config controls the spawn rate of cities (lower = more cities).

**Comment by democat3457** [comment]
oh right we should close this
