### ISSUE TITLE
Gniss Brick Slabs become Red Granite Brick Slabs Upon Breaking[BUG]

### ISSUE THREAD

**Issue by Novasiri** [Rebirth-of-the-Night/Rebirth-Of-The-Night#605]
**Describe the bug**
When broken, Gniss Brick Slabs turn into Red Granite Brick Slabs.

**To Reproduce**
Set down Gniss Brick Slab and break it with a Bronze Pickaxe or higher.

**Expected behavior**
Gniss Brick slab should drop instead of a red granite brick slab.

**Screenshots**
![brick1](https://user-images.githubusercontent.com/78075114/105965518-60004e80-6038-11eb-8222-dee83ea9b372.png)
![brick2](https://user-images.githubusercontent.com/78075114/105965523-61317b80-6038-11eb-839a-431ec8eee0ea.png)
![brick3](https://user-images.githubusercontent.com/78075114/105965525-61ca1200-6038-11eb-92f0-cebac0080300.png)

**Info (please complete the following information):**
 - Modpack Version: RotN 3.0 Beta 3
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: RotN 3.0 Beta 3

**Additional context**
I think it speaks for tiself.

**Comment by democat3457** [comment]
reeeeeeeee look at the pinned issues

duplicate of #362
