### ISSUE TITLE
[BUG] Beneath Biome Generation Issues

### ISSUE THREAD

**Issue by Ikedadel** [Rebirth-of-the-Night/Rebirth-Of-The-Night#606]
**Describe the bug**
A biome labeled as 'The Beneath' generates on the surface. Structures still generate but the biome itself appears to be similar to the plains with vanilla MC stone replacing grass. There are caves but after looking inside there are no ores, only lava. (The only ore that does spawn are wonder geodes.)

**To Reproduce**
Steps to reproduce the behavior: Unknown, this seems to be a biome generation bug so I would have no idea how to recreate it. The nearby biomes were Mountain, Defiled Lands, Mega Spruce Taiga, Jungle and Wetland.

**Expected behavior**
A normal biome generation.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/68084570/106008698-90baa500-6085-11eb-9e88-12f4eb707853.png)
![unknown (1)](https://user-images.githubusercontent.com/68084570/106008945-d0818c80-6085-11eb-952d-ef60002d68bb.png)
![unknown (2)](https://user-images.githubusercontent.com/68084570/106008955-d2e3e680-6085-11eb-8c60-517a88470d9b.png)
![Screenshot_71](https://user-images.githubusercontent.com/68084570/106009557-7503ce80-6086-11eb-9f44-08362f1aa254.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA Ver 3
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 1.12.2

**Additional context**
???

**Comment by Ikedadel** [comment]
An additional screenshot I forgot to add, my apologies.
![unknown (3)](https://user-images.githubusercontent.com/68084570/106015114-25280600-608c-11eb-852f-b78882e5781a.png)

**Comment by democat3457** [comment]
Can you provide the world seed for further testing?

This *might* be related to the stygian biome bug where all the biome ids got shifted by one but will require further testing.

**Comment by Ikedadel** [comment]
The world seed is 5631524763611086278.

**Comment by Foreck1** [comment]
After creating a new world using the provided seed on our dev branch, I couldn't find any instance of this biome on the OW. we need more testing to make sure it hasn't been fixed already by changes made to Biome Tweaker

**Comment by CalaMariGold** [comment]
Did you create your world on beta 2 then update it to beta 3?
