### ISSUE TITLE
[BUG] Cannot make biscuits

### ISSUE THREAD

**Issue by dekuraan** [Rebirth-of-the-Night/Rebirth-Of-The-Night#607]
**Describe the bug**
Can't craft biscuits because they have the same recipe as pasta. 

**To Reproduce**
1. Try to make biscuits
2. Makes pasta instead

**Expected behavior**
The biscuits recipe should make biscuits

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 
 - Server or Singleplayer:
 - Version the world was created on:

**Additional context**

**Comment by Landsurfer2000** [comment]
which beta version are you on? The biscuits are made in the Kettle with dough and butter, while pasta is made in the Chef's Workstation with dough and butter as-well. These should not conflict.

![](https://i.gyazo.com/342cf46bac1867b5c3e2f56b00800040.png)

![](https://i.gyazo.com/7b2526c111c71b0e1295691b55c7971d.png)

maybe you were confused on which machine to use?

**Comment by CalaMariGold** [comment]
@dekuraan

**Comment by dekuraan** [comment]
Sorry I forgot to close this!
I'm not sure but I think JEI autofilled the dough and butter for a biscuit recipe even when it was chef's workstation. Let me check really quick.

**Comment by dekuraan** [comment]
Nope, no JEI issues, I must have just tried to make biscuits in the chef's workstation.
