### ISSUE TITLE
[BUG] Server duplication of crafting tables

### ISSUE THREAD

**Issue by gbottino** [Rebirth-of-the-Night/Rebirth-Of-The-Night#608]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: Craft some crafting tools and a basic worktable, then use the crafting tools to make more crafting tables on the workbench. 
**Expected behavior**

The crafting tools will glitch for a second and will give you the crafting tables, although it won't give you as much as you put in materials; for instance, I used 6 crafting tools and got 2 crafting tables and still had the original 6 tools.

**Info:**
 - Modpack Version: v3.0 BETA 3
 - Server or Singleplayer: Server
 - Version the world was created on: Beta 3

**Comment by TheNelston** [comment]
Doesn't appear replicable in singleplayer, probably a server glitch

**Comment by CalaMariGold** [comment]
I couldn't reproduce this on a server. Doesn't sounds like something we could fix anyway.

**Comment by democat3457** [comment]
yea probably just server-client desync (like if the server was lagging a lot)
