### ISSUE TITLE
[BUG] When chopping a dynamic tree with an axe is enchanted with magnetic the saplings don't drop

### ISSUE THREAD

**Issue by SoulRacer65** [Rebirth-of-the-Night/Rebirth-Of-The-Night#609]
**Describe the bug**
  chopping a dynamic tree with an axe is enchanted with magnetic will cause the saplings to not drop

**To Reproduce**
Steps to reproduce the behavior:  chop a tree with an axe enchanted with magnetic

**Expected behavior**
 i expected acorns to drop when chopping  a tree

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta v3
 - Server or Singleplayer: single player
 - Version the world was created on: 3.o beta 3

**Additional context**

**Comment by democat3457** [comment]
i feel like saplings dont drop even when the axe doesnt have magnetic

**Comment by democat3457** [comment]
but redwood cones still drop from redwood trees with a magnetic axe, so i cant reproduce then

dev singleplayer

**Comment by democat3457** [comment]
I would say this is a mostly minor issue, and not worth looking into then
