### ISSUE TITLE
[BUG] Concrete Powder Conversion Rate bugged insinde a soaking Pot

### ISSUE THREAD

**Issue by VaeVicti** [Rebirth-of-the-Night/Rebirth-Of-The-Night#610]
**Describe the bug**
Conversion Rate of Concrete Powder into Concrete Blocks is not 1 to 1 as intended, but instead 1 to 8.

**To Reproduce**
Place Concrete Powder (of any color) into a soaking Pot

**Expected behavior**
Fixing Conversion Rates back to 1 to 1

**Screenshots**
Screenshots available in Helper RotN Chat. 

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Server
 - Version the world was created on: 3.0 Beta 3

**Comment by VaeVicti** [comment]
Update, Soaking Pot in it’s entirety is bugged with the conversion rate for all applicable items

**Comment by Kompreya** [comment]
Seems to be an intended feature of Pyrotech's Soaking Pot that we misunderstood.

Vis items fixed in dev. #72c720d

**Comment by TheNelston** [comment]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/pull/620 fixed in this
