### ISSUE TITLE
[BUG] Peridot 'Fortune 1' set bonus does not work

### ISSUE THREAD

**Issue by Fate1098** [Rebirth-of-the-Night/Rebirth-Of-The-Night#611]
**Describe the bug**
The peridot set bonus is [Fortune I] but it doesn't seem to work. 

**To Reproduce**
Find coal, diamond, or other ores that fortune works on and mine them while wearing the peridot armor set.

**Expected behavior**
Some of the mined ores drop two items instead of one (just like fortune 1 on a pickaxe).

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Akliz Server and singleplayer
 - Version the world was created on: 3.0 Beta 3

**Additional context**
1.) I have mined dozens of coal ore blocks and haven't gotten two coal from any of them. I also used it on many peridot/diamond/sapphire ore blocks and none of them dropped multiple gems.
2.) I also used a non-enchanted peridot pickaxe when I mined the ores (I also tested it on creative with a non-enchanted diamond pickaxe).

**Comment by TheNelston** [comment]
Changing the peridot armor set bonus to

`FullPeridotArmorBonus, wards:effect_fortune.1, extraalchemy:effect.pacifism.2`

fixes the problem
