### ISSUE TITLE
[BUG] Wood does not drop from trees when peridot set bonus is active

### ISSUE THREAD

**Issue by Fate1098** [Rebirth-of-the-Night/Rebirth-Of-The-Night#612]
**Describe the bug**
Dynamic trees that are cut down when the peridot set bonus is active do not drop any wood or sticks (only the pine cones drop from the trees).

**To Reproduce**
Cut down a tree when wearing a full set of peridot armor (either punch the tree or use an axe--both produce same behavior).

**Expected behavior**
The dynamic tree drops wood and sticks.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Akliz Server and singleplayer
 - Version the world was created on: 3.0 Beta 3

**Additional context**
1.) I cut down both redwood and tenebra trees on my server and in singleplayer creative (tested with an axe and without an axe). Both types did not drop wood or sticks while wearing a full set of peridot.

**Comment by TheNelston** [comment]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/pull/619
