### ISSUE TITLE
[BUG] Backpack copying items after lag spike

### ISSUE THREAD

**Issue by Milokolo18Q** [Rebirth-of-the-Night/Rebirth-Of-The-Night#613]
So my game in nether got a big lag like 1 minute and after game came out of the lag my items from bacpack got copied into my inventory. But my inventory was full so it deleted my enchanted gear and in its place put copied items from backpack. 

Version of game beta beta 3.0 v3 Singleplayer.

**Comment by democat3457** [comment]
Use the template. And send the logs.
