### ISSUE TITLE
[CRASH] Server Crash when generating & just loading the nether

### ISSUE THREAD

**Issue by CookiePowder** [Rebirth-of-the-Night/Rebirth-Of-The-Night#616]
Here are the logs
It also crashed once when returning to the overworld the first time
[crash-2021-01-26_02.44.30-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5898416/crash-2021-01-26_02.44.30-server.txt)
[crash-2021-01-26_02.52.38-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5898417/crash-2021-01-26_02.52.38-server.txt)
[crash-2021-01-28_21.16.42-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5898419/crash-2021-01-28_21.16.42-server.txt)

**Comment by CalaMariGold** [comment]
set max tick time to -1 in the server.properties

it should be -1 by default if you used our server pack
