### ISSUE TITLE
[BUG] Kilo and Kompy's relics have the same title in the relics achievement tab

### ISSUE THREAD

**Issue by SenatorSupreme** [Rebirth-of-the-Night/Rebirth-Of-The-Night#617]
**Describe the bug**

Both Kilo and Kompy's relics have the same name/heading in the achievements tab, "Talk Is Cheep"
**To Reproduce**
look at the relics achievement tab
**Expected behavior**

Them to have separate names
**Screenshots**

![image](https://user-images.githubusercontent.com/73618518/106391866-03dd5780-63b5-11eb-92c0-177a15231b7c.png)
![image](https://user-images.githubusercontent.com/73618518/106391872-0b046580-63b5-11eb-94f0-7616354abe94.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: SP
 - Version the world was created on: 3.0 Beta 3

**Additional context**

**Comment by democat3457** [comment]
https://canary.discord.com/channels/620840315498004480/664351929505415168/702965147261468793
kek

**Comment by SenatorSupreme** [comment]
> no, it's been fixed for a while on our side

_Hmmmm...._

**Comment by CalaMariGold** [comment]
@Kompreya pls fix

**Comment by CalaMariGold** [comment]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/d80228221d4cf656ce9dbd407d543c7450849161
