### ISSUE TITLE
[BUG] Blast Furnace does not use ore dict for cobblestone

### ISSUE THREAD

**Issue by Dappermang** [Rebirth-of-the-Night/Rebirth-Of-The-Night#618]
**Describe the bug**

Crafting a Blast Furnace from FutureMC can only be done with vanilla cobblestone.

**To Reproduce**

Attempt to craft a FutureMC Blast Furnace

**Expected behavior**

Blast Furnace can be crafted.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version:  2.77.5
 - Server or Singleplayer: Singleplayer and Multiplayer
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by democat3457** [comment]
but... blast furnaces are made with smooth stone, not cobblestone

**Comment by CalaMariGold** [comment]
![image](https://user-images.githubusercontent.com/57605926/106678556-fe386b00-6588-11eb-9eb2-04584c34ea05.png)
you cant make smoothstone with UGB stone

**Comment by CalaMariGold** [comment]
wtf, there's smooth sandstone for all the UGB stuff but not smooth stone?

**Comment by CalaMariGold** [comment]
@democat3457 can you add the furnace recipe, i couldnt get it to work
