### ISSUE TITLE
[BUG] Offhand weapons not working as intended

### ISSUE THREAD

**Issue by Dumbino** [Rebirth-of-the-Night/Rebirth-Of-The-Night#62]
**Describe the bug**
Main hand weapon gets used whenever you hit the key for your offhand, even though the animation swings your offhand. This also means it uses the damage and durability of your main hand regardless of whether you left or right click (tested on a training dummy, but I noticed weird behavior even against mobs which is what led me to testing it more thoroughly).

**To Reproduce**
Steps to reproduce the behavior: Equip any main and offhand WEAPONS (dragonsteel halberd in main and a sharp stick in offhand for extra laughs). Try swinging one and then the other. Either way it'll use the halberd instead (even though weaving the offhand usage in seems to let you attack faster with your main).

**Expected behavior**
For the offhand to get used at 75% of its normal damage and its durability to get used correctly, as with the previous version(s).

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: Latest (2.75.3)
 - Server or Singleplayer: Server
 - Version the world was created on: 2.74

**Additional context**
None.

**Comment by CalaMariGold** [comment]
Issue is from the mod Better Rebirth. We can try making a GitHub issue on their page.

**Comment by kil0byt3** [comment]
Likely due to this, waiting https://github.com/SanAndreasP/BetterCombatRebirth/issues/21

**Comment by democat3457** [comment]
fixed with burgy's fork

**Comment by kil0byt3** [comment]
Every time a 2 year old bug gets closed, I regain some of my lost happiness

**Comment by democat3457** [comment]
i remember the good ol days where we had 4 pages or less of issues
