### ISSUE TITLE
[BUG] Mobs/Animals stuck leaping really high when in water

### ISSUE THREAD

**Issue by CookiePowder** [Rebirth-of-the-Night/Rebirth-Of-The-Night#623]
**Describe the bug**
I've seen several times with player zombies, chameleons, and wolves, when they're swimming in water, sometimes they get stuck in a loop of leaping up really high into the air then falling back to the same spot.

**To Reproduce**
Lure an animal/player zombie into water. 
I'm not certain on what specificially causes it, but i suspect it might be when there's messed up flowing water.

**Expected behavior**
The animal/mob should get stuck in place, leaping really high out of the water, then falling back over and over again.

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Akliz Server
 - Version the world was created on: 3.0 Beta 3

**Additional context**
The world was initially single-player, played on LAN, then we got the Akliz server. But for the first evening of palying we did have to put the world back to Beta 2 as Akliz didn't have Beta 3 yet, then since the first evening we've been back on Beta 3

**Comment by blhutchings** [comment]
I will just add an mp4 for le example as I am also having this issue. This is on my own locally hosted server.
https://user-images.githubusercontent.com/35791930/106950964-88a5d980-6705-11eb-8701-0cd5ffbd343e.mp4

**Comment by CalaMariGold** [comment]
@Foreck1 @democat3457 what is causing this

**Comment by democat3457** [comment]
i believe someone said it was a problem with rotm affecting the y direction for swim speed in addition to the x and y velocities, but i'm not sure it'd cause such a huge velocity boost

**Comment by KaleThyself** [comment]
I'd like to add on that mobs can hyper boost up to 255+ max world height in some flowing water areas in less than a second.

**Comment by democat3457** [comment]
while you're here @KaleThyself the links that you have in your issues shouldn't have the`(url)` part attached to them
for example, your issue https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/631 has a crash report linked but the link is actually just https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/url because the link is actually
`[https://haste.antti.codes/ibevetopal.mccrash](url)` which just leads to a relative link to `url`

**Comment by democat3457** [comment]
Possible fix: https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/19aeda1165e767ddec4e9a5d4a21eaf3d2dc3a01

**Comment by KaleThyself** [comment]
No longer an issue in v.3.1.1a.
