### ISSUE TITLE
[BUG] Trapdoors falling out of place

### ISSUE THREAD

**Issue by CookiePowder** [Rebirth-of-the-Night/Rebirth-Of-The-Night#624]
**Describe the bug**
Trapdoors (at least wooden ones, i've yet to use others) that don't have a block beneath them seem to sometimes gain "gravity" like sand/gravel does, and they fall from where they were initially placed.

**To Reproduce**
Place a (wooden) trapdoor on the side of a block like normal, but with no blocks/ladders underneath it. Maybe try activate the automatic opening it does when you walk over it/bump off it, that might be what trigger this.

**Expected behavior**
The trapdoor should fall as though it's got gravity, similar to sand/gravel. It may also break depending on what it lands on.

**Info:**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Akliz Server
 - Version the world was created on: 3.0 Beta 3

**Comment by CalaMariGold** [comment]
couldnt reproduce this on dev
