### ISSUE TITLE
[BUG] Trapdoor/Door open/close state bug

### ISSUE THREAD

**Issue by M3RGeo** [Rebirth-of-the-Night/Rebirth-Of-The-Night#625]
**Describe the bug**
Whenever a skeleton shoots an arrow at trapdoors or doors, they're stuck in that state, meaning when a player tries to open/close it, it does but immediately returns to former state

**To Reproduce**
Have a skeleton shoot at a trapdoor or door and try to open/close it.

**Expected behavior**
trapdoor/door to open/close dependant on state, and not immediately return to former state

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: Rebirth Of The Night - 3.0 Beta 3
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 3.0 Beta 3

**Additional context**

**Comment by M3RGeo** [comment]
I went and checked my latest log, as before I quitted the game I was attacked by the skeletons, and both my door and trapdoors were hit, for each arrow, I got an error line of.
[Server thread/INFO] [STDOUT]: [com.p1ut0nium.roughmobsrevamped.RoughApplier:onTarget:322]: invalidAttacker = net.minecraft.entity.Entity; blocked target

**Comment by CalaMariGold** [comment]
Just pick up the arrow and it should fix.
