### ISSUE TITLE
[CRASH] Server Crash when Generating/loading Nether

### ISSUE THREAD

**Issue by CookiePowder** [Rebirth-of-the-Night/Rebirth-Of-The-Night#626]
**Describe the crash**
The server crashed when generating the Nether for the first time, when returning back from it the first time, and also when just loading into it the time after that.
After talking to a staff member at Akliz, I think they told me it was due to (or probably due to) the BetterNether mod, and some issue with the world seed.

**To Reproduce**
Travel to the nether for the first time on a server. Also then travel back and forth a few times after that.

**Crash Log**
[crash-2021-01-26_02.44.30-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5912215/crash-2021-01-26_02.44.30-server.txt)

[crash-2021-01-26_02.52.38-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5912216/crash-2021-01-26_02.52.38-server.txt)

[crash-2021-01-28_21.16.42-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5912218/crash-2021-01-28_21.16.42-server.txt)

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Akliz Server
 - Version the world was created on: 3.0 Beta 3

**Additional context**
The world was initially single-player, hosted on LAN (this is all way before we went to the nether), but when we moved it onto the Akliz server, for the first evening we needed to go beta to Beta 2 since Akliz didn't have 3 yet.
But when we went to the nether, we had been back on Beta 3 for about a week.

**Comment by CalaMariGold** [comment]
It shouldn't crash anymore next update, but the insane lag will always be there unless a modder decides to fork better nether or we figure out a different implementation for nether cities
