### ISSUE TITLE
[BUG] Unfired Pot missing turntable recipe

### ISSUE THREAD

**Issue by TheNuclei** [Rebirth-of-the-Night/Rebirth-Of-The-Night#629]
**Describe the bug**
The unfired pot cannot be turned into an unfired vase on the turntable.

**To Reproduce**
Place a clay block onto a powered turntable from better with mods.
Block will turn into an unfired planter, then an unfired pot. The crafting will halt there due to the missing recipe.

**Expected behavior**
The pot should be turned into a vase after a moment which can then turn into an urn.

**Screenshots**
[gyazo screenshot](https://i.gyazo.com/19dbaa3bdaf36c95bee74497201022b8.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta v3
 - Server or Singleplayer: Server (HydroX)
 - Version the world was created on: 3.0 Beta v3

**Comment by TheNelston** [comment]
Fixed via https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/pull/630

**Comment by democat3457** [comment]
(just put "fixes #629" in the description when you open the pull request)
