### ISSUE TITLE
[CRASH] Using any bucket of water from pyrotech to activate an Aether Portal crashes the game

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#631]
**Describe the crash**
Attempting to use any pyrotech bucket which has a durability bar in order to activate an Aether Portal crashes the game immediately upon placing the water. 

**To Reproduce**
1. Create an Aether Portal frame. 
2. Use a flimsy, wooden, or clay, bucket of water to activate the portal. 
3. The buckets are consumed on a server and crashes your game while in singleplayer, the water nor the bucket are consumed but still crash the game. 
4. Relaunch the world and the portal is lit with either outcome from step 3. 

**Crash Log**
https://haste.antti.codes/ibevetopal.mccrash

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Tested on both Server and Singleplayer
 - Version the world was created on: 3.0 Beta 3

**Additional context**
Quality Buckets seem to have no issue, but wooden buckets also have the same crashing issue.

**Comment by democat3457** [comment]
seems like right clicking is trying to equip the item, but throws an error when trying to play the sound
whats weird is that buckets arent equippable

**Comment by TheNelston** [comment]
Confirmed, happened to me on livestream

**Comment by CalaMariGold** [comment]
@democat3457 Issue on aether's end? Should forward this to their GH?

**Comment by democat3457** [comment]
I'm not entirely sure. I suppose it could be put on both repos, just in case?

**Comment by kil0byt3** [comment]
fixed in #631 via randomportals implementation - all water buckets can now be used to open aether portals
