### ISSUE TITLE
[CRASH] Smelting enchantment causes crashes when harvesting crops

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#633]
**Describe the crash**
When using any pickaxe with the smelting enchantment, an unknown item with a missing texture is dropped alongside the raw crops. When picking up that item, the game/server crashes. 

**To Reproduce**
1. Set up a small farm of any crop. 
2. Enchant a pickaxe with smelting. 
3. Bone meal the crops so they become mature.
4. Right click harvest the crops with the smelting pickaxe from far away. 
5. Missing texture entity spawns and crashes the game when picked up. 

**Crash Log**
Abridged Log: https://pastebin.com/SQL08zWh
Full Log: [crash-2021-02-05_14.32.17-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/5935688/crash-2021-02-05_14.32.17-server.txt)
**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Tested on both
 - Version the world was created on: 3.0 Beta 3

**Additional context**
Also drops exp as if smelting the crop. Crops are also dropped normally besides the missing texture entity.

**Comment by CalaMariGold** [comment]
dungeon tactics isnt being worked on anymore and is closed source
![image](https://user-images.githubusercontent.com/57605926/107433602-8d003700-6af7-11eb-8ff0-51b45156af93.png)

**Comment by democat3457** [comment]
The item that was dropped appears to be **not** null but is rather not found in the registry. Maybe it's an item that wasn't registered properly? Does this happen with any crop? What crops were tested?

**Comment by KaleThyself** [comment]
> 
> 
> The item that was dropped appears to be **not** null but is rather not found in the registry. Maybe it's an item that wasn't registered properly? ~Does this happen with any crop?~ What crops were tested?

I've tested all crops that are cook-able in the default Pam's Harvestcraft config. I'm led to believe that the Smelting enchantment is acting like a furnace that smelts anything interacted with on the pickaxe including right click harvests and breaking blocks. I know for a fact that the Pam's Harvestcraft version we're on in Beta 3 has nearly every type of cooked vegetable items, but I suppose most are disabled?

**Comment by KaleThyself** [comment]
I'd like to add on that if right clicking to harvest vanilla carrot crops with the smelting enchantment, it perma crashes/corrupts your chunk. Currently investigating to find a solution.

**Comment by KaleThyself** [comment]
No longer relevant as smelting has been removed.
