### ISSUE TITLE
[BUG] Glaretorches placeable in the air

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#635]
**Describe the bug**
Ultimate Glaretorches are somehow able to be placed onto each other and float in the air once placed in succession. 

**To Reproduce**
1. Place an ultimate glaretorch onto a wall or the floor. 
2. Attempt to place more glaretorches in rapid succession on different sides of the glaretorch. 
3. Keep placing them on different sides going outwards as shown in the screenshot. 

**Expected behavior**
I expect glaretorches to not be able to be stacked in mid air. 

**Screenshots**

![image](https://user-images.githubusercontent.com/50285548/107139167-061c4600-68ce-11eb-86f2-942cb7f74318.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 Beta 3

**Comment by CalaMariGold** [comment]
Mod hasn't been updated since 2017 and doesn't have a GitHub page or any source code.

**Comment by democat3457** [comment]
but... its on a gplv3 and could be reuploaded

**Comment by CalaMariGold** [comment]
oh, well then i guess we could fork it. weird they dont have the source code public tho
