### ISSUE TITLE
[BUG] I am unable to join my server

### ISSUE THREAD

**Issue by SoggeySandwhich** [Rebirth-of-the-Night/Rebirth-Of-The-Night#636]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: log on to any server...

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: v.3.0 BETA
 - Server or Singleplayer: server
 - Version the world was created on: 1.12.2

**Additional context**
 could have to do with my client, or something missing in the mods, but if that were the case it would pull up a missing mods thing and I just don't know at this point.  Would love to see a solution tho!

**Comment by democat3457** [comment]
at least send screenshots or an error message - we don't even know what BETA version you're on or what it's erroring with

**Comment by democat3457** [comment]
closing due to age and lack of info
