### ISSUE TITLE
[BUG] Arcane Barrier Breaching Issues

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#638]
**Describe the bug**
The volatile core needed for the Magic Bomb is unobtainable since Quazar doesn't exist as an entity on the server pack. Furthermore, the Arcane Focus is not able to remove the first layer of the barrier. When attempting to break the barrier in creative with the Arcane Focus, it didn't interact with the first layer at all. 

**To Reproduce**
1. Craft the Arcane Focus
2. Use either at the first layer of the arcane barrier

**Expected behavior**
I expect the Arcane Focus to suck the barrier blocks into itself in order to get past the first layer of the barrier. 

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Server and Singleplayer
 - Version the world was created on: 3.0 Beta 3

**Additional context**
 - The "Barrier trembles" text shows up, but the barrier can't be interacted with after using the Arcane Focus. 
 - When crafted with the ritual, the Arcane Focus is given to the player with 0/16 durability. 
![image](https://user-images.githubusercontent.com/50285548/107732589-96cb9b00-6cad-11eb-9a2c-d88aeb3750fc.png)

**Comment by democat3457** [comment]
im pretty sure the focus is supposed to increase in durability as you suck up barriers

**Comment by KaleThyself** [comment]
> im pretty sure the focus is supposed to increase in durability as you suck up barriers

It does not interact with the barrier at all besides giving the progression text. Also, it only seems to work if it has durability added to it. (e.g. mending, cheat via JEI)
