### ISSUE TITLE
[CRASH] Twilight Forest batching chunks crash

### ISSUE THREAD

**Issue by sickb0unz** [Rebirth-of-the-Night/Rebirth-Of-The-Night#643]
**Describe the crash**
When entering the twilight portal, after a few seconds the world crash.

**To Reproduce**
Enter the twilight portal.

**Crash Log**
https://haste.antti.codes/giyejixige.mccrash

**Info (please complete the following information):**
 - Modpack Version: RotN 3.0 BETA 3
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: RotN 3.0 BETA 3

**Additional context**
Tryied in different worlds but the result is the same.

**Comment by CalaMariGold** [comment]
I've encountered this a few times when flying in the twilight forest but it was pretty rare. Can you rejoin your world without issue? Not sure what's causing it.

**Comment by sickb0unz** [comment]
@CalaMariGold  No, the world crash endlessly

**Comment by jferrares1** [comment]
https://haste.antti.codes/kerifeguya.mccrash Same happened to me as well

**Comment by democat3457** [comment]
Does this happen in 3.1.1?

**Comment by KaleThyself** [comment]
> Does this happen in 3.1.1?

Surprisingly enough, running through the TF in singleplayer at max speed does not cause any crashes or TPS drops.

**Comment by democat3457** [comment]
That's very good, (to anyone) feel free to comment/reopen this issue if you get this crash again on a recent version.
