### ISSUE TITLE
[BUG] the harvester cannot be spawned after dying to him

### ISSUE THREAD

**Issue by DIVIDERE** [Rebirth-of-the-Night/Rebirth-Of-The-Night#644]
**Describe the bug**
if the harvester kills you and you try spawning him again, he'll vanish within the first few seconds of battle

**To Reproduce**
1: build the harvester structure and spawn him
2: let the harvester kill you (or his fire from the lightning), he'll despawn
3: try spawning him again using the structure, he'll strike you with lightning and vanish. the boss bar goes away too.

**Expected behavior**
the harvester shouldn't vanish/despawn

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 3
 - Server or Singleplayer: single
 - Version the world was created on: 3.0 beta 3

**Additional context**
first happened in survival on a normal world. I tested it again on a superflat creative world to make sure he wasn't going into a cave or something, same results. leaving the worlds and rejoining didn't fix.

**Comment by TheNelston** [comment]
Let me guess, you spawned him during the day?

https://youtu.be/i5BQJlR2THM hope this helps.

**Comment by DIVIDERE** [comment]
> Let me guess, you spawned him during the day?
> 
> https://youtu.be/i5BQJlR2THM hope this helps.

*facepalm* thank you
