### ISSUE TITLE
Unable to craft saw blade or enchantment table[BUG]

### ISSUE THREAD

**Issue by verocrisul** [Rebirth-of-the-Night/Rebirth-Of-The-Night#648]
**Describe the bug**

**To Reproduce**
1: gather items
2: place them in crafting table
3: attempt to craft them

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: beta 3
 - Server or Singleplayer: singleplayer
 - Version the world was created on: beta 3

**Additional context**

**Comment by democat3457** [comment]
Fixed via #428
