### ISSUE TITLE
[BUG] Mounts and sirens go super fast in the water

### ISSUE THREAD

**Issue by iEatShadows** [Rebirth-of-the-Night/Rebirth-Of-The-Night#649]
**Describe the bug**
While mounted on a horse/hippocampus or when a siren attempts to swim in water, all of them go super fast.

**To Reproduce**
1. Join a server
2. Tame a horse/hippocampus
3. ride the mount in water
4. experience the g force

**Expected behavior**

I expect mounts and mobs to not go extremely fast in water.

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 3
 - Server or Singleplayer: server
 - Version the world was created on: 3.0 beta 3

**Additional context**
I assume that issue #623 is similar to this one. Also, Piranhas also go super fast too.

**Comment by democat3457** [comment]
Possible fix: https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/19aeda1165e767ddec4e9a5d4a21eaf3d2dc3a01

**Comment by KaleThyself** [comment]
This is no longer an issue in v.3.1.1a, so it may be closed.
