### ISSUE TITLE
Melting Crucibles Capped at 1000 Kelvin

### ISSUE THREAD

**Issue by Chad-Medic-Man** [Rebirth-of-the-Night/Rebirth-Of-The-Night#650]
Melting Crucible Heat is capped ≤ 1000 Kelvin

Use blocks Burner Heater, Melting Crucible (Advanced or Standard), Fuel Source (Non-Specific, Coal, Log Pile, Nether Coal, or blocks of previous mentioned fuel) Burner placed on bottom and Melting Crucible on top, enter Iron ore, gold ore, or most metal ores or blocks (Tin will not suffice as its melting point is too low) put in fuel, wait for the temperature to rise

The temperature will rise but slow to 999 Kelvin (Advanced) or 1000 Kelvin (Standard) and stay there regardless of dimension or refractory space.

**Screenshots**
https://cdn.discordapp.com/attachments/619698097357979648/812042856155447347/unknown.png
https://cdn.discordapp.com/attachments/619698097357979648/812044870637846618/unknown.png

 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Single Player
 - Version the world was created on: Creative

**Additional context**
I think it's just capped too low in an attempted to stop a value overflow

**Comment by democat3457** [comment]
known, will be fixed in beta 4
