### ISSUE TITLE
[BUG] Teal Glowshrooms removing the Arcane Barrier

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#651]
**Describe the bug**

Magical! It appears that when you use bone meal to grow Teal Glowshrooms (mod_lavacow:glowshroom), it creates a shallow grave underneath the block the Teal Glowshroom was put on. This replaces any block including unbreakable ones with podzol dirt and a Tombstone (also from the undead rising mod). 

**To Reproduce**
1. Go to the Arcane Barrier that separates the Beneath and the Overworld. 
2. Place down a Teal Glowshroom. 
3. Use bone meal on it. 
4. Break the podzol. 
5. Mine into the Beneath with a stone pickaxe. 

**Expected behavior**
I expect this feature to not exist because it is game breaking. 

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Server 
 - Version the world was created on: 3.0 Beta 3

**Additional context**

**Comment by TheNelston** [comment]
what the fuck

**Comment by iEatShadows** [comment]
heh

**Comment by iEatShadows** [comment]
and if you do it twice you can bypass the beneath portal frame thingy and fall out the world.

**Comment by Kompreya** [comment]
lmao this is wild. Thanks for finding it.

**Comment by Kompreya** [comment]
Update Fish's to latest version and this should be fixed

**Comment by Kompreya** [comment]
Fish's has been updated
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/485177a359d632a76b18ede0e8b8b2e323d9ba8f
