### ISSUE TITLE
[CRASH]when i try to start the game it crashes

### ISSUE THREAD

**Issue by Quint2008** [Rebirth-of-the-Night/Rebirth-Of-The-Night#656]
**Describe the crash**
 keeps crashing when i start minecraft

**To Reproduce**
Steps to reproduce the behavior: idk what that means 

**Crash Log**

it sais no fucking log

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer:cant load up the game 
 - Version the world was created on: cant not load the game

**Additional context**

**Comment by SenatorSupreme** [comment]
we need logs from the log folder, this doesnt tell us anything

**Comment by democat3457** [comment]
and also this should say how far into loading it got, if it even booted up - basically, more info = better report
