### ISSUE TITLE
[CRASH] Placing certain "Better Nether" plants in die Cincinnacite pot makes the game crash

### ISSUE THREAD

**Issue by MythicBeast7** [Rebirth-of-the-Night/Rebirth-Of-The-Night#657]
**Describe the crash**
Since the plant doesn't actually place, I can load the world fine and continue playing, as long as I don't try to place the plants that are causing the crash.

**To Reproduce**
In the overworld, place a Cincinnacite pot and then select plants from the "Better Nether" mod to be placed in the pot. Unsure which plants specifically, but I'm sure about white fungus and purple mushrooms. The plant doesn't actually place, nothing happens and the game crashes almost immediately.

**Crash Log**
https://haste.antti.codes/xuxehiwifu.mccrash

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 Beta 3

**Additional context**
![image](https://user-images.githubusercontent.com/63791135/108879306-ceb9d300-7609-11eb-9da9-bee8d819a561.png)

These are the plants I tested and all of them made the game crash.

**Comment by democat3457** [comment]
wat
