### ISSUE TITLE
Rustic Mod Quality Bucket Duplicating[BUG]

### ISSUE THREAD

**Issue by Bernie1o1** [Rebirth-of-the-Night/Rebirth-Of-The-Night#661]
**Describe the bug**
Creating Ale with the Rustic Mod duplicates the Quality Bucket

**To Reproduce**
Steps to reproduce the behavior: When creating a bucket of ale you keep your original bucket and gain a new bucket of ale which when dispensed into a barrel will leave you with two quality buckets

**Info (please complete the following information):**
 - Modpack Version: Version 3 Beta
 - Server or Singleplayer: have only tested single player
 - Version the world was created on: Version 3 Beta

**Comment by Foreck1** [comment]
Rustic alcohol is replaced with Growthcraft alcohol in the next update, making this issue obsolete.
