### ISSUE TITLE
[CRASH] world crashes upon entering the twilight forest

### ISSUE THREAD

**Issue by PDMephisto** [Rebirth-of-the-Night/Rebirth-Of-The-Night#662]
**Describe the crash**
The world crashes upon loading the twilight forest 

**To Reproduce**
Steps to reproduce the behavior: enter into the portal to the twilight forest again

**Crash Log**
https://haste.antti.codes/kexowekipe.mccrash

**Info (please complete the following information):**
 - Modpack Version: beta 4
 - Server or Singleplayer: single player
 - Version the world was created on: 1.12.2

**Additional context**

**Comment by KaleThyself** [comment]
I have not been able to replicate this issue in either stable v.3.1.1a or stable v.3.0.1a.
