### ISSUE TITLE
[BUG] goblins all started with maces. before the progression stage

### ISSUE THREAD

**Issue by PDMephisto** [Rebirth-of-the-Night/Rebirth-Of-The-Night#663]
**Describe the bug**
goblins had maces upon starting the world, well before they are supposed to be gated to.

**To Reproduce**
start a new world
wait for night

**Expected behavior**
maces are supposed to be progression gated 

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: beta 4
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 1.12

**Additional context**

**Comment by CalaMariGold** [comment]
Pretty sure this was fixed in the hotfix, if not, beta 5
