### ISSUE TITLE
[BUG] Duplication with Radiant Crafting Table in Multiplayer

### ISSUE THREAD

**Issue by LadivItnas** [Rebirth-of-the-Night/Rebirth-Of-The-Night#666]
**Describe the bug**
Extremely easy duplication bug using the radiant crafting table. It only works on items craftable in the 3x3 grid of the Radiant Crafting Table, and requires a minimum of two players. It does not create ghost items, they can be dropped and used normally.

**To Reproduce**
1. Player A places a crafting recipe into the Radiant Crafting Table (Example: One copper ingot to turn into nuggets.)
2. Player B accesses the Radiant Crafting Table (They see the copper to nuggets recipe).
3. Player A Completes the crafting recipe (Turns the copper ingot into nuggets.)
4. Player B sees the crafting ingredients disappear as Player A finishes crafting, but is still able to take the result of the recipe out, effectively duplicating the result. (Player B takes out the nuggets, which are still shown, duplicating the copper.)

**Expected behavior**
The Radiant Crafting Table can keep crafting ingredients in its inventory even if the player exits the GUI. The result of this is that, like a chest, it can be accessed by two players at once. Ingredients taken in and out of the inventory can be observed by anyone opening the chest. If one player finishes the crafting recipe, the ingredients disappear, as well as the result of the recipe, as they should.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5

**Additional context**
I guess Radiant Crafting Tables aren't made for multiplayer. You can't dupe the ingredients, and taking one of the ingredients out takes it out for both players, as well as when they are put back in. However, the recipe will remain the same regardless. If player A enters the GUI when its empty, the result will remain empty regardless of Player B trying to craft an item. This is fixed by closing and reopening the GUI. If Player A does that, and then Player B takes out the crafting ingredients, Player A will still see the crafting result, and can take it out even when the ingredients are no longer there, costing nothing. I didn't test this, but I assume that the effect will be multiplied for every player added.

**Comment by KaleThyself** [comment]
Fixed in 3.0. Radiant Crafting Tables are now instanced per player, so only one player can use it at a time.

**Comment by democat3457** [comment]
noice. also just noticed the issue number
