### ISSUE TITLE
[BUG] Kettle not accepting more than one bucket of water

### ISSUE THREAD

**Issue by Tomato-No-Mae** [Rebirth-of-the-Night/Rebirth-Of-The-Night#668]
Version: Beta 3

Description:
When you place a kettle down and right click it to add water from a bucket it will not let you if there is any amount of water in the kettle at all.

You can only add water when the kettle is completely empty

Submitted via mobile so sorry for not having the usual template

**Comment by democat3457** [comment]
Fixed in beta 4 (it also adds a pipette for removing these 1mb of water :wink:)
