### ISSUE TITLE
[BUG] Recipe is incorrect for earthen ruby in beta 4

### ISSUE THREAD

**Issue by SoulRacer65** [Rebirth-of-the-Night/Rebirth-Of-The-Night#671]
**Describe the bug**
earthen ruby requires a earthen ruby to make instead of a bop ruby
**To Reproduce**

**Expected behavior**
earthen ruby uses bop ruby instead of itself

**Screenshots**
![image](https://user-images.githubusercontent.com/66193653/109433143-781b1300-79d4-11eb-885c-95bd408006cc.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 4
 - Server or Singleplayer: singleplayer, but should also be seen on servers
 - Version the world was created on: 3.0 beta 4

**Additional context**

**Comment by Kompreya** [comment]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/6eb0055d091f53e3124915d0ef8c8f4d44a7f69d
