### ISSUE TITLE
[CRASH] holding an animal while interacting a myrmex/npc/any thing that gives trades

### ISSUE THREAD

**Issue by iEatShadows** [Rebirth-of-the-Night/Rebirth-Of-The-Night#672]
**Describe the crash**
holding an animal while interacting (right clicking) a myrmex/npc/any thing that gives trades, force closes the window.

**To Reproduce**
1. hold an animal that can be held.
2. interact with villager or myrmex while holding the animal.
3. crash.

**Crash Log**
here's the crash logs https://pastebin.com/KwQaTjg0

**Info**
 - Modpack Version: 3.0 Beta 4 v2
 - Server or Singleplayer: both
 - Version the world was created on: 3.0 Beta 4 v2

**Additional context**

**Comment by democat3457** [comment]
Opened issue https://github.com/Fuzss/gamblingstyle/issues/2

**Comment by Fuzss** [comment]
How exactly are you able to hold an animal? Which mod provides this feature? Carry On possibly?

**Comment by SenatorSupreme** [comment]
Yeah it's Carry On

**Comment by democat3457** [comment]
still cant access it, but then again we cant interact with anything period when holding an animal so its intended
