### ISSUE TITLE
Please help me fix this issue!.

### ISSUE THREAD

**Issue by NotAlyxir** [Rebirth-of-the-Night/Rebirth-Of-The-Night#673]
**Describe the crash**

**To Reproduce**

**Crash Log**

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA 4
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 BETA 3

**Additional context**

**Comment by NotAlyxir** [comment]
the issue is interactions pls help me fix it!

**Comment by democat3457** [comment]
bro we dont even have a crash log or a crash report, how would we help you

and also hotfix soon:tm: for this

**Comment by democat3457** [comment]
and also although a world reset is highly recommended, its very likely that unintended biomes and enchantments will be produced because ids shift
