### ISSUE TITLE
[BUG] Crafting a chopped logs dupes the axe that you use 2.77.5

### ISSUE THREAD

**Issue by BigBrainedGam3r** [Rebirth-of-the-Night/Rebirth-Of-The-Night#674]
Crafting chopped logs with any type of axe that you can use will dupe the axe after you exit out of the inventory screen, the axe both keeps its enchantment and quality and loses barely any durability.

**Comment by democat3457** [comment]
is this replicable on 3.0 is the real question

**Comment by KaleThyself** [comment]
Not replicable on 2.77.5 or 3.0...

**Comment by iEatShadows** [comment]
just did some EXTREAM testing. Results: **It only ghosts the item**. it has something with PLAYER crafting inventory lag. 
1. Used 64 wood logs to pull off the lag also have a crafting table nearby
2. place the axe and wood logs in the player crafting slots. SHIFT+LEFT CLICK the end result which is the chopped logs
3. quickly exit the player inventory then right click a crafting table
4. you should get the axe back with the new chopped logs
5. exit the crafting table then press E to look into your inventory
6. you should see the axe and wood logs still in the player crafting slots.
7. you can take em out but they are not usable.
