### ISSUE TITLE
[BUG] Iron Nuggets -> Nails recipe conflict

### ISSUE THREAD

**Issue by cha0sbuster** [Rebirth-of-the-Night/Rebirth-Of-The-Night#679]
**Describe the bug**

The crafting recipe for Nails involves nuggets of various metals, among them being Iron. However, when attempting to make nails out of Iron Nuggets, it instead creates an Iron Ring, an item that, as far as I can tell, isn't used for anything, basically wasting Iron. The recipe works as intended for Tin, however.

**To Reproduce**
1. Have Iron Nuggets.
2. Navigate to the recipe for Nails in JEI.
3. Click the "+" button that moves the ingredients to the crafting grid.
4. An Iron Ring will appear under output, rather than Nails.

**Expected behavior**

I expect Nails to be in the output slot, rather than an Iron Ring.

**Screenshots**

![image](https://user-images.githubusercontent.com/22553697/109771559-f3461a00-7bca-11eb-89b3-63d2935e219e.png)
![image](https://user-images.githubusercontent.com/22553697/109771591-fc36eb80-7bca-11eb-920d-7df80fb6de3e.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA 4
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 BETA 4 

**Additional context**
A player experiencing this bug could install a mod such as Polymorph to sidestep the issue, but with a pack as intricately crafted as this one, I'm not confident concretely making the recommendation as a workaround that won't potentially introduce new issues. So y'know, here there be dragons etc.

**Comment by democat3457** [comment]
The nails recipe is shapeless, whereas the iron ring recipe is not.

**Comment by democat3457** [comment]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/57fa5d5f21fcc4574694142ef63fa6b7fdd72a1e
