### ISSUE TITLE
[BUG] Spike Trap recipe doesn't work

### ISSUE THREAD

**Issue by cha0sbuster** [Rebirth-of-the-Night/Rebirth-Of-The-Night#680]
**Describe the bug**
When attempting to craft Spikes, no output appears in the crafting grid. 

**To Reproduce**
1. Put the components necessary to produce Spikes into a crafting grid.
2. Nothing will appear in the output slot.

**Expected behavior**

I expect my spike trap, dangit!

**Screenshots**

![image](https://user-images.githubusercontent.com/22553697/109772332-dcec8e00-7bcb-11eb-85a7-4b285315e251.png)

**Info (please complete the following information):**
 - Modpack Version: 
 - Server or Singleplayer:
 - Version the world was created on:

**Additional context**

I'm kinda stumped on this one, to be honest. However, a similar problem occurs with Nail Traps, which I'll outline in another issue that references this one.

**Comment by Ninjayatsu** [comment]
Ok the problem isn't the mod, you have to use nails at full durability or the recipe will not work. not bug

**Comment by cha0sbuster** [comment]
> Ok the problem isn't the mod, you have to use nails at full durability or the recipe will not work. not bug

...so anyways, there is no "full durability" for them in this pack, there's no way to increase durability, and making a fresh set puts them at this durability level.
this has caused other problems which have already been addressed.
you're not even a developer.

but go off

**Comment by democat3457** [comment]
the nails problem has been fixed, the recipe now gives full dura nails

**Comment by democat3457** [comment]
also dont attack em, they're just trying to help

**Comment by democat3457** [comment]
fixed when nails recipe was fixed
