### ISSUE TITLE
[BUG] Unexpected behavior while crafting with Nails

### ISSUE THREAD

**Issue by cha0sbuster** [Rebirth-of-the-Night/Rebirth-Of-The-Night#681]
**Describe the bug**
When attempting to create a nail trap, 2 sets of Nails put together in a crafting grid behave strangely. When 2 fresh sets of nails are put in a crafting grid, rather than creating a Nail Trap as expected, a single set of nails appears in the output slot. This set will not stack with other sets, implying it has NBT data that the fresh sets do not.

Occasionally, these "doubled" nails will properly create a Nail Trap when paired with either a fresh or doubled set -- but it's inconsistent.

**To Reproduce**
1. Create some Nails with any metal, 3 is sufficient to completely demonstrate the behavior. (Tin or Silver, as I've detailed previously that Iron currently doesn't work: #679 )
2. Attempt to craft a Nail Trap by putting two sets of Nails in a crafting grid together. A single set of Nails will appear in the output slot. Crafting it will consume both of the "fresh" Nails.
3. Place the new "doubled" set of Nails into a crafting grid, with the third "fresh" one. Sometimes it will create a Nail Trap, other times, nothing will happen.

**Expected behavior**

I expect two sets of nails, whether or not they've been "combined" in this way, to create a Nail Trap.

**Screenshots**

3 sets of fresh Nails. They stack as expected.
![image](https://user-images.githubusercontent.com/22553697/109773201-ec200b80-7bcc-11eb-9957-d0dcd06df81a.png)

The result of putting 2 "fresh" Nails in a crafting grid.
![image](https://user-images.githubusercontent.com/22553697/109773450-373a1e80-7bcd-11eb-9148-fca286a98f37.png)

The "fresh" and "doubled" nails do not stack.
![image](https://user-images.githubusercontent.com/22553697/109773599-62247280-7bcd-11eb-8a2d-85c76f54c8a1.png)

Occasionally, these sets work, but sometimes they don't. It seems whether they're made in a 2x2 or 3x3 grid will determine whether they work or not, but I can't confirm this as of right now.

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA 4
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 BETA 4

**Additional context**

Short of knowing the mod that the nails came from and being intimately familiar with its mechanics, I can't say for sure what the issue is, but if there's anything I'm good at, it's shaky conjecture based on immediately present evidence!

I've noted that the Nails have a durability value when in the inventory, when they don't in JEI. (Quick-moving from JEI has no impact on their behavior.) They also have a durability meter. Crafting them together seems like, in an unedited version of their source mod, they'd be "put together" in a pseudo-stack, similar to TerraFirmaCraft's food stacking.

I'm led to believe, then, that this issue is related to (or rather, the SOURCE of) #680 . I'd suspect a script error with regards to the Nails causing them to create malformed NBT data(?) that the crafting recipes INVOLVING the Nails doesn't like.
This is all conjecture, of course.

Unfortunately, short of cheating (which honestly I'm not above), I'm stuck in terms of progression unless I can find or be informed of a workaround.

**Comment by cha0sbuster** [comment]
UPDATE: The Nail Trap recipe consistently works when A STACK OF TWO Nails, either "fresh" or "doubled", are paired together. They can also be mixed together!

![image](https://user-images.githubusercontent.com/22553697/109776148-4a9ab900-7bd0-11eb-81ab-dab5d754fa78.png)

**Comment by democat3457** [comment]
I'm guessing that combining two nails = strange nails because it's trying to add the durabilities together, such as the way you can combine tools to get an increased durability. Can change the recipe for nail traps slightly.

**Comment by democat3457** [comment]
Nail traps recipe changed: https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/1685cb40b751ca4a0b2e1e66fd1d9b12f58e35cf
