### ISSUE TITLE
[BUG] Loot added by LTT not dropping

### ISSUE THREAD

**Issue by Kompreya** [Rebirth-of-the-Night/Rebirth-Of-The-Night#682]
**Describe the bug**
Loot added to mobs using LTT (LootTableTweaks) don't drop.
For example, iron from the wroughtnaut, sharptooth from frostmaw, and more.

**To Reproduce**
Add loot to a table using LTT, slay monster, loot doesn't drop

**Info (please complete the following information):**
 - Modpack Version: Beta3
 - Server or Singleplayer: Single

**Additional context**
Found this bug while I was adding loot to the wroughnaut. Self reporting so we can track and fix it, and to avoid duplicate issues.
Can be fixed by changing our loot handler to LootTweaker.
LTT should only be used for globally removing loot.
This issue may be affecting other loot tables, but haven't tested yet.

**Comment by Kompreya** [comment]
Wroughtnaut loot fixed.

**Comment by democat3457** [comment]
Because there's a workaround, this will be closed.
