### ISSUE TITLE
[BUG] Falling Meteors on servers causing massive tps issues

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#683]
**Describe the bug**

- Looking at the nyx.cfg file, there seems to be a discrepancy with the spawn rates of meteors during the day and during the night for the chance of meteors spawning every second after the gate dimension has been entered. 

https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/blob/57166eebc6eb9bcc18a6b2982100896587f83243/config/nyx.cfg#L181
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/blob/57166eebc6eb9bcc18a6b2982100896587f83243/config/nyx.cfg#L184

- Line 184's value of `0.007`, in turn, causes meteors to spawn out of control on server worlds. On multiplayer servers, meteors are **multiplied** per player after each team or group of players enter the nether. 

- As a result,, the server tps drops, connections turn to red bars, and the server becomes practically unplayable. 

- Also, since meteors and stars from nyx can't cross unloaded chunk borders while falling, they get stuck in the sky which obviously builds up in numbers and is the culprit of the lag caused by meteors. 

**To Reproduce**
1. Start exploring and loading chunks around an area on a server. 
2. Enter the nether on a server with at least 2-3 players who play regularly. 
3. Exit the nether into the overworld. 
4. Play for a few in-game days and nights with a base and have meteors accumulate. 
5. Start exploring the same loaded chunks in step 1. 
6. See that tons of meteors have fallen and will not stop falling, causing massive lag. 

**Expected behavior**
I expect line 184 in the nyx.cfg file to have the value `0.0007` instead of `0.007` in order to match line 181's decimal places of `0.0001`.

**Screenshots**
From another player who has played RoTN 3.0 Beta 4 on a server recently. 
![image](https://user-images.githubusercontent.com/50285548/109878849-ab0a1480-7c29-11eb-8f6b-5bcc89824c2c.png)
*"i had about 5 more spawns not even 30 seconds after i took the pic. the spawn rate is truely insane"
-Draganot*

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 4
 - Server or Singleplayer: Server 
 - Version the world was created on: 3.0 Beta 4

**Additional context**
- Extensive testing was put through by a server host, another player, and myself in order to come to these conclusions above. 

- This commit by CalaMariGold was intended to lower the spawn rates of the meteors before the Beta 4 update, but it instead **increased** the spawn rate: https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/a7de086268c1bcceb905547d052ba9eebd6107b8

**Comment by kil0byt3** [comment]
nice bug report 10/10

**Comment by SenatorSupreme** [comment]
> 
> 
> nice bug report 10/10

Thought you were being sarcastic until I saw it.

das hot
