### ISSUE TITLE
[BUG]Unharvestable Onyx

### ISSUE THREAD

**Issue by Y4m4to19** [Rebirth-of-the-Night/Rebirth-Of-The-Night#684]
**Describe the bug**
I killed Wither, then tried to harvest Onyx.

**Screenshots**
![image](https://user-images.githubusercontent.com/80107166/110120803-cefe5f00-7dbd-11eb-9419-fd71b7e0d839.png)
<This Onyx Pickaxe is from Wither>

**Info (please complete the following information):**
 - Modpack Version: 3,0 Beta4
 - Server or Singleplayer: LAN server
 - Version the world was created on:3.0 Beta3

**Comment by CalaMariGold** [comment]
1. you're on a LAN server. LAN is not supported.
2. you didnt create a new world like we said you should
