### ISSUE TITLE
[BUG] Scroll Of New Life drying rack issue

### ISSUE THREAD

**Issue by Noisythunder** [Rebirth-of-the-Night/Rebirth-Of-The-Night#688]
**Describe the bug**
 If you right click a drying rack with a Scroll of new life the message: Your destiny has been written..., appears but it doesn't 
 consume the item

**To Reproduce**
Right click a drying rack with a scroll of new life

**Expected behavior**
  the scroll of new life should get consumed or the message shouldn't appear

**Info:**
 - Modpack Version: 3.0 beta 4
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 3.0 beta 4

**Comment by CalaMariGold** [comment]
Fixed in beta 5
