### ISSUE TITLE
[BUG] Basalt bricks and others appear as acacia nailed boards

### ISSUE THREAD

**Issue by elipol02** [Rebirth-of-the-Night/Rebirth-Of-The-Night#689]
**Describe the bug**

Basalt, komatite, gabbro, andesite, rhyolite, black granite, dacite, and red granite all appear as acacia nailed boards in the world, but appear correctly in the inventory.
**To Reproduce**
Place any of those blocks down in the world
**Expected behavior**

They should appear as the correct block

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 4
 - Server or Singleplayer: single player
 - Version the world was created on: 3.0 beta 3

**Additional context**
 I tested this in a world that was made in beta 3 4.0 and the blocks appeared correctly

**Comment by TheNelston** [comment]
Seems to be an issue with block IDs since you ported a Beta 3 world to Beta 4, not much we can do about that and it shouldn't happen in future versions anyways.

**Comment by democat3457** [comment]
(add or remove labels when closing)
