### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by Taha-uhc** [Rebirth-of-the-Night/Rebirth-Of-The-Night#691]
**Describe the crash**
<!-If I try to hit a hostile mob, the game crashes. The cause is the ambience mod. -->

**To Reproduce**

**Crash Log**
 https://haste.antti.codes/udikuvowad.mccrash  

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 4
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 3/8/2021

**Additional context**
<!-- removing the ambience mod fixes this problem but then some textures get corrupt. --
<img width="656" alt="Screenshot 2021-03-08 085021" src="https://user-images.githubusercontent.com/80265604/110330074-55e44f00-7feb-11eb-969f-a6fe8d60424b.png">
>

**Comment by InlustrisXIII** [comment]
This person was using the serverpack on his client. This can be closed.

**Comment by TheNelston** [comment]
please use the client pack!
