### ISSUE TITLE
[BUG] Baubles disappear after being killed

### ISSUE THREAD

**Issue by PhaedrusXY** [Rebirth-of-the-Night/Rebirth-Of-The-Night#693]
**Describe the bug**
All baubles disappeared after being killed by Valkyrie Queen, as well as several other inventory items, for both me and my friend. We returned immediately, and picked up most stuff. So it wasn't a problem with despawning.
**To Reproduce**
Fight queen, die while wearing backpack and baubles.

**Expected behavior**
For my baubles to be safe when dying.

**Screenshots**
n/a

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 4
 - Server or Singleplayer: server, also uses some plugins (homes, etc)
 - Version the world was created on: 3.0 beta 4

**Additional context**

**Comment by CalaMariGold** [comment]
Can someone else reproduce this consistently on singleplayer and server?

**Comment by InlustrisXIII** [comment]
> also uses some plugins (homes, etc)
Clarify this please? Are you only using forge, or are you using spongeforge or another alternative? 
Also list what "plugins" you are using please. These can affect inventory management.


> Can someone else reproduce this consistently on singleplayer and server?
Will test.

**Comment by PhaedrusXY** [comment]
I'm playing on the Hydrox public server listed on the RotN discord page. I don't know exactly what plugins they use, as I am not a moderator there. I will ask one of them to comment here.

**Comment by KookosPahkina** [comment]
We are using spongeforge-1.12.2-2838-7.3.0.jar and the following plugins
worldedit-sponge-api7.1.0-6.1.10-SNAPSHOT-dist.jar
TotalEconomy-1.8.1.jar
shabbyholograms-1.0-SNAPSHOT-shaded.jar

**Comment by KookosPahkina** [comment]
We are using spongeforge-1.12.2-2838-7.3.0.jar and the following plugins
![plugins](https://user-images.githubusercontent.com/16511128/110354897-54457600-8041-11eb-8d1a-afef7c83eaf6.PNG)

**Comment by InlustrisXIII** [comment]
Nucleus affects inventories, it's similar to Essentials for vanilla servers; however I will test this on a non-modifed RotN server shortly. Might be a RotN bug, or just spongeforge "ores" causing issues. Will update later

**Comment by PhaedrusXY** [comment]
I also had a totem of returning go off.

**Comment by PhaedrusXY** [comment]
I meant undying...

**Comment by KaleThyself** [comment]
I was unable to replicate this issue in v.3.1.1a singleplayer. I believe it occurred due to the additional plugins/mods added to the server which may have caused issues.
