### ISSUE TITLE
Mobs Can Walk And Jump On Ice[BUG]

### ISSUE THREAD

**Issue by SenatorSupreme** [Rebirth-of-the-Night/Rebirth-Of-The-Night#696]
**Describe the bug**

Zombies and maybe other mobs can walk and jump on ice without it breaking
**To Reproduce**
just have a zombie walk on ice
**Expected behavior**

for the ice to break like it would for the player
**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA 4
 - Server or Singleplayer: Server
 - Version the world was created on: 3.0 BETA 4

**Additional context**

**Comment by democat3457** [comment]
you just jealous that they walk lighter than you

**Comment by SenatorSupreme** [comment]
Ability to lose weight in rotn when

**Comment by KaleThyself** [comment]
No longer relevant since the Fragile Glass & Thin Ice mod has been removed.
