### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by F0AMEXE** [Rebirth-of-the-Night/Rebirth-Of-The-Night#698]
On my Rebirth of the Night server that I host I can not break any blocks. At first, I thought it was the Davinci's Vessels mod that that was causing this because it only happened whenever I made an airship. I restarted the server and it fixed itself. Then I used an airship again and tried to restart and now I still can not break blocks. How do I fix this?

**Comment by SenatorSupreme** [comment]
1. Please reserve questions for the discord
2. You really cant do anything. Try and break it and if that doesn't work then your world is bricked.

**Comment by CalaMariGold** [comment]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/406
