### ISSUE TITLE
[BUG] ToroQuest Error trying to accept quest from lord

### ISSUE THREAD

**Issue by flumignano** [Rebirth-of-the-Night/Rebirth-Of-The-Night#699]
"java.util.concurrent.ExecutionException: java.lang.NullPointerException: quest delegator was set with a null"

https://pastebin.com/R0trY3r4

Of note: the name of the lord is Lord of Bloomfare but the village he is in is called Weigela. The village seems to have generated with a different name from the name of the village seen in the NPC trade screens!

**Comment by CalaMariGold** [comment]
Use our template
