### ISSUE TITLE
[BUG] Cooking stock in a cooking pot grants diminishing returns (Beta 4)

### ISSUE THREAD

**Issue by WarspiteEnthusiast** [Rebirth-of-the-Night/Rebirth-Of-The-Night#701]
Describe: 
When cooking stock in a cooking pot with meats (3 stock) or vegetables (2 stock), you will only get the proper amount when the output slot of the pot is empty. If there is already stock in the slot, you will only get one instead of the intended amount.

Reproduction:
Place a furnace, place a cooking pot on top of it, then add water. Put meat in the pot and wait for it to cook into stock. The first one will result in 3 stock being produced. If said stock is left in the output slot of the pot, the next piece of meat that is cooked will only produce one stock.

Expected behavior:
You will get 30 bowls of stock when you cook 10 pieces of meat, not 12. 

![image](https://user-images.githubusercontent.com/80505411/110898341-e94fa580-82b3-11eb-85c2-d82ee3b7e517.png)
![image](https://user-images.githubusercontent.com/80505411/110898360-f4a2d100-82b3-11eb-9846-96db92c7ff5e.png)
![image](https://user-images.githubusercontent.com/80505411/110898380-fbc9df00-82b3-11eb-8833-45fcc1d208a1.png)
![image](https://user-images.githubusercontent.com/80505411/110899024-32ecc000-82b5-11eb-88bf-132b7b2b8577.png)

   Info:
 - Modpack Version: 3.0 Beta 4
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 Beta 4

**Comment by TheNelston** [comment]
The recipe in the .zs file is correct, this appears to be a mod bug/poor implementation of crafttweaker on the mod author's part

**Comment by CalaMariGold** [comment]
Seems it was fixed in the latest update. Will be in beta 5
