### ISSUE TITLE
[BUG] Gorgon statues not working correctly on some mobs

### ISSUE THREAD

**Issue by Tomato-No-Mae** [Rebirth-of-the-Night/Rebirth-Of-The-Night#704]
**Describe the bug**
When the gorgon turns mobs into statues you can mine them with a pickaxe to get some cobblestone, however, with some mobs like the player zombies and warrior skeletons, this does not happen. When you attempt to mine them the statue will disappear and will leave the "wounds" from the player zombies and the helmet, sword, and bow from the warrior skeletons.

**To Reproduce**
find/spawn gorgon
make it statuify a player zombie or warrior skeleton
mine with pickaxe

**Expected behavior**
for cobblestone to drop

**Screenshots**
![image](https://user-images.githubusercontent.com/67121000/111054504-c4357100-8432-11eb-83d8-862b9d42525a.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 4
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 3.0 beta 4

**Additional context**

**Comment by KaleThyself** [comment]
Cobblestone still drops if you keep whacking the leftovers that they leave with a pickaxe. However, I'm unsure why their main models become invisible.

**Comment by democat3457** [comment]
👀 can you send logs, the entity might have crashed, causing it to disappear

**Comment by Tomato-No-Mae** [comment]
I looked in the logs and crash reports folder but there were no files from the time this happened

**Comment by democat3457** [comment]
It wouldn't cause a crash report file to be generated because it would only affect a specific entity, but it might generate in the log file itself - send the debug.log or latest.log.

**Comment by Tomato-No-Mae** [comment]
[latest.log](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6135976/latest.log)
can't send the debug cause it's too big but here's latest.log

**Comment by democat3457** [comment]
lets see... i find some alpine does, an alpine buck, and some barakoas that crashed, but no gorgonified stuff or warrior skeletons...

**Comment by democat3457** [comment]
ok so its probably because the mob still exists technically - i&f does weird stuff with the statues. since the mobs still drop cobble if you keep whacking them, this is something that we wont fix
