### ISSUE TITLE
[BUG] zombies & skeletons spawning at wrong game stages on spiders.

### ISSUE THREAD

**Issue by Ninjayatsu** [Rebirth-of-the-Night/Rebirth-Of-The-Night#705]
**Describe the bug**

Even when a game stage is not reached, plague zombies, mushrooms, and burning zombies and skeletons can spawn ON SPIDERS. this only happens on spiders

**To Reproduce**

open up a world, and watch mobs spawn during the night, make sure you haven't unlocked any game stages.

**Expected behavior**

later game mobs don't spawn on spiders in the earlier game stages.

**Screenshots**

don't have any but know others who experienced this

**Info (please complete the following information):**
 - Modpack Version:  3.0.0
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: beta 4

**Additional context**

idk how to fix but it definitely works differently from normal mobs, I suspect for the mod dev to have added the possibility of the mob riding on a spider there should be a way to refer to it specifily in the source code, but idk cause they are 2 different entities, so maybe if you could make it so the mobs can't ride on spiders until the game stage requirements are met and they can spawn. that how I would do it.

**Comment by KaleThyself** [comment]
This issue is not replicable on v.3.1.1a.
