### ISSUE TITLE
[BUG]blood moons and star falling nights being wonky

### ISSUE THREAD

**Issue by Ninjayatsu** [Rebirth-of-the-Night/Rebirth-Of-The-Night#706]
**Describe the bug**

I got a stars falling night, but only a couple stars fell ( like 2 or 3) then I got a blood moon right after that and that night a bunch started falling

**To Reproduce**

get a night where stars fall a lot and then a blood moon night the next night

**Expected behavior**

a normal amount of stars fall on a star falling night, and not on the next blood moon night.

**Screenshots**

![2021-03-14_17 25 46](https://user-images.githubusercontent.com/66919658/111084851-decb2100-84ea-11eb-97c9-35f9bc2f0274.png)

**Info (please complete the following information):**
 - Modpack Version: 3.0.0
 - Server or Singleplayer:Singleplayer
 - Version the world was created on:beta 4

**Additional context**

not sure why, maybe a mod conflict if blood moon mod and the one that makes the stars fall are seperate.

**Comment by iEatShadows** [comment]
after getting those 2 stars, did you go anywhere else? or just only stayed in/near your base?

**Comment by democat3457** [comment]
Also fyi the same mod handles blood moons and falling stars

**Comment by KaleThyself** [comment]
This issue may be indirectly related to #683.
> - Also, since meteors and stars from nyx can't cross unloaded chunk borders while falling, they get stuck in the sky which obviously builds up in numbers and is the culprit of the lag caused by meteors.

**Comment by democat3457** [comment]
This seems like a really obscure edge case anyway, so closing
