### ISSUE TITLE
[BUG] Non-vanilla milks cannot be used to brew kumis

### ISSUE THREAD

**Issue by TheNelston** [Rebirth-of-the-Night/Rebirth-Of-The-Night#707]
**Describe the bug**
Non-vanilla milks (Animania) cannot be used in a fermentation barrel to produce kumis.

**To Reproduce**
1. Put Animania cow/goat milk in a fermentation barrel
2. Cry

**Expected behavior**
1. Put Animania cow/goat milk in a fermentation barrel
2. Obtain kumis 

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 4 (Dev Build)
 - Server or Singleplayer: Singeplayer
 - Version the world was created on: 3.0 Beta 4 (Dev Build)

**Additional context**
We need to replace Growthcraft kumis recipes with oreDict fluid milk to create the desired effect

**Comment by TheNelston** [comment]
The fix is known, I'm just too lazy to actually implement this anytime soon

**Comment by CalaMariGold** [comment]
kumis

**Comment by democat3457** [comment]
cum is kumis

**Comment by TheNelston** [comment]
i hate you both

**Comment by TheNelston** [comment]
Fixed, recipe already exists to turn animania milk into vanilla milk
