### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by sakkezboi** [Rebirth-of-the-Night/Rebirth-Of-The-Night#709]
**Describe the crash**

just keeps on crashing as soon as i join the world

**To Reproduce**

**Crash Log**

https://haste.antti.codes/setoceweju.mccrash

**Info (please complete the following information):**
 - Modpack Version:  3.0 Beta 4
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 Beta 4

**Additional context**

halp

**Comment by SenatorSupreme** [comment]
I've never seen this myself, but apparently it's because of world corruption

https://forums.minecraftforge.net/topic/63617-javautilzipzipexception-incorrect-data-check/

https://www.spigotmc.org/threads/java-util-zip-zipexception-incorrect-data-check.25315/

**Comment by democat3457** [comment]
Unfortunately this isn't something that can be fixed safely or reliably. The world is corrupted, yes.
