### ISSUE TITLE
[BUG] Slayer's Journal chapter doesn't appear after getting drop

### ISSUE THREAD

**Issue by CalaMariGold** [Rebirth-of-the-Night/Rebirth-Of-The-Night#710]
**Describe the bug**
After picking up the slayers Journal drop, we got the achievement but didn't get the new chapter unlocked

**To Reproduce**
Join a server with friend
Create a team
1 or both players pick up journal
No chapter unlocked

**Info (please complete the following information):**
 - Modpack Version: beta 4 hotfix
 - Server or Singleplayer: akliz server
 - Version the world was created on: beta 4 hotfix

**Additional context**
Relogging fixed it.

**Comment by CalaMariGold** [comment]
Can someone test this on a server and find out if Teams is causing the issue?

**Comment by CalaMariGold** [comment]
I've determined the issue is not caused by the Teams mod.

Tested on a server with 1 other player, I picked up the journal and got the achievement but no chapter unlocked. Rejoining unlocked the chapter.

**Comment by CalaMariGold** [comment]
Created an issue on Patchouli GitHub, awaiting response.

**Comment by SenatorSupreme** [comment]
Not replicable on a Patchouli only server, needs testing.

**Comment by KaleThyself** [comment]
After several zombie, skeleton, bandit, creeper, and spider kills on the first night in v.3.1.1a, I've been unable to acquire a Slayer's Tattered Journal despite acquiring the Farmer's Tattered Almanac instead on my first zombie kill. However, when giving myself the Slayer's Tattered Journal with cheats, I am able to get the advancement. (Tested on Singleplayer)

**Comment by KaleThyself** [comment]
This issue appears to be resolved as of version 3.2.1a.
