### ISSUE TITLE
[BUG] double rmb clicks

### ISSUE THREAD

**Issue by Randoom17** [Rebirth-of-the-Night/Rebirth-Of-The-Night#711]
**Describe the bug**
A Well, torches, doors. Pressed rmb once but it may doubled. It works every time with a well and a bucket, so when I try to take water from the well (when I have not only 1 bucket), I get a bucket of water, but also a stream from the block next to the well/

**To Reproduce**
Take 2 and more buckets (i used iron ones)
Press rmb on a well with a bucket in a hand.

**Expected behavior**
A stream begins to flow from a block near a well

**Screenshots**
![2021-03-23_00 24 49](https://user-images.githubusercontent.com/81188002/112046989-80e3ac80-8b6e-11eb-947a-163f82a55326.png)
![2021-03-23_00 24 51](https://user-images.githubusercontent.com/81188002/112046997-850fca00-8b6e-11eb-8c05-1c4e243f76b4.png)

**Info (please complete the following information):**
3.0 beta V4
Singleplayer:
3.0 beta V4

**Additional context**
I have not a good mouse but it can't double click every time only with a certain object.

**Comment by TheNelston** [comment]
I think this is a bug with the no cooldown rmb mod, may have to look at that

**Comment by CalaMariGold** [comment]
yeah i should probably make it not so instant

**Comment by Randoom17** [comment]
I'm glad the problem isn't with a mouse. Thank you

**Comment by Randoom17** [comment]
Noticed smth else. When i jump and spam rmb i can't place a block under me. Guess it happens when i use a red balloon or smth with additional jump height.

**Comment by democat3457** [comment]
I believe that's because there was a config setting somewhere to disable easy pillaring

**Comment by Rigobert0** [comment]
Also works with the following: put a door in front of a crafting table and open the door. The crafiting table opens itself.
works with any two interactable blocks I guess, also tested it with a chest, same behaviour.

**Comment by CalaMariGold** [comment]
I thought for sure there was a config to adjust the place speed, but there isn't. 

I really like the instant block placement and makes building bases go a lot smoother and faster, but clearly, there are some other issues with it. 

I'm not sure what to do. I could make it creative mode only. That might be the only option.

**Comment by democat3457** [comment]
can we confirm that it's the instant block placement mod causing it
