### ISSUE TITLE
[BUG] "Mochi" trouble

### ISSUE THREAD

**Issue by Randoom17** [Rebirth-of-the-Night/Rebirth-Of-The-Night#712]
**Describe the bug**
Rice and honeycombs are multiplies when I craft mochi. Also, bottles of water disappear and only one stays.

**To Reproduce**
Put in a crafting window rice (more than 1), honeycombs (more than 1) and bottles of water (more than 1). Then craft mochi.

**Expected behavior**
every ingredient will be multiplied by 2 without wasted ingredients. like  5x2-1=9

**Screenshots**

![2021-03-23_00 22 50](https://user-images.githubusercontent.com/81188002/112047952-b937ba80-8b6f-11eb-80ae-ff21540e58eb.png)
![2021-03-23_00 22 59](https://user-images.githubusercontent.com/81188002/112047977-c0f75f00-8b6f-11eb-941d-46641b4be0a6.png)

**Info (please complete the following information):**
3.0 v4
Singleplayer:
3.0 v4

**Additional context**
guess it's multiplied by two

**Comment by democat3457** [comment]
wtf

**Comment by Randoom17** [comment]
i know, sounds kinda cool cause you can dupe items. But i already have a lot of ingredients, except water bottles...

**Comment by Landsurfer2000** [comment]
huh, will look into this

**Comment by democat3457** [comment]
can reproduce on dev singleplayer, happens with either click or shift-click

**Comment by democat3457** [comment]
and also the water bottle stack is completely consumed and returns one empty bottle

**Comment by KaleThyself** [comment]
This issue has already been resolved, and it is not replicable on v.3.1.1a.
