### ISSUE TITLE
[BUG] bone meal, bone block, mechanical compactor.

### ISSUE THREAD

**Issue by Randoom17** [Rebirth-of-the-Night/Rebirth-Of-The-Night#714]
**Describe the bug**
Not equal craft. Bone meal can be dupped.

**To Reproduce**
Put 8 bone meal in a mechanical compactor to get 1 bone block. Then crush a bone block in a millstone in order to get 9 bone meal. Repeat all steps to get more and more bone meal.

**Expected behavior**
You can get an infinite amount of bone meal.

**Screenshots**
![2021-03-23_22 12 55](https://user-images.githubusercontent.com/81188002/112190581-f448f500-8c26-11eb-91e9-3d198ab60c90.png)
![2021-03-23_22 21 36](https://user-images.githubusercontent.com/81188002/112190595-f7dc7c00-8c26-11eb-8305-19fda2b6a879.png)

**Info (please complete the following information):**
3.0 v 4
Singleplayer:
3.0 v 4

**Additional context**
I'm so sorry if it's not a bug. I really don't know was it planned or not. If it wasn't, please excuse me.

**Comment by TheNelston** [comment]
Fixed in commit `f9435c3` already, I'm surprised Nyagi didn't get to this first

**Comment by Randoom17** [comment]
Glad to hear
