### ISSUE TITLE
[BUG] Villager, Farmer, Village, trades

### ISSUE THREAD

**Issue by Randoom17** [Rebirth-of-the-Night/Rebirth-Of-The-Night#715]
**Describe the bug**
1. Broken trade with a farmer. 6 emeralds for 1 emerald.
2. Librarian doesn't upgrade his level of trading after my trade with him. I used "bugged" emeralds from the previous step.

**To Reproduce**
1. Trade with a farmer. (look at the screenshot)
2. Trade with a librarian. (look at the screenshot)

**Expected behavior**
A librarian should upgrade his level of trading (not only him but I have an issue with him). He has an item on his belt that changes, which indicates a level increase (look at the screenshot). But it doesn't change.

**Screenshots**
A farmer 
![2021-03-23_22 54 36](https://user-images.githubusercontent.com/81188002/112196057-725bca80-8c2c-11eb-8f1a-68cf4d9d3ec2.png)

This thing on a belt that doesn't change 
![2021-03-23_23 04 09](https://user-images.githubusercontent.com/81188002/112196136-8c95a880-8c2c-11eb-826e-15215261776a.png)

A librarian 
![2021-03-23_23 04 22](https://user-images.githubusercontent.com/81188002/112196188-9ae3c480-8c2c-11eb-99e3-749724a51e5f.png)

**Info (please complete the following information):**
3.0 v4
Singleplayer:
3.0 v4

**Additional context**
Seed : 3341179550070224022
Seed screenshot
![2021-03-23_23 09 26](https://user-images.githubusercontent.com/81188002/112196788-337a4480-8c2d-11eb-88e1-febd631d8322.png)

Location 1586, 73, -174

**Comment by democat3457** [comment]
villagers level up from village rep

**Comment by Randoom17** [comment]
Guess it's different from 2.77 and vanilla minecraft. But I already have 186 rep and trades don't change at all. Level doesn't increase.

**Comment by CalaMariGold** [comment]
Librarian actually doesn't have any more trades at all. We'll add more later based on rep. I also removed the emerald to emerald trades, so it will be fixed in beta 5
