### ISSUE TITLE
[BUG] Hoe durability

### ISSUE THREAD

**Issue by realMangoSenpai** [Rebirth-of-the-Night/Rebirth-Of-The-Night#716]
**Describe the bug**
 Hoes doesn't seem to have the durability that is shown on the tooltip. For example a Stone Hoe says to have 135 durability, but it breaks after around 20 blocks 

**To Reproduce**
Steps to reproduce the behavior: simply just make a hoe and hoe the ground.

**Expected behavior**
I expected the hoe to last as long as the tooltip indicated. 

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by Randoom17** [comment]
The same problem. beta 3.0 v4

**Comment by CalaMariGold** [comment]
Well that's annoying. We have a mod that purposely lowers the uses, but instead of lowering the durability, it just uses up like X durability for every use

**Comment by democat3457** [comment]
why can't we use materialchanger

**Comment by CalaMariGold** [comment]
we can we're just lazy

**Comment by democat3457** [comment]
:|

**Comment by democat3457** [comment]
Fixed by #717
