### ISSUE TITLE
[BUG] Snow and leaves spawning in the nether

### ISSUE THREAD

**Issue by CalaMariGold** [Rebirth-of-the-Night/Rebirth-Of-The-Night#723]
**Describe the bug**
Title

**To Reproduce**  
idk

**Screenshots**
![image](https://user-images.githubusercontent.com/57605926/112708602-3cffe880-8e89-11eb-8920-864e644c3be5.png)

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 4
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 4
   - [ ] Other: 

**Additional context**

**Comment by KaleThyself** [comment]
From my experience, this only happens when betternether nether cities are enabled.

**Comment by KaleThyself** [comment]
This generation issue has not shown up in v.3.1.1a so far since nether city generation is now fixed.
