### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by clintonsbn** [Rebirth-of-the-Night/Rebirth-Of-The-Night#724]
**Describe the crash**
Upon first time loading into 2 separate servers (3.0, 2.77.5) I get an immediate crash after loading in of 

**To Reproduce**  
install game on forge and log into a multiplayer server.

**Crash Log**
-Clicking 'get link' fails when i attempt to do so

**Info (please complete the following information):**
 - Modpack Version:
   - [ x] 2.77.5
   - [ ] 3.0 BETA 4
   - [ ] Other: 
 - Server or Singleplayer:
   - [x ] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [x
[crash-2021-04-01_16.22.44-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6246654/crash-2021-04-01_16.22.44-client.txt)
 ] 2.77.5
   - [ ] 3.0 BETA 4
   - [ ] Other: 

**Additional context**
I was able to load into the world after a couple of attempts however all sound seemed disabled, I would only hear an initial sound like a foot step as i loaded into the world and then it would be completely silent afterwards.

**Comment by democat3457** [comment]
Try reinstalling
