### ISSUE TITLE
[BUG] Using JEI automatic recipe fill duplicates armor worn

### ISSUE THREAD

**Issue by MeatBean** [Rebirth-of-the-Night/Rebirth-Of-The-Night#726]
**Describe the bug**
Using the JEI recipe fill did not move ingredients into the grid (using portable crafting mat), similar to when crafting during a lag spike. Moved to a basic worktable to fill the same recipe, and all armor worn (silver) was duplicated and added to my inventory with identical durability.

**To reproduce**

> 1: Look up recipe for monster hide into cut leather

> 2: Fill ingredients to grid on portable crafting mat

> 3: Lag-like effect(?)

> 4: Repeat 1-3 at basic worktable

> 5: Shift-LMB to retrieve all cut leather

**Expected behavior**
On either the crafting mat or basic worktable, filling the recipe should move monster hide into the grid, and Shift-LMB to retrieve the leather should automatically move the product into the inventory (without duplicating armor).

- Modpack Version:

> - [ ] 2.77.5
> - [x] 3.0 BETA 4
> - [ ] Other:

- Server or Singleplayer:
> - [x] Server
> - [ ] Singleplayer

- Version the world was created on: 
> - [ ] 2.77.5
> - [x] 3.0 BETA 4
> - [ ] Other:

**Comment by democat3457** [comment]
cannot reproduce on dev

**Comment by MeatBean** [comment]
Could be, I checked the chest where I put the duplicated armor and it was
gone, so whatever happened I think was temporary-- I think we can call it
resolved.

**Comment by iEatShadows** [comment]
it only ghosts the item. similar to #674 only this time its the portable crafting mat. I think it functions like the player 2x2 crafting grid which is probably the reason why it laggs. reproduceable but nothing too game breaking. It does lock your player inventory but relogging can solve the issue. I think this is something to do with modded items being unable to be quickly crafted in the player inventory. https://www.youtube.com/watch?v=3iiAObwrMJM
