### ISSUE TITLE
[BUG] Puffbulbs don't spawn at all in the Beneath

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#727]
**Describe the bug**
As the title says, Puffbulbs can't be found in any dimension. 

**To Reproduce**  
1. Go to the Beneath. 
2. Search endlessly for Puffbulbs. 
3. Realize that they don't exist in 3.0. 

**Expected behavior**
I expect Puffbulbs to spawn in the Beneath as the JEI description describes. 

**Screenshots**
![image](https://user-images.githubusercontent.com/50285548/113641219-12a0ee80-9632-11eb-8aa3-d706a613b1f1.png)

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [X] 3.0 BETA 4
   - [ ] Other: 
 - Server or Singleplayer:
   - [X] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [X] 3.0 BETA 4
   - [ ] Other: 

**Additional context**
Has been an issue since 2.77.5.

**Comment by democat3457** [comment]
this is true, they no longer spawn above viridium

**Comment by KaleThyself** [comment]
Update: Puffbulbs only appear to rarely spawn over UGB Viridium Ore instead of Viridium Veins as well in v.3.1.1a.

**Comment by democat3457** [comment]
Fixed by 15b524a5c52cba129ef1644023e333c56b572768
