### ISSUE TITLE
[BUG] Vanilla crit with greatswords

### ISSUE THREAD

**Issue by wabooski** [Rebirth-of-the-Night/Rebirth-Of-The-Night#728]
**Describe the bug**

At least when using iron & silver greatswords, instead of the 20% critical hit chance, you can get consistent criticals by using vanilla minecraft methods (jumping up, and attacking when you start falling). Haven’t tested using greatswords of other materials, but I would expect results to be similar.
**To Reproduce**  
1. Jump
2. Fall
3. Swing at opponent with greatsword whilst falling 
4. You should get a critical hit
**Expected behavior**

Every 1/5 hits should be criticals, and you should not be able to get consistent critical hits using vanilla minecraft methods.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [ | ] 3.0 BETA 4
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [ | ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [ | ] 3.0 BETA 4
   - [ ] Other: 

**Additional context**

**Comment by democat3457** [comment]
Caused by the same thing as https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/62, relevant issue being https://github.com/SanAndreasP/BetterCombatRebirth/issues/21

**Comment by InkyWasTaken** [comment]
It goes for almost half the weapons in the mod too.
