### ISSUE TITLE
[BUG] Different Coral Generating

### ISSUE THREAD

**Issue by syelents** [Rebirth-of-the-Night/Rebirth-Of-The-Night#73]
**Describe the bug**
Coral found from the world is from the Biomes o' Plenty mod, but when searched for in JEI, Only coral from the CoralReef mod appears. There seems to be no way to get the CoralReef mod's Coral, which can be used as a dye substitute 

**To Reproduce**
Locate any coral reef.

**Expected behavior**
Coral from the CoralReef mod should have generated.

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Both
 - Version the world was created on: 2.76.1

**Comment by CalaMariGold** [comment]
We'll look into this, but don't want to touch oceans too much until 2.8.

**Comment by democat3457** [comment]
CoralReef begone!
