### ISSUE TITLE
[BUG] I'm keeping my inventory after death

### ISSUE THREAD

**Issue by FaustSchlag** [Rebirth-of-the-Night/Rebirth-Of-The-Night#731]
Hello,
How can I disable keep inventory after death?  /gamerule keepInventory false does not work.

**Comment by CalaMariGold** [comment]
On 2.77.5, you keep your hotbar and armor. It's intended as part of game design. You can disable it by going through the config for Corpse Complex.

For the future, please use the GitHub template provided.
