### ISSUE TITLE
[CRASH] Right clicking Cincinnasite Pots with a Fire Lily crashes the game

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#734]
**Describe the crash**
When a player attempts to interact with a Cincinnasite Pot from betternether using a Fire Lily from Ice and Fire, the game instantly crashes.

**To Reproduce**  
1. Place down a Cincinnasite Pot. 
2. Right click it with a Fire Lily. 

**Crash Log**
[crash-2021-04-13_17.49.53-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6307488/crash-2021-04-13_17.49.53-client.txt)

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [X] 3.0 BETA 4
   - [ ] Other: 
 - Server or Singleplayer:
   - [X] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [X] 3.0 BETA 4
   - [ ] Other: 

**Additional context**
Only tested with the Fire Lily.

**Comment by democat3457** [comment]
Fixed next beta with BetterNether fork.
