### ISSUE TITLE
[BUG] Stonelings from Quark spawn underground before any major progression

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#736]
**Describe the bug**
I found two Stonelings underground while mining after getting the Gearing Up! progression stage of full metal armor. I happened to get lucky and got 1 heart of diamond. 

**To Reproduce**  
1. Search underground for Stonelings during an early progression stage. 

**Expected behavior**
I expect Stonelings to not spawn that early as they have a chance to drop hearts of diamond which can be hammered into heart crystal shards. 

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [X] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
This is on a fresh 3.0 Beta 5 server using the most recent server pack update uploaded after 21:42 PST.

**Comment by CalaMariGold** [comment]
That heart crystal shard recipe should be removed. Other than that, this is intended.
