### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sakkezboi** [Rebirth-of-the-Night/Rebirth-Of-The-Night#739]
**Describe the bug**
 when placed a coade stone slab is placed half a block above ground its hardness is refined, but when the same slab is place on the ground its hardness is sturdy

**To Reproduce**  
place a coade stone slab half a block above ground

**Expected behavior**
It will have hardness value of refined

**Screenshots**
![image](https://user-images.githubusercontent.com/80770973/115567308-ce654d80-a2c3-11eb-8c3b-6eb1fc435945.png)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
fix came

**Comment by democat3457** [comment]
#546
