### ISSUE TITLE
[BUG] Beta 5, Mac, Patchouli Guidebook texture missing

### ISSUE THREAD

**Issue by darchitectlp** [Rebirth-of-the-Night/Rebirth-Of-The-Night#741]
**Describe the bug**
Getting a missing texture for the Guidebook background

**To Reproduce**  
Open the Guidebook from the inventory screen

**Expected behavior**
Be able to read the guidebook over a neutral texture

**Screenshots**
https://imgur.com/a/SCmT5lW

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [ X] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [X ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [X ] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
Tried redownloading Patchouli; didn't fix it. Also tried making sure the png wasn't corrupt in 
Rebirth of the Night Beta 5 (1.12)/minecraft/resources/rotn/textures
Looked fine.

**Comment by democat3457** [comment]
possibly fixed in next beta

**Comment by darchitectlp** [comment]
Can you close this? I did a completely fresh install this morning, and it's working flawlessly now. Thanks!
