### ISSUE TITLE
[CRASH] Right-click harvest with nether wart crash

### ISSUE THREAD

**Issue by iEatShadows** [Rebirth-of-the-Night/Rebirth-Of-The-Night#742]
**Describe the crash**
When I try to mount my hippogriff, I get a sudden crash. happened twice already. (inconsistent)

**To Reproduce**  
 Tame a hippogriff and ride it.

**Crash Log**
[crash-2021-04-26_18.43.45-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6380995/crash-2021-04-26_18.43.45-client.txt)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other:

**Comment by democat3457** [comment]
@iEatShadows did you right-click on (or were anywhere near) nether wart

**Comment by iEatShadows** [comment]
> @iEatShadows did you right-click on (or were anywhere near) nether wart

yea

**Comment by iEatShadows** [comment]
> @iEatShadows did you right-click on (or were anywhere near) nether wart
yep can confirm, its right clicking the nether wart while trying to mount.

**Comment by democat3457** [comment]
If you right-click nether wart without trying to mount, does it still produce the crash

**Comment by democat3457** [comment]
so it's not related to mounting then?

**Comment by KaleThyself** [comment]
> 
> 
> so it's not related to mounting then?

I can replicate the same issue of right click harvesting nether wart without a hippogryph causing an instant crash on the Beta 5 server pack. 

(logs) 
[crash-2021-04-26_18.24.53-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6382344/crash-2021-04-26_18.24.53-client.txt)

**Comment by democat3457** [comment]
Rebirth-of-the-Night/Quark#4

**Comment by democat3457** [comment]
Will be fixed in beta 6
