### ISSUE TITLE
Ice Dragon - Dragon Horn Not Working - BETA 5

### ISSUE THREAD

**Issue by HamartiaCodex** [Rebirth-of-the-Night/Rebirth-Of-The-Night#744]
**When you hatch an ice dragon:**

1.  When you right click to pick it up and move to a different location to set it down, when you set it down it teleports back to the location it hatched from.

2.  When you attempt to use the Dragon Horn to transport an Ice Dragon:

-  it goes into the horn but never comes out. The horn in your hot bar becomes empty, and appears empty in your inventory, but when you move it to another slot in your inventory it appears full again but still will not release the dragon.

**Tests already taken:**

1. Attempted all issues with Fire Dragons and have not had any issues.

2. Attempted to recreate in both single player and a fresh install of the modpack; problem still persists. 

3. Attempted in Beta 4, Issue still persists

4. Attempted in a different modpack containing Ice and Fire; worked in seperate modpack but was using an updated version of Ice and Fire

**Comment by democat3457** [comment]
when you say updated version, you must mean that the modpack is on a different mc version since we have the latest, right?

**Comment by HamartiaCodex** [comment]
> when you say updated version, you must mean that the modpack is on a different mc version since we have the latest, right?

If I'm not mistaken, the other modpack ( Which was All The Mods 6, Version 1.5.4b ) uses an updated version of both minecraft and the Ice and Fire mod.

ROTN (3.0 Beta 5) uses Ice and Fire version 1.9.1-1.12.2   while  All The Mods uses 2.1.6-1.16.4


[All The Mods - Mod List](https://imgur.com/a/IbEI3DK)


[Rebirth of The Night - Mod List](https://imgur.com/a/uFhCtBV)

**Comment by democat3457** [comment]
ye so then theyre completely different, cant really compare

**Comment by HamartiaCodex** [comment]
> ye so then theyre completely different, cant really compare

Fair enough, the bug still is a problem. The only thing that myself and those on the server I play on have done that "works" is to restart the server every time, even then only 1 ice dragon can be released from a horn on the server before it breaks again and requires another restart to release another ice dragon.

**Comment by KaleThyself** [comment]
To my knowledge, the dragon horn recipe has been disabled (with a tooltip warning the player to not use it) as it appears to be a lost cause for the time being.
