### ISSUE TITLE
invasion bug when it starts while you are in a bed

### ISSUE THREAD

**Issue by elipol02** [Rebirth-of-the-Night/Rebirth-Of-The-Night#750]
**Describe the bug**
I slept in a bed and when I woke up in the morning an invasion started. I killed some of the mobs, but the invasion bar has remained for multiple days, I am unable to sleep, and the monster glow effect disappeared after the first day so I cannot find the mobs to kill.

**To Reproduce**  
sleep right before an invasion is about to start
**Expected behavior**

the invasion announcement should happen before you are able to sleep and the game should stop you from sleeping.
**Screenshots**

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

This was the second invasion in the world

**Comment by democat3457** [comment]
@SekretOne

**Comment by KaleThyself** [comment]
Invasions will now instantly teleport the player, so it will displace them from being able to sleep in their bed anyways the moment night comes. Thus, this issue may be closed.
