### ISSUE TITLE
[BUG] Can't tame rats

### ISSUE THREAD

**Issue by thos-grol** [Rebirth-of-the-Night/Rebirth-Of-The-Night#751]
**Describe the bug**
Can't tame rats with cheese chunks. Found out when I tried to tame pied piper rats after trapping them in a pit and then double jumping out, killing the piper, and then coming back to tame. Killed them and then summoned rats to test. It didnt work either. ROTN does something weird to the ai.

**To Reproduce**  
Above

**Expected behavior**

Tame rats.

**Screenshots**

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [X ] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [ X] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [ X] 3.0 BETA 5
   - [ ] Other:

**Comment by OblivionHeart** [comment]
I have the same issue, I also tried to put the cheese in a rat trap and that worked fine so idk why the rats arent taming
