### ISSUE TITLE
Stymphalian arrows dupe (maybe all kinds of arrows too idk)

### ISSUE THREAD

**Issue by z57333** [Rebirth-of-the-Night/Rebirth-Of-The-Night#754]
When I was playing, I was testing out stymphalian arrows, shooting them on the wall, etc. Then I noticed the number of arrows I had (originally 12) was going up, to 13, 14, then 15. It was weird and it didn't happen every time I picked up the arrows again. Weird bug, very beneficial. Just asking for this to be reported and aware of.

**Comment by democat3457** [comment]
What bow (and enchants?), what version, and did you have any potion effects?

**Comment by z57333** [comment]
And no, I did not have any potion effects from anything except the well fed effect because I was eating some steak.

**Comment by democat3457** [comment]
Is this effect replicable with a different bow (different material)?

**Comment by z57333** [comment]
I haven't tried it, as I'm afraid that the server admin will ban me if I do
this again, and he and I are already on not-so-good terms. But, I will get
back to you once I have tested it in singleplayer. Also, the server admin
sees everything on the aternos console, so yeah... he's been keeping an eye
out on not so ordinary things.

**Comment by KaleThyself** [comment]
Presumably a duplicate of #857; may close due to not enough info/invalid post.

**Comment by democat3457** [comment]
not a duplicate as the bow does not have Back to the Chamber, supposedly

**Comment by democat3457** [comment]
however, yea this does have an invalid format and is also very old
