### ISSUE TITLE
[BUG] Invasion mobs don't spawn in nether

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#756]
**Describe the bug**

Being in the nether during before the invasion starts will prevent you from leaving the dimension and will oddly spawn a few zombie horses on you. This is fixed via the `/ostop [<player>]` command. 

**To Reproduce**  
1. Wait for invasion day. 
2. Enter the nether or any dimension during invasion day. 
3. Stay in the nether past the time when the invasion starts. 
4. You will not be tp'd out, nor will you be able to leave the nether during the invasion. 
5. The invasion is then prolonged infinitely since you cannot kill the invasion mobs to end the invasion without `/ostop [<player>]`

**Expected behavior**

I expect the invasion to teleport you out of the nether. 

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [X] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other:

**Comment by democat3457** [comment]
New invasion mod mechanics mean dimension-specific invasions. The current (and planned) invasions shouldn't teleport you out of the player. The actual bug is that mobs don't seem to spawn correctly during that invasion.

**Comment by KaleThyself** [comment]
Invasions now teleport the player anyways, so this issue is now irrelevant.
