### ISSUE TITLE
[BUG] Magnetism Duplicates Items

### ISSUE THREAD

**Issue by dot-shark** [Rebirth-of-the-Night/Rebirth-Of-The-Night#757]
**Describe the bug**
The potion of magnetism duplicates dropped items.

**To Reproduce**  
1. Drink a Potion of Magnetism I
2. Drop an item on the floor roughly 2-3 blocks away (works more consistently with multiple items)
3. Wait a few seconds until magnetism picks the item up
4. The item(s) will have duplicated

**Expected behavior**
Magnetism will pick up the item from a greater range.

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
Blocks that pop out items such as millstones and filtered hoppers will also achieve the same effect, though dropping an item on the ground also works. It does not seem to work with Magnetism II. I have tested in both a server an in singleplayer, and can confirm it works for both.

**Comment by democat3457** [comment]
Holy cow I can reproduce this on dev

**Comment by democat3457** [comment]
Fixed by 9308033b021f5d3f753c6f7a3288cb2268939f1f (removing magnetism)

**Comment by KaleThyself** [comment]
Magnetism was not removed. It's still in the loot table of underground chests, and even worse, you can still craft the potion ring of magnetism. Thus, infinite duping will never run out as long as you have exp.

**Comment by TheNelston** [comment]
how do we remove this from loot tables?

**Comment by iEatShadows** [comment]
its hella broken once you get one. now what if you have 2? gg.

**Comment by KaleThyself** [comment]
Potion of magnetism presumably no longer spawns at all, nor is it craftable into a potion ring in v.3.1.1a. This issue may be closed until they somehow decide to appear again in an obscure loot table.
