### ISSUE TITLE
[BUG] plague inconsistencies

### ISSUE THREAD

**Issue by Exzavion** [Rebirth-of-the-Night/Rebirth-Of-The-Night#761]
**Describe the bug**

**To Reproduce**  
Steps to reproduce the behavior:Get hit by any monster with plague. Most common ones to get hit by with a little to no counterplay is plague rats ( the small kind ) as well as plagued corrupted enderman.

**Expected behavior**
 Sometimes you will get plague 3 and be able to live, other times you get plague 4 instantly and just die and nothing can save you.

**Screenshots**
 I would but its always a death screen.

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [ x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [x ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [ x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

**Comment by KaleThyself** [comment]
Plague seems to be fairly consistent in v.3.1.1a, and doesn't appear to progress at all through stages anymore. Is something broken with the plague scripts or was it overall nerfed compared to 3.0 B5?
![image](https://user-images.githubusercontent.com/50285548/179603752-e5a61d1d-33e7-4b3c-95e1-3a9d76d42e33.png)

**Comment by democat3457** [comment]
thats good, was probably fixed at some point in the rats mod
