### ISSUE TITLE
[BUG] Curseforge Launcher still points to Patreon

### ISSUE THREAD

**Issue by Seth0067** [Rebirth-of-the-Night/Rebirth-Of-The-Night#762]
**Describe the bug**
On the update version window, the patreon URL is still listed, leading to a 404 web page

**To Reproduce**  
go to Curseforge, RotN. Click the button on the profile that allows you to change versions.  Note the patreon URL on the pop-up .

**Expected behavior**
Since the Patreon was deactivated after CMG's departure, the Patreon links should be removed.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/22122348/119060979-49905100-b9a1-11eb-9213-24e96f87ca08.PNG)

**Info (please complete the following information):**

 - Modpack Version:
(all)

 - Server or Singleplayer:
n/a

 - Version the world was created on:
n/a

**Additional context**
n/a

**Comment by democat3457** [comment]
fixed

**Comment by democat3457** [comment]
also removed merch store links (since proceeds now go to rotn sa instead of modpack)
