### ISSUE TITLE
[BUG] Flimsy buckets are not consumed in recipes that would have consumed a normal bucket

### ISSUE THREAD

**Issue by SylvanasIII** [Rebirth-of-the-Night/Rebirth-Of-The-Night#763]
**Describe the bug**
Making many things (e.g., any piece of either type of alchemic condenser, cooking cauldron, quality bucket) with a flimsy bucket does not consume the bucket.

**To Reproduce**  
Craft something with a flimsy bucket, such as one of the above listed items.

**Expected behavior**
The flimsy bucket is consumed by the recipe.

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
 
 - Server or Singleplayer:
   - [ ] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5

**Comment by democat3457** [comment]
Fixed in beta 6
