### ISSUE TITLE
[BUG] Huge Fps drop when looking at another player

### ISSUE THREAD

**Issue by Marrynd** [Rebirth-of-the-Night/Rebirth-Of-The-Night#767]
**Describe the bug**
Huge Fps drop when looking at another player

**To Reproduce**  
looking at another player general direction, this happens through wall

**Expected behavior**
FPS drop from 120 to 30

**Screenshots**
-

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [x ] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ x] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x ] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
i did install other mod ,![image](https://user-images.githubusercontent.com/84743599/119849674-069d2300-bf37-11eb-8c74-c595cf96e66f.png)
3 player server
Reinstalling the whole thing seem to fix the problem for a while

**Comment by democat3457** [comment]
thats a lot of other mods. unfortunately we cannot and will not support altered modpack installations

**Comment by Marrynd** [comment]
understandable, thanks

**Comment by Marrynd** [comment]
Found a fix, Waila is causing this problem @democat3457 this info might help you somehow.

**Comment by democat3457** [comment]
hmm thanks, one of the mods you added probably gave a bunch of stuff to the player waila

**Comment by Marrynd** [comment]
ok, after playing for a few hours the problem came back, deleting waila only help for a few hours for some unknown reason lmao

**Comment by Marrynd** [comment]
@democat3457 Alright for real this time, it electroblob's wizardry. this have nothing to do with Waila
after a lot of testing by disabling every mod one by one i notice that electroblob is causing the fps drop
Changing this config "B:spellcastingAnimations." from true to false resolves the problem.
I hope this info is useful for you in the future.
