### ISSUE TITLE
[BUG] Dual-wielding causes damage buff effects to not work

### ISSUE THREAD

**Issue by DorianZ2** [Rebirth-of-the-Night/Rebirth-Of-The-Night#771]
**Describe the bug**

While dual-wielding melee weapons, the off-hand melee does half the damage and is unaffected by the damage buff effects such as Strength.

**To Reproduce**  
Simply dual-wield any two weapons by grabbing one into your off-hand and try to attack something while paying attention to the damage numbers.

**Expected behavior**

the off-hand melee should do half the original weapon's damage, e.x. if the melee has 8 damage by default, the off-hand one will do only 4, even with Strength effect or other damage buffs, it will still be 4 damage.

**Screenshots**
Main hand viridium sword damage:
![image](https://user-images.githubusercontent.com/85310881/120704168-8d617b00-c4b6-11eb-93c2-cac3d8e6c484.png)

Off-hand viridium sword damage:
![image](https://user-images.githubusercontent.com/85310881/120704508-f648f300-c4b6-11eb-9af4-5079d0f4f5ec.png)

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other:
 - Server or Singleplayer:
   - [ ] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

Nothing else to say.

**Comment by kil0byt3** [comment]
as discussed, offhand 50% damage is intended as part of the mod/not a bug, but potion effects not working is a bug. Mod is abandoned so not sure if we can fix but we can try. https://www.curseforge.com/minecraft/mc-mods/better-combat-rebirth

**Comment by KaleThyself** [comment]
> as discussed, offhand 50% damage is intended as part of the mod/not a bug, but potion effects not working is a bug. Mod is abandoned so not sure if we can fix but we can try. https://www.curseforge.com/minecraft/mc-mods/better-combat-rebirth

In addition, this allows you to swing the weapon at a fixed rate, such as using the ender of worlds sword which has a very long charge up time in the main hand, but is nearly instantaneous to use in the offhand while stil providing the extinction enchantment effect.

**Comment by democat3457** [comment]
related to #62

**Comment by bglandolt** [comment]
https://drive.google.com/file/d/1vBIT-IU3ST0G7Y2P_c_5jUBrOZDoxCfv/view?usp=sharing

lmk if this works for you, I made an update for the mod a few months ago

**Comment by kil0byt3** [comment]
> https://drive.google.com/file/d/1vBIT-IU3ST0G7Y2P_c_5jUBrOZDoxCfv/view?usp=sharing
> 
> lmk if this works for you, I made an update for the mod a few months ago

Cool! However I don't have access: 
![image](https://user-images.githubusercontent.com/39413400/126027864-19e44556-f3fd-45b7-a475-86313f6c14c7.png)
@bglandolt

**Comment by bglandolt** [comment]
rip, i always forget

https://drive.google.com/file/d/1vBIT-IU3ST0G7Y2P_c_5jUBrOZDoxCfv/view?usp=sharing

**Comment by kil0byt3** [comment]
Thanks - we'll test this

**Comment by bglandolt** [comment]
Yeah I fixed:

-the random crit chance
-made it so weapon traits work for that weapon only, so a +30% damage (from quality tools) on your main hand weapon only affects your main hand (it affected offhand in the OG mod unfortunately)
-made it so you can only swing with your offhand/main hand if you have the ‘energy’ for it
-made it so warhammers penetrate the armor attribute (like the armor attribute that gets applied through rough mobs revamped)
-other small tweaks, like making the warhammer rebuff work against mobs, or an option for adding extra damage to the dragbow (it does as much damage as a vanilla bow for some reason?)

I haven’t touched the mod for a few months so idk if everything is working 100%, but yes let me know if that fixes your problem(s)

:)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by democat3457** [comment]
fairly sure this is solved by burgy fork
