### ISSUE TITLE
[CRASH] Attempting to plant a Foliaath causes a small crash

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#775]
**Describe the crash**

Attempting to plant a Foliaath via the Foliaath seed on a dirt block in a loamy grass biome will cause the crash to pop up on the top right of the screen. 

**To Reproduce**  
1. Acquire a Foliaath seed. 
2. Plant it on a piece of vanilla dirt in a loamy dirt biome. 

**Crash Log**

[crash-2021-06-12_18.01.14-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6643115/crash-2021-06-12_18.01.14-client.txt)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [X] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

**Comment by democat3457** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/network/internal/EntitySpawnHandler.java#L87-L89

[debug] either entityid is null or the entity created on line 87 is null

**Comment by KaleThyself** [comment]
This crash does not appear to be replicable in v.3.1.1a anymore.
