### ISSUE TITLE
[CRASH] Elder Guardian kicks you out when killed?

### ISSUE THREAD

**Issue by DorianZ2** [Rebirth-of-the-Night/Rebirth-Of-The-Night#776]
**Describe the crash**
I went to an ocean monument for sponge to tame Hippocampus, while I was looking for Elder Guardians, killing one of them resulted in a sudden crash. I decided to investigate and noticed that it drops an item without a texture that disappears after I got kicked.

**To Reproduce**  
Kill an Elder Guardian, spawned with an egg or naturally.

**Crash Log**

[crash-2021-06-13_22.38.23-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6644617/crash-2021-06-13_22.38.23-client.txt)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

This is a screenshot of an item, you can see it's called "Trident" and it drops from Elder Guardians. After I get kicked, the item is gone:
![image](https://user-images.githubusercontent.com/85310881/121821298-7a119500-cc98-11eb-8ee1-f32dab7939d6.png)

**Comment by democat3457** [comment]
if you hover over the item with f3+h, does it give you the modid of the item, or are you kicked before you can analyze it

**Comment by DorianZ2** [comment]
> if you hover over the item with f3+h, does it give you the modid of the item, or are you kicked before you can analyze it

unfortunately I get kicked as soon as I hover over this item, therefore can't check it's ID

**Comment by democat3457** [comment]
Related to thedarkcolour/Future-MC#253
