### ISSUE TITLE
[BUG] Can't pick up Lunar Water from cauldrons

### ISSUE THREAD

**Issue by DorianZ2** [Rebirth-of-the-Night/Rebirth-Of-The-Night#778]
**Describe the bug**
Apparently the buckets with durability limit on them can not pick up Lunar Water out of the cauldrons.

**To Reproduce**  
Grab any bucket except for Quality one [as these have no durability limit] and attempt to collect Lunar Water from a cauldron

**Expected behavior**
Doing so results in an error and the bucket has a glitched regular water in it (it goes back to empty when trying to use it again and water disappears, which is a common visual bug).

**Screenshots**
![image](https://user-images.githubusercontent.com/85310881/121821866-12f5df80-cc9c-11eb-9b48-c9ded7fb7dda.png)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
Also, upon interacting with the cauldron using Quality bucket first, it then works normally even with other buckets, so be aware when trying to fill cauldrons with Lunar water using Quality buckets, as the bug will not occur this way. I did it by filling the cauldrons up, waiting for the moon to cause purification, combining it with the Lunar quintessence and THEN attempting to harvest it with all bucket types.

Here's a report I got, if necessary:
[crash-2021-06-13_23.06.58-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6644647/crash-2021-06-13_23.06.58-server.txt)

**Comment by democat3457** [comment]
fixed with nyx update
