### ISSUE TITLE
[CRASH] Error spamming in console which leads to a crash

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#779]
**Describe the crash**

The error `[Server thread/WARN] [net.minecraft.entity.EntityTrackerEntry]: Fetching addPacket for removed entity` has been spamming the console of a server I'm in with hundreds of lines. This is most prominent whenever there's a bloodmoon, invasion, or both at the same time. 

**To Reproduce**  
1. Have an invasion or bloodmoon occur on 3.0 Beta 5. 
2. Check console output which shows the errors. 

**Crash Log**

[Not a crash log, but it shows the errors]
[error log.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6658432/error.log.txt)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [X] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

The bug report is vague as I'm unsure what could be causing the issue besides bloated mob spawn rates. In the configs, I've disabled nether cities, lowered meteor spawn rates, and disabled goblin spawning. Server is running on 6GB allocated RAM and has 3-5 players on in the same area.

**Comment by democat3457** [comment]
Do people move around and load/unload chunks during those events? And if people just stay in the same chunk during an event (for testing), does the error still happen as often?

**Comment by KaleThyself** [comment]
> 
> 
> Do people move around and load/unload chunks during those events? And if people just stay in the same chunk during an event (for testing), does the error still happen as often?

Yes to both.

**Comment by fnar** [comment]
What was the fix? Was there a commit which addressed this issue?
