### ISSUE TITLE
[CRASH] Loading into full screen

### ISSUE THREAD

**Issue by DragonesLocos** [Rebirth-of-the-Night/Rebirth-Of-The-Night#781]
**Describe the crash**

**To Reproduce**  
I reboot the game and it loads up to 100% and crashes the moment the window full screens.

**Crash Log**
[crash-2021-07-01_20.40.26-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6751599/crash-2021-07-01_20.40.26-client.txt)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
The only way I can play the game is to uninstall and reinstall it every time.

**Comment by democat3457** [comment]
The window shouldn’t go directly to full screen, maybe that’s the cause of the issue?

**Comment by DragonesLocos** [comment]
I made a short video of what the crash looks like, go to 5:45 to see the crash. https://drive.google.com/file/d/1o3KJ_lPvSoR6OJHUY9pinPwtjoPPvijJ/view?usp=sharing
The only additions I made to the game are Journeymap-1.12.2-5.7.0 and the Sildurs Vibrant Shaders v1.29 Medium.

**Comment by democat3457** [comment]
Does it still crash without Journeymap and Sildurs Vibrant?

**Comment by DragonesLocos** [comment]
Yes it does.

**Comment by democat3457** [comment]
Have you tried reinstalling? Also, have you changed any configs pertaining with full screen mode or anything similar?

**Comment by DragonesLocos** [comment]
Every time I reinstall it, it works the first time then has the same error after I quit and start it up again. When it works the first time I always hit F11 to go into full screen but other then that I do not change anything else.

**Comment by democat3457** [comment]
Before quitting the game on the first load, try exiting out of full screen first- the game is remembering your full screen mode but I guess some mods need an actual window on startup

**Comment by DragonesLocos** [comment]
Thank you that actually worked sorry for the late reply. Thanks for the help.
