### ISSUE TITLE
[BUG] Some main menu messages are pretty weird

### ISSUE THREAD

**Issue by HUJEC17** [Rebirth-of-the-Night/Rebirth-Of-The-Night#784]
**Describe the bug**
From time to time when my son starts up the game, some politically affiliated messages pop up in the main menu.

**To Reproduce**  
You just need to start up the game, it will appear from time to time.

**Expected behavior**
I suppose there should be a way to turn it off, I really don't want my kid get into politics this young. Minecraft's playerbase is pretty young after all.

**Screenshots**
![1](https://user-images.githubusercontent.com/87401451/125545278-8e001f72-051e-4b4e-8e97-bf1bfff1fe5d.jpg)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [X] Server
   - [X] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

**Comment by KaleThyself** [comment]
Hello, if you would like to delete certain Message of the Day texts, the folder they reside in is: 
`Rebirth-of-the-Night-3.0-BETA-5\minecraft\oresources\minecraft\texts\splashes` 

The text file has a plain .txt list of different splash MOTD's that can be shown at random on the main menu screen.

**Comment by democat3457** [comment]
Understandable. That particular message is because our previous lead developer was trans, and we wanted to get the word out, but I can see how that would provoke certain conversations. As stated above by Kale, you can delete those messages from the splash config, but this isn’t really an issue in the broad sense, so I’ll close this.
