### ISSUE TITLE
[BUG] creative pick block button giving the incorrect slabs

### ISSUE THREAD

**Issue by DIVIDERE** [Rebirth-of-the-Night/Rebirth-Of-The-Night#785]
**Describe the bug**
in creative when using the pick block button both the andesite brick and cobble slabs give quartzite slabs instead.

**To Reproduce**  
1: place down an andesite brick or cobble slab in creative
2: use the pick block button (whatever you have it bound to)
3: a quartzite slab will appear in your hotbar

**Expected behavior**

the correct slabs should be given

**Screenshots**

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

**Comment by democat3457** [comment]
stick this issue as a comment on the end of #362 kthx
