### ISSUE TITLE
[CRASH] when using openJDK 

### ISSUE THREAD

**Issue by Melodycloudu** [Rebirth-of-the-Night/Rebirth-Of-The-Night#786]
**Describe the crash**
just a launch crash (using openJDK) 

**To Reproduce**  
using openjdk 11?

**Crash Log**
MultiMC version: 0.6.12-1530

Minecraft folder is:
C:/Users/<username>/Documents/MultiMC/instances/Rebirth of the Night (RotN)/minecraft

Java path is:
C:/Program Files/AdoptOpenJDK/jdk-11.0.11.9-openj9/bin/javaw.exe

Checking Java version...
Java is version 11.0.11, using 64-bit architecture, from AdoptOpenJDK.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/<username>/Documents/MultiMC/instances/Rebirth of the Night (RotN)/natives

Mods:
  [📁] 1.12 (folder)
  [✔️] aactadapter-1.12.2-0.1.0
  [✔️] AdvancedLiftingMethods-1.12.2-1.0.0
  [✔️] aeble_v1.4.0
  [✔️] aether_continuation-1.12.2-v1.2.3
  [✔️] aether_legacy-1.12.2-v1.4.4
  [✔️] AIImprovements-1.12-0.0.1b3
  [✔️] animania-1.12.2-1.7.3
  [✔️] antighost-1.12-forge14.21.1.2387-1.1.1
  [✔️] antiqueatlas-1.12.2-4.6.3
  [✔️] anvilpatch-1.0.0
  [✔️] AppleCore-mc1.12.2-3.4.0
  [✔️] AppleSkin-mc1.12-1.0.9
  [✔️] arcanearchives-0.2.0.19
  [✔️] athenaeum-1.12.2-1.18.1
  [✔️] ATOP-1.12.2-v.1.5
  [✔️] AttributeFix-1.12.2-1.0.4
  [✔️] AutoRegLib-1.3-32
  [✔️] base-1.12.2-3.13.0
  [✔️] Baubles-1.12-1.5.2
  [✔️] Better With Addons-0.51
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] betteranimals-5.2.1
  [✔️] betteranimalsplus-1.12.2-9.0.1
  [✔️] bettercaves-1.12.2-1.6.0
  [✔️] BetterCombat-1.12.2-1.5.6
  [✔️] BetterFps-1.4.8
  [✔️] betterhud-1.12.2-1.4.1
  [✔️] betternether-0.1.8.6
  [✔️] BetterWithLib-1.12-1.5
  [✔️] BetterWithMods-1.12-2.3.23
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2444-universal
  [✔️] BiomeTweaker-1.12.2-3.2.354
  [✔️] BlockDropsTweaker-1.12.2-2.4
  [✔️] Blur-1.0.4-14
  [✔️] BNBGamingCore-1.12.2-0.11.0
  [✔️] BNBGamingLib-1.12.2-2.17.6
  [✔️] Bookshelf-1.12.2-2.3.590
  [✔️] Born In A Barn V1.8-1.12-1.1
  [✔️] Bountiful Baubles-1.12.2-0.1.6
  [✔️] Bountiful-2.2.2
  [✔️] CarryOn MC1.12.2 v1.12.3
  [✔️] CD4017BE_lib-1.12.2-6.4.18
  [✔️] Charm-1.12.2-1.3.7
  [✔️] Charset-Lib-0.5.6.4
  [✔️] Charset-StorageChests-0.5.6.0
  [✔️] cherishedworlds-1.12.2-1.0.1
  [✔️] ChunkAnimator-MC1.12-1.2
  [✔️] chutes-1.12.2-1.0.0
  [✔️] Clumps-3.1.2
  [✔️] ColouredTooltips-1.12.2-1.0.9
  [✔️] ContentTweaker-1.12.2-4.9.1
  [✔️] Controlled Burn-1.12.2.020
  [✔️] Controlling-3.0.9
  [✔️] copypaste-1.1
  [✔️] CoralReef-2.5-1.12.2
  [✔️] coroutil-1.12.1-1.2.37
  [✔️] corpsecomplex-1.12.2-1.0.10.1
  [✔️] CosmeticArmorReworked-1.12.2-v5a
  [✔️] CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
  [✔️] CraftTweaker2-1.12-4.1.20.576
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] CustomLoadingScreen-1.12.2-1.4.1
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] Cyclic-1.12.2-1.20.2
  [✔️] davincisvessels-1.12-6.340-full
  [✔️] DefaultOptions_1.12.2-9.2.8
  [✔️] diethopper-1.1
  [✔️] discordrpc-1.3.3-1.12
  [✔️] disenchanter-[1.12]1.6
  [✔️] DoggyTalents-1.12.2-1.15.1.5
  [✔️] dropt-1.12.2-1.18.0
  [✔️] DungeonTactics-1.12.2-0.16.6
  [✔️] DynamicSurroundings-1.12.2-3.6.1.0
  [✔️] DynamicTrees-1.12.2-0.9.8
  [✔️] DynamicTreesBOP-1.12.2-1.4.1e
  [✔️] DynamicTreesPHC-1.12.2-1.4.2
  [✔️] eguilib-0.1.2
  [✔️] EnchantingPlus-1.12.2-5.0.176
  [✔️] enchcontrol-1.12.2-1.1.5-0
  [✔️] EndReborn III [0.3.7]
  [✔️] EpicSiegeMod-13.168
  [✔️] EquipmentTooltips-1.12.2-1.0.3-4
  [✔️] ExtendedDays-1.12.2-0.2.9-28
  [✔️] extraalchemy-forge-1.12-build11-0.5.4
  [✔️] ExtraGolems-1.12-7.1.9
  [✔️] fairylights-2.1.10-1.12.2
  [✔️] FantasticLib-1.12.2.034
  [✔️] FastFurnace-1.12.2-1.3.1
  [✔️] FastWorkbench-1.12.2-1.7.3
  [✔️] Fishs_Undead_Rising-1.0.13
  [✔️] foamfix-0.10.10-1.12.2
  [✔️] Forgelin-1.8.4
  [✔️] FpsReducer-mc1.12.2-1.15
  [✔️] FullscreenWindowed-1.12-1.6.0
  [✔️] future-mc-0.1.13
  [✔️] fxcontrol-1.12-0.1.14
  [✔️] GameStages-1.12.2-2.0.123
  [✔️] GeographiCraft-1.12-0.8.9b
  [✔️] GlareTorch_Ver.8.11_[MC1.12](forge-1.12-14.21.1.2387)
  [✔️] grapplemod-v11.1-1.12.2
  [✔️] HardcoreDarkness-MC1.12.2-2.0
  [✔️] HelpFixer-1.12.1-1.5.18
  [✔️] hostileworlds_invasions-1.12.1-1.1.13
  [✔️] HungerOverhaul-1.12.2-1.3.3.jenkins148
  [✔️] HungerTweaker-1.12.2-1.3.0
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] iceandfire-1.8.4
  [✔️] ido-1.12.2-1.1.0
  [✔️] incontrol-1.12-3.9.16
  [✔️] InventoryTweaks-1.63
  [✔️] itlt-1.12.2-1.0.2
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] jei_1.12.2-4.15.0.293
  [✔️] JEIHider-1.1c
  [✔️] just-enough-harvestcraft-1.12.2-1.7.0
  [✔️] KleeSlabs_1.12.2-5.4.12
  [✔️] LetMeSleep-v1.2.1-1.12.2
  [✔️] LibraryEx-1.12.2-1.1.3
  [✔️] living_enchantment-3.2.1
  [✔️] llibrary-1.7.19-1.12.2
  [✔️] logimmune-0.1
  [✔️] LootTableTweaker-1.12.2-1.1.14
  [✔️] LootTweaker-0.1.7+MC1.12.2
  [✔️] MagmaMonsters-0.3.0
  [✔️] materialchanger1.0.3-1.12.2
  [✔️] mcw-bridges-1.0.4-mc1.12.2
  [📁] memory_repo (folder)
  [✔️] minerva-library-1.0.13
  [✔️] MineTraps-1.12.2-(v.1.0.4)
  [✔️] MmmMmmMmmMmm-1.12-1.14
  [✔️] MobStages-1.12.2-2.0.13
  [✔️] Modpack Configuration Checker-1.12.2-v1.9.0
  [✔️] modtweaker-4.0.18
  [✔️] morepaintings-paintings-1.12.2-5.0.1.2
  [✔️] MoreSwordsLegacy-1.12.2-1.0.7
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] movingworld-1.12-6.342-full
  [✔️] mowziesmobs-1.5.5
  [✔️] MTLib-3.0.6
  [✔️] multimob-1.0.5
  [✔️] MultithreadedNoise-1.12.2-0.0.2
  [✔️] mysticallib-1.12.2-1.7.0
  [✔️] NamePain-1.12.x-1.2.1
  [✔️] Neat 1.4-17
  [✔️] netherchest-1.1.1
  [✔️] NetherEx-1.12.2-2.1.7
  [✔️] NetherPortalFix_1.12.1-5.3.17
  [✔️] Nyx-1.3.0
  [✔️] OreLib-1.12.2-3.6.0.1
  [✔️] OreSpawn-1.12-3.3.1.179
  [✔️] Pam's HarvestCraft 1.12.2zg
  [✔️] Patchouli-1.0-20
  [✔️] phosphor-1.12.2-0.2.6+build50-universal
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] PotionCore-1.9_for_1.12.2
  [✔️] primitivemobs-1.2.3a
  [✔️] ProportionalDestructionParticles-1.12.2-1.2.4
  [✔️] pyrotech-1.12.2-1.4.29
  [✔️] QualityTools-1.0.7_for_1.12.2
  [✔️] QuarkOddities-1.12.2
  [✔️] Quark-r1.6-179
  [✔️] randomenchants-0.1.4a
  [✔️] randompatches-1.12.2-1.21.0.3
  [✔️] rats-3.2.6
  [✔️] reauth-3.6.0
  [✔️] rebind-1.12.2-2.7.5-0
  [✔️] Redstone++ ver1.3e
  [✔️] redstonepaste-mc1.12-1.7.5
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] Rex's-Additional-Structures-1.12.x-(v.2.3.1)
  [✔️] rockytweaks-1.12.2-0.6.0-PRE-RELEASE-3
  [✔️] RoguelikeDungeons-1.12.2-1.8.0
  [✔️] roughmobsrevamped-1.12.2-2.3.16
  [✔️] Ruins-1.12.2
  [✔️] rustic-1.1.2
  [✔️] rusticbopwoods-1.0
  [✔️] savemystronghold-1.12.2-1.0.0
  [✔️] ScalingHealth-1.12.2-1.3.42+147
  [✔️] ScreenshotToClipboard-1.12.2-1.0.1
  [✔️] SereneSeasons-1.12.2-1.2.18-universal
  [✔️] SetBonus-1.12.2.019
  [✔️] SilentLib-1.12.2-3.0.14+168
  [✔️] simplecore-1.12.2-1.7.3.4
  [✔️] simpleores-1.12.2-1.11.2.2
  [✔️] SmoothFont-mc1.12.2-2.1.2
  [✔️] SoundFilters-0.12_for_1.12
  [✔️] spartancompat-1.2.2
  [✔️] spartanfire-0.07
  [✔️] SpartanShields-1.12.2-1.5.4
  [✔️] SpartanWeaponry-1.12.2-beta-1.3.8
  [✔️] specialai-1.1.0_for_mc1.12.2
  [✔️] specialmobs-1.0.2_for_mc1.12.2
  [✔️] stg-1.12.2-1.2.3
  [✔️] stygian-1.0.4
  [✔️] Surge-1.12.2-2.0.79
  [✔️] TexFix V-1.12-4.0
  [✔️] The Beneath-1.12.2-1.7.0
  [✔️] Tips-1.12.2-1.0.7
  [✔️] Toast Control-1.12.2-1.8.1
  [✔️] ToolBelt-1.12.2-1.9.12
  [✔️] toolprogression-1.12.2-1.6.9
  [✔️] toroquest-1.12.2-5.3
  [✔️] totemexpansion-1.2.2-1.12.2
  [✔️] TrashSlot_1.12.2-8.4.10
  [✔️] Triumph-1.12.2-3.19.2
  [✔️] trumpetskeleton-1.12-1.0.2.1
  [✔️] twilightforest-1.12.2-3.10.1013-universal
  [✔️] UndergroundBiomesConstructs-1.12-1.3.8
  [✔️] unloader-1.2.0
  [✔️] vanillaanvilrepair-1.1
  [✔️] VanillaFix-1.0.10-150
  [✔️] VerticallyStackedDimensions-1.12.2-0.1.9
  [✔️] VillageNames-1.12.2-3.3.1
  [✔️] VillagerTrades-1.12-0.6.4
  [✔️] Void-Fog-1.1.3
  [✔️] wards-1.3.1
  [✔️] WaterControlExtreme-1.0.2
  [✔️] weakerspwbs_1.12-1.3
  [✔️] zombie_players-1.12.1-1.2.7
  [✔️] zombieawareness-1.12.1-1.11.16

Params:
  --username  --version MultiMC5 --gameDir C:/Users/<username>/Documents/MultiMC/instances/Rebirth of the Night (RotN)/minecraft --assetsDir C:/Users/<username>/Documents/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms128m, -Xmx12222m, -Duser.language=en]

Minecraft process ID: 6800

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: jdk.internal.loader.ClassLoaders$AppClassLoader incompatible with java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.
Clipboard copy at: 15 Jul 2021 04:08:29 +0100
Clipboard copy at: 15 Jul 2021 04:08:59 +0100

   - [ X] 2.77.5

**Comment by democat3457** [comment]
you need java 8

**Comment by democat3457** [comment]
also updated the wiki installation page to show the java 8 requirement
