### ISSUE TITLE
[BUG] Transposition enchant does not work 

### ISSUE THREAD

**Issue by MeechIsPurple** [Rebirth-of-the-Night/Rebirth-Of-The-Night#788]
I got a mythril bow and it had transposition when i first crafted it, but i tried testing it out and the arrows domt even do damage nor do I trade places with the target.     

steps to reproduce would be to try to use transposition on any bow.

**Expected behavior**
I expected the bow to do damage and then teleport me to the targets position and the target would be at my old position.

**Screenshots**

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5 x
   - [ ] 3.0
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server x
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5 x
   - [ ] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

**Comment by democat3457** [comment]
mythril bow enchantments are bugged, not even supposed to get transposition in the first place...
fixed in 3.0
