### ISSUE TITLE
[BUG] Floating Roots

### ISSUE THREAD

**Issue by RomeRake51** [Rebirth-of-the-Night/Rebirth-Of-The-Night#792]
**Describe the bug**

Sometimes cave roots spawn in mid-air

**To Reproduce**  
Look inside a cave

**Expected behavior**

for the roots to be placed properly on a block and not just in the air

**Screenshots**

![image](https://user-images.githubusercontent.com/88627259/128722882-279673a1-d103-465e-b561-aba2ab71f0eb.png)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

Might not be fixable? Never had this happen personally with the cave generation mod.

**Comment by Foreck1** [comment]
This situation is extremely common and I'm pretty sure it has nothing to do with Quark itself. The most likely culprit is a mix of Cave Generator's custom carvers + Quark detection of air in caves. I'm inclined to say the most feasible "fix" is to remove their generation mod-wise and add it back in using either CG or COFH.

**Comment by democat3457** [comment]
Is this fixed with the resolution of https://github.com/Rebirth-of-the-Night/Quark/issues/4 ?

**Comment by democat3457** [comment]
Fixed in v3.0.0
