### ISSUE TITLE
Crops dissappearing randomly from tilled soil. 

### ISSUE THREAD

**Issue by mpmdw** [Rebirth-of-the-Night/Rebirth-Of-The-Night#794]
Happens in beta 5 3.0. Running a server config via a hosting site. Crops will randomly disappear from tilled soil. Proper season or not, at least wheat, carrots, and melons all have disappeared.

**Comment by democat3457** [comment]
eeeeeee follow the template
but since you at least provided the version i'll keep it open

**Comment by democat3457** [comment]
does the tilled soil have water around it

**Comment by mpmdw** [comment]
Yes, all around. Basically middle of a lake like about a 2x10 set of tilled soil water all sides.  The disappearing does not seem to happen if the tilled soil is underground at least it hasn't yet. Happened pretty quick and consistently with crops above ground. Can't get any consistency. Using a server too so very may well be just a syncing or server issue. May only happen to isolated swatches maybe. The sugar cane and wheat I had attached to the main land I'm on has never disappeared. I am away from my pc at the moment, but can send a few screenshots when I get home of the exact setup. My bad for not following the bug template, I'll also edit that when I get the chance. Sent from ProtonMail for iOS On Sat, Aug 14, 2021 at 1:39 PM, Colin Wong ***@***.***> wrote:  
does the tilled soil have water around it

**Comment by democat3457** [comment]
Can you send a picture of the area in-game

**Comment by mpmdw** [comment]
Soon as I'm back at the computer I will. Thanks a lot, didn't expect to get so much support for my relatively trivial issue I would've taken more care in submitting my bug report Sent from ProtonMail for iOS On Sat, Aug 14, 2021 at 1:46 PM, Colin Wong ***@***.***> wrote:  
Can you send a picture of the area in-game

**Comment by mpmdw** [comment]
Ok so as numbered in both pics, 1 is the area that most frequently vanishes (maybe 3-4 times few crops at a time, various states of growth, various crops. I have put wheat, carrots, hemp, all to disappear without being trampled on so far as I saw. The soil also never was untilled that I saw.  2. gave less problems, a few melon seeds disappeared early on and have not since, 3. is a spot that has never disappeared, it was the earliest spot. I have an underground farm with no such issues, which leads me to believe it's either a mob interaction or a glitch. I didn't think trampled by mobs because the soil didn't require tilling again is my only reason I'm even considering a glitch. I also do get pretty frequent minecraft has encountered an unknown error press ctrl I for more when I start up the game and while it's loading but that seems to fade.
![bugNote2](https://user-images.githubusercontent.com/69032261/129465172-0226564a-475a-4114-b221-64251214efaf.png)
![bugNote1](https://user-images.githubusercontent.com/69032261/129465173-7f5fdecf-66f3-400f-9686-55f3b7f135b6.png)

**Comment by KaleThyself** [comment]
I experience this same issue when playing on a privately hosted dedicated server.

**Comment by democat3457** [comment]
can you (anyone) show the server logs of about the time they disappear

**Comment by mpmdw** [comment]
I will. try to recreate but the first raid has such destroyed most of what you see in the pictures. Will update when I can

**Comment by mpmdw** [comment]
Okay it has happened a few more times. Here are logs from roughly the times. 
[bugLogs.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6997168/bugLogs.txt)

**Comment by democat3457** [comment]
wack there isn't anything useful in the logs

**Comment by mpmdw** [comment]
I'll keep recording logs when it happens and add them. It's not the end of the world

**Comment by KaleThyself** [comment]
Crops do not appear to randomly disintegrate into thin air anymore as of v.3.1.1a, so this issue may be closed.
