### ISSUE TITLE
[BUG] Inconsistent Cauldron Brewing

### ISSUE THREAD

**Issue by Dr-Turtle** [Rebirth-of-the-Night/Rebirth-Of-The-Night#796]
**Describe the bug**
When using a cauldron to brew potions, sometimes it allows for varying amounts of liquid, and sometimes does not. JEI implies that this method will only brew 2 potions at a time, I have yet to experience any issues while only brewing 2 potions,

**To Reproduce**  
Brew potions in a full cauldron, as if it only contained 2 bottles (afaik this should not be possible in the first place, but it has a chance to not work at all).

I have attempted to create a video demonstrating this bug, but I have been unable to reproduce it again as I am uncertain the conditions needed for the cauldron to not accept items

**Expected behavior**
The cauldron is to not accept items regardless when it does not have exactly 2 bottles of liquid.

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other:

**Comment by democat3457** [comment]
hmm well if it can't be reproduced reliably, it's unfortunately almost impossible to fix - comment on this when you do manage to get a video, though, and we'll be happy to reopen it

**Comment by Dr-Turtle** [comment]
I was able to brew awkward potions with a full cauldron but was still unable to reproduce it with other ingredients, the ingredients I was trying to use were the same ones that I was able to brew with previously

https://imgur.com/a/v91QeQp

**Comment by democat3457** [comment]
i thought you were supposed to throw them in instead of right-clicking, no?

**Comment by Dr-Turtle** [comment]
It seems that this only occurs when right-clicking as seen here
https://imgur.com/a/UWzpKVn

**Comment by democat3457** [comment]
well the fact that you can right click it is unintended i believe
