### ISSUE TITLE
[CRASH] at startup when loading all the plugins - Cave Generator

### ISSUE THREAD

**Issue by EnTonyH** [Rebirth-of-the-Night/Rebirth-Of-The-Night#797]
**Describe the crash**

Looking at loading plugins and then crash log. Screen here: https://ctrlv.link/holI 

**To Reproduce**  
1. install clean
2. play a game, generate new world, start a local server, friend join, playing no problem
3. quit the game
4. wait a few hours
5. start the game like always
6. crash (the problem)

**Crash Log**

included as a txt file here
[crash-2021-08-28_19.57.36-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/7071209/crash-2021-08-28_19.57.36-client.txt)

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

Macbook Air M1
Restarting the macbook does not help.
Restarting curseforge does not help.
Force quit java after crash does not help. 

Expected some temporary fiels or world generated files, but it would be solved by restart. I will have to complete delete the modpack to clean to get it to work again. 

Did not happened on stable release 2.77.7

**Comment by democat3457** [comment]
that completely shouldn't happen. absolutely no idea what is causing this. have you tried moving the rotn install location elsewhere?

**Comment by EnTonyH** [comment]
Deleted beta, now playing alpha. Will not be abe to give more info now.

But here are some point worth noting:
- This does not happen after clean install and moving folder to a new location and playing stable version. Into a folder that is not icloud synced. It seems like icloud sync could be doing some of the problems.

- I discovered other problem in stable release MP. when people cant connect to my server cause of missing registry after once playing there and my stopping the server. That was solved by uploading my MP map to a person. He opened it in his game. And then he could connect to me. But that a potential story for a new git issue.

**Comment by democat3457** [comment]
oh yeah the icloud thing is probably the issue
i've seen similar things happen to steam games like ksp when modding them

and in regards to the mp problem, i have no clue what that is

but this can be closed now since it seems resolved
