### ISSUE TITLE
[BUG] Soaking pot culls items in recipes resulting in stacks over the max stack size

### ISSUE THREAD

**Issue by Gnuelch** [Rebirth-of-the-Night/Rebirth-Of-The-Night#812]
**Describe the bug**
When soaking 13 or more hay bales in wood tar in the soaking pot, the recipe will only return 64 tar bales, when more should be returned.

**To Reproduce**  
1. Pour 4 buckets of wood tar in a soaking pot
2. Put 13 or more hay bales in the very same soaking pot (recipe should result in at least 65 tar bales)
3. Wait for the soaking to commence
4. Retrieve now only 64 tar bales instead of the 65+

**Expected behavior**
The Soaking pot should either:
a) allow only 12 hay bales to be processed at once (or just enough to not lose any material, depending on the recipe)
b) allow more than 64 items to be retrieved once the soaking process is done.

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

**Comment by codetaylor** [comment]
Fixed in Pyrotech `1.12.2-1.5.23`

**Comment by democat3457** [comment]
Fixed in 3.0.0
