### ISSUE TITLE
[CRASH] Ice and fire ROTN Pixie house crash the game trying to render it

### ISSUE THREAD

**Issue by ElTioYisus** [Rebirth-of-the-Night/Rebirth-Of-The-Night#814]
**Describe the crash**

**To Reproduce**  
-Install only ice and fire rotn version and library to see that there is the problem.
-On creative go to ice and fire blocks tab and try to see the pixies house.
-Complete! Your game is crashed.

**Crash Log**

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [ ] 3.0 BETA 5
   - [x] Other: a single mod issue 
 - Server or Singleplayer:
   - [ ] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [ ] 3.0 BETA 5
   - [x] Other: a single mod issue

**Additional context**

**Comment by democat3457** [comment]
Can you resubmit this to https://github.com/Rebirth-of-the-Night/Ice_and_Fire/issues? Thanks

**Comment by ElTioYisus** [comment]
Done! :D
