### ISSUE TITLE
[BUG] Mulch only works on vanilla farmland

### ISSUE THREAD

**Issue by luke512** [Rebirth-of-the-Night/Rebirth-Of-The-Night#818]
**Describe the bug**
Can't use mulch on non-vanilla farmland

**To Reproduce**  
Right click farmland from a mod (eg. bop loamy farmland) with pyrotech mulch

**Expected behavior**
farmland becomes mulched

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other:

**Comment by iEatShadows** [comment]
I remember this bug, it was back in April when my friend encounter it, so we suggested it to have the loamy farmland and the silty farmland. We forgot to report it to Github oops.
(https://discord.com/channels/620840315498004480/714540497171120199/848411737179029535)
