### ISSUE TITLE
[BUG] Wood Plank Siding, Moulding, and Corners have the same cook time as Wood Planks (1.5 items)

### ISSUE THREAD

**Issue by jdvne** [Rebirth-of-the-Night/Rebirth-Of-The-Night#819]
**Describe the bug**

All variations of slab, siding, moulding, and corner crafted from wood planks have the same cooking time within a furnace (1.5 items).  Because each wood plank can be sawed into a grand total of 8 corners, this effectively extends their cooking time to 12 seconds per plank instead of 1.5.

**To Reproduce**  
Use any wooden slab, siding, moulding, or corner as fuel in a furnace and compare to regular planks as fuel.

**Expected behavior**

Each block should have a cook time relative to its recipe: 
- Slab/Siding: **0.75 items** (1.5 items / 2)
- Moulding: **0.375 items** (1.5 items / 4)
- Corner: **0.1875 items** (1.5 items / 8)

**Screenshots**

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [x] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**

**Comment by democat3457** [comment]
Pretty sure this is fixed in beta 6. Can any dev confirm?

**Comment by democat3457** [comment]
Confirmed fixed in beta 6.
