### ISSUE TITLE
[BUG] Villager GUI

### ISSUE THREAD

**Issue by Toocan11** [Rebirth-of-the-Night/Rebirth-Of-The-Night#828]
### Describe the bug

After exiting the trading GUI of any villager type, interacting with the item purchased results in all purchased goods reverting back to emeralds and any reorganization of inventory reverting to the order it was in prior to opening the trading GUI.

### To Reproduce

Open trading GUI, purchase item, rearange inventory. Close trading GUI, interact with the purchased item.

### Modpack Version

3.0.0

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.0

### Additional context

My computer has a total of 8gb RAM. I have allocated 6gb to ROTN. My TPS is consistently between 18-20.

**Comment by iEatShadows** [comment]
Fixed in 3.0.1
