### ISSUE TITLE
[BUG] Sharpness does not increase damage when attacking any mob types

### ISSUE THREAD

**Issue by SkilljoyJr** [Rebirth-of-the-Night/Rebirth-Of-The-Night#830]
### Describe the bug

![Screenshot_826](https://user-images.githubusercontent.com/101489333/158043992-c54c3ce1-d7cd-48e4-be7f-15e052fb6b23.png)
Attacking non-undead and non-arthopods does not increase the damage either. This applies to all levels of sharpness

### To Reproduce

Enchant any weapon with sharpness using any method

### Expected behavior

In the case of an iron arming sword as a weapon example. The damage stat should increase to 9 damage with sharpness V after hitting a non-undead or non-arthopod mob.

### Modpack Version

3.0.0

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.0

**Comment by democat3457** [comment]
why close
