### ISSUE TITLE
[BUG] I do not see any mobs, as well as blocks lying on the floor.

### ISSUE THREAD

**Issue by vlad0ff** [Rebirth-of-the-Night/Rebirth-Of-The-Night#831]
### Describe the bug

When I appear in the world, I immediately notice that there are no peaceful mobs. Also, when I decided to cut down a tree, I noticed that after its fall there are no blocks and they appear in the inventory only after I pick them up. The sound of the mobs themselves is heard, but neither night nor day can they be seen. 

### To Reproduce

Creation of the world. 

### Expected behavior

Must see mobs as well as items that are out of inventory.

### Screenshots

![image](https://user-images.githubusercontent.com/101500924/158054121-af092929-959d-40a4-866d-9a4721a452f4.png)
![image](https://user-images.githubusercontent.com/101500924/158054126-f7990c12-0e7e-46ad-b844-dde243c68578.png)
![image](https://user-images.githubusercontent.com/101500924/158054137-0700161f-ce8b-4560-bcec-40d98bfb2d30.png)

### Modpack Version

3.0 BETA 5

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0 BETA 5

**Comment by Takedomaru** [comment]
ты решил проблему? у меня просто тоже самое

**Comment by vlad0ff** [comment]
нет, решил пока что забить просто

**Comment by Takedomaru** [comment]
удали мод entity culling

**Comment by vlad0ff** [comment]
да, помогло, спасибо
