### ISSUE TITLE
[BUG] invisible entities

### ISSUE THREAD

**Issue by Takedomaru** [Rebirth-of-the-Night/Rebirth-Of-The-Night#832]
### Describe the bug

All mobs are invisible and objects when mining or throwing out

### To Reproduce

downloaded ROTN and this bug was originally

### Screenshots

![g](https://user-images.githubusercontent.com/97760191/158057603-009f47e1-8ec8-4c5d-8fa7-0f93ac03eb67.png)

### Modpack Version

3.0 BETA 5

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0 BETA 5

**Comment by PavelEmelyanovNATK** [comment]
I have the same issue. Ryzen 3 5300u integrated graphics. I think the problem is in the drivers, cause my frends with nvidia chips dont have this issue. Do you solve it?

**Comment by iEatShadows** [comment]
> ### Describe the bug
> All mobs are invisible and objects when mining or throwing out
> 
> ### To Reproduce
> downloaded ROTN and this bug was originally
> 
> ### Expected behavior
> _No response_
> 
> ### Screenshots
> ![g](https://user-images.githubusercontent.com/97760191/158057603-009f47e1-8ec8-4c5d-8fa7-0f93ac03eb67.png)
> 
> ### Modpack Version
> 3.0 BETA 5
> 
> ### Server or singleplayer
> Singleplayer
> 
> ### Version the world was created on:
> 3.0 BETA 5
> 
> ### Other...
> _No response_
> 
> ### Additional context
> _No response_

Either remove the mod "EntityCulling" or get the updated version in discord.

**Comment by iEatShadows** [comment]
see if it fixes it.

**Comment by PavelEmelyanovNATK** [comment]
I disabled this option and it helped
![image](https://user-images.githubusercontent.com/78269656/158159486-c234ae3b-e9c9-4927-a32c-a3501c79cda4.png)
