### ISSUE TITLE
[CRASH] Onslaught causes crashes when playing with a friend in the local world

### ISSUE THREAD

**Issue by OBJECT228** [Rebirth-of-the-Night/Rebirth-Of-The-Night#834]
### Describe the crash

After finishing an invasion when friend is in your local world Onslaught causes crash

### To Reproduce

Adding a friend to a local world and finishing an invasion

### Crash Logs

[crash-2022-03-14_17.25.20-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/8247241/crash-2022-03-14_17.25.20-server.txt)
[crash-2022-03-14_17.25.27-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/8247242/crash-2022-03-14_17.25.27-client.txt)
[crash-2022-03-14_17.20.59-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/8247243/crash-2022-03-14_17.20.59-server.txt)
[crash-2022-03-14_17.24.19-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/8247244/crash-2022-03-14_17.24.19-server.txt)

### Modpack Version

3.0.0

### Server or singleplayer

Server

### Version the world was created on:

3.0.0

**Comment by iEatShadows** [comment]
Known, download the lasted onslaught mod here, https://www.curseforge.com/minecraft/mc-mods/onslaught/download/3680566

**Comment by democat3457** [comment]
yes, fixed next beta
