### ISSUE TITLE
[BUG] Torch and Wicker Basket interaction

### ISSUE THREAD

**Issue by TastyToastSon** [Rebirth-of-the-Night/Rebirth-Of-The-Night#835]
### Describe the bug

Right clicking a wicker basket with a torch in the off hand causes the torch to be removed from the offhand as if it were placed. The torch is not actually placed in the world.

### To Reproduce

Right click a wicker basket (I used a medium sized one) with torch(es) in the offhand.

### Expected behavior

it not attempt to place the torch, it just opens like a chest.

### Modpack Version

3.0.1

### Server or singleplayer

Server

### Version the world was created on:

3.0.1

**Comment by iEatShadows** [comment]
https://www.youtube.com/watch?v=9MS50jjCHkw
