### ISSUE TITLE
[BUG] Excessive Server CPU Usage

### ISSUE THREAD

**Issue by TastyToastSon** [Rebirth-of-the-Night/Rebirth-Of-The-Night#836]
### Describe the bug

Utilizing server version 3.0.1. Over time, excessive lagging will manifest because of anomalously high CPU usage by the modpack. The dedicated 10600KA server we were running was clocking in at 95% utilization, and it routinely falls >2000 ms behind schedule because of this. Restarting ROTN causes the issue to subside for a time, but it does come back.

### To Reproduce

Unknown if it is a global server issue, or an issue related to our specific circumstances. If it's a gobal issue, a simple server test should come across it in a few hours.

### Expected behavior

Nominal processor utilization. It is not expected for a modpack to constantly overwhelm a hexa-core 4.8 GHz modern chip.

### Modpack Version

3.0.1

### Server or singleplayer

Server

### Version the world was created on:

3.0.1

### Additional context

https://cdn.discordapp.com/attachments/567431322881228800/960076111394529311/2022-04-03-1.log

That crash manifested after the server sat, behind for too long of a time. It is possible these two issues are linked.

**Comment by KaleThyself** [comment]
Since this issue is on an outdated version which most likely got performance patched, I believe it's fine to close it, especially since those specific issues in the logs provided don't show up in v.3.1.1a anymore.
