### ISSUE TITLE
[BUG] Multiple water bottles disappear when making mochi, and rice & honeycomb doubles

### ISSUE THREAD

**Issue by aolinyang** [Rebirth-of-the-Night/Rebirth-Of-The-Night#841]
### Describe the bug

A glass bottle of water, rice, and honeycomb are required to make mochi. However, if you put multiple bottles of water for multiple mochi and shift-click the mochi out, only a single glass bottle is returned to the inventory. Also, the rice and honeycomb double instead of decrementing.

### To Reproduce

1. Get 2 or more glass bottles of water
2. Get 2 or more rice
3. Get 2 or more honeycomb
4. Put them on the on-person crafting grid
5. Shift-click the mochi out 
6. If shift-clicking does not duplicate rice and honeycomb, drag the mochi out.

### Expected behavior

All empty glass bottles should be returned to inventory, and rice & honeycomb should decrease in amount.

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by iEatShadows** [comment]
known bug of #712

**Comment by TheNelston** [comment]
fixed as of 3.0.2
