### ISSUE TITLE
[BUG] Creating a fruit tree seed with a bucket of dirt and the fruit will duplicate the bucket

### ISSUE THREAD

**Issue by aolinyang** [Rebirth-of-the-Night/Rebirth-Of-The-Night#842]
### Describe the bug

Creating a fruit tree seed with a bucket of dirt and the fruit will duplicate the bucket - gives you an empty bucket with durability taken off and a bucket of dirt.

### To Reproduce

1. Get a bucket of dirt and a persimmon
2. Put them together to craft the persimmon seeds

### Expected behavior

Shouldn't end up with an untouched bucket of dirt.

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by iEatShadows** [comment]
yep the Dirt bucket dupe, its easier to dupe with just dirt + Iron bucket.  https://www.youtube.com/watch?v=2F7AFgW_c3A&list=PLml4tOym_pQXwoAOgYuyI291Zn7Fjftk8&index=6

**Comment by TheNelston** [comment]
it's intentional that crafting a dirt bucket with a fruit does not consume the bucket; however, the bucket dupe has been patched for next update
