### ISSUE TITLE
[BUG] Bees increase in number in the apiary

### ISSUE THREAD

**Issue by aolinyang** [Rebirth-of-the-Night/Rebirth-Of-The-Night#843]
### Describe the bug

Putting a bee in the apiary will increase the number of bees over time instead of using them up - not sure if this is intended or not.

### To Reproduce

1. Put bee in apiary
2. Wait

### Expected behavior

Bees should decrease in number - this seems like an infinite source of honeycomb which is too easy.

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by KaleThyself** [comment]
If you think this is something that could be tweaked, feel free to put it as a `.suggest` in the Discord server. Otherwise, it works as intended by the Rustic mod.

**Comment by democat3457** [comment]
yeah unfortunately this isnt something that can be fixed, as the capability is not present in the base rustic mod
