### ISSUE TITLE
[BUG] Weakness makes you unable to dish out damage

### ISSUE THREAD

**Issue by aolinyang** [Rebirth-of-the-Night/Rebirth-Of-The-Night#844]
### Describe the bug

Having any level of weakness makes you unable to deal damage at all

### To Reproduce

1. Get weakness from either sleeping or a weakness arrow
2. Try to damage a mob

### Expected behavior

Should have decreased damage, not no damage

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by TheNelston** [comment]
caused by immersive combat
