### ISSUE TITLE
[BUG] Onslaught does not always work properly (two separate bugs)

### ISSUE THREAD

**Issue by aolinyang** [Rebirth-of-the-Night/Rebirth-Of-The-Night#846]
### Describe the bug

One night, I went to sleep when there's supposed to be an invasion, and the invasion happened in the morning when I woke up.
Another night, the invasion happened as scheduled, but even after I killed all highlighted zombies the progress bar wasn't full. I did die a few times by this thing called "The Huntsman."

### To Reproduce

Inconsistent bug, occurs during some invasions. All I've experienced are zombie invasions.

### Expected behavior

Invasions should only be at night and should fill up completely after you kill all highlighted mobs.

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by W0lflake** [comment]
I'm having the same problem on of the raid not finishing in version v3.1.1, does anyone have a way to get rid of this problem?

**Comment by EliteMeats** [comment]
This issue will be "fixed" in 3.2.0 (or whatever we end up calling it), due to the removal of the Onslaught mod. If we ever use the mod again might be worth relooking at.
