### ISSUE TITLE
[BUG] Dense Redstone Not Spawning

### ISSUE THREAD

**Issue by MegaGlub** [Rebirth-of-the-Night/Rebirth-Of-The-Night#847]
### Describe the bug

Dense redstone crystals do not spawn deep in caves.

### To Reproduce

1. Create a new world
2. Enter spectator mode
3. Check the underground near lava level for dense redstone crystals

### Expected behavior

Dense redstone crystals should be spawning deep in the caves, at a rate of ~0.25 - 1 per chunk.

### Modpack Version

3.0.1, Other

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1, Other

### Other...

3.0.1a

### Additional context

They did spawn in 3.0.0, but not in the current version. Might be related the removal of cave roots somehow.

**Comment by TheNelston** [comment]
upcoming fix next update
