### ISSUE TITLE
[BUG] Gold blast furnace dupe

### ISSUE THREAD

**Issue by RealSinful** [Rebirth-of-the-Night/Rebirth-Of-The-Night#850]
### Describe the bug

Using the blast furnace to smelt anything, and removing the produced material will result in turning nothing into gold afterwards with what ever remaining fuel.

Ex: Place 1 charcoal block as fuel, and 1 raw ore, wait for the ore to smelt and remove the ingot, you'll start producing gold out of nothing until the fuel runs out

GIF: https://gyazo.com/524bc94b3e4ae579cc24b83ec00780a3

### To Reproduce

Get a blast furnace
Place 1 charcoal block as fuel
Place 1 raw ore in the furnace
Remove the smelted material from the output slot

### Expected behavior

Produces gold from nothing

### Screenshots

https://gyazo.com/524bc94b3e4ae579cc24b83ec00780a3

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by democat3457** [comment]
Does this happen on 3.1? And does this occur in the regular furnace as well?

**Comment by KaleThyself** [comment]
![image](https://user-images.githubusercontent.com/50285548/176405351-fa2da799-a54b-462f-a910-57c41286e4b3.png)

This only seems to occur with the blast furnace from futuremc.

**Comment by democat3457** [comment]
Fixed in 3.1.2
