### ISSUE TITLE
[BUG] Recipe for wooden bridge is blank; can craft out of thin air

### ISSUE THREAD

**Issue by aolinyang** [Rebirth-of-the-Night/Rebirth-Of-The-Night#853]
### Describe the bug

See image

### To Reproduce

Go to JEI and view recipe for wooden bridge

### Expected behavior

Shouldn't be blank

### Screenshots

![Capture](https://user-images.githubusercontent.com/43360744/164873974-f3a2ca44-9a7d-4c12-8b9c-e54a72ec2fea.PNG)

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by TheNelston** [comment]
fixed in upcoming update
