### ISSUE TITLE
[BUG] Can't break arcane barrier with Arcane focus

### ISSUE THREAD

**Issue by RealSinful** [Rebirth-of-the-Night/Rebirth-Of-The-Night#854]
### Describe the bug

Can't interact with arcane barrier using an arcane focus

### To Reproduce

Make/get 1x ritual table, 1x un-attuned focus, 1x vis shard, 1x rune of arcana
Craft arcane focus
Dig down to arcane barrier level
Attempt to interact with arcane barrier block

### Expected behavior

Nothing happens, no interaction/animation

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by TheNelston** [comment]
are you talking about the first layer of arcane barrier?

**Comment by KaleThyself** [comment]
The Arcane Focus properly works in v.3.1.1a, so this issue may be closed.
