### ISSUE TITLE
[BUG] archimedes screw doesn't work with iron ingots

### ISSUE THREAD

**Issue by aolinyang** [Rebirth-of-the-Night/Rebirth-Of-The-Night#855]
### Describe the bug

Trying to use iron ingots to make an archimedes screw only allows you to craft iron bricks instead.

### To Reproduce

Try to use iron ingots to make an archimedes screw.

### Expected behavior

Archimedes screw recipe should be an option.

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by KaleThyself** [comment]
This is replicable for all ingots that may be used for the archimedes screw.

**Comment by democat3457** [comment]
@TheNelston can you link the commit that fixed this

**Comment by TheNelston** [comment]
@democat3457 it didnt fix last time, this is the new fix 4db56b1

**Comment by democat3457** [comment]
Why'd you only make some of the bricks recipe shaped and left others shapeless?

**Comment by TheNelston** [comment]
these are the only ones that cause recipe issues right now- no point taking away the flexibility with other bricks/recipes if it isnt necessary

**Comment by democat3457** [comment]
but - *inconsistency*

and it might bite us later if the issue does come up again and we forget we made these changes

**Comment by TheNelston** [comment]
cope + seethe + mald + ratio + dont care + cry (ill fix it later dw)

**Comment by democat3457** [comment]
Fixed inconsistency with e39c9d87c6065a95346066e2f263d725922739a4
