### ISSUE TITLE
[BUG] Projectile damage buff/bonuses does not work with crossbows.

### ISSUE THREAD

**Issue by iEatShadows** [Rebirth-of-the-Night/Rebirth-Of-The-Night#856]
### Describe the bug

Projectile damage buff/bonuses does not work with crossbows. That means crossbows get no damage boosts at all.

### To Reproduce

1. Get a crossbow with some bolts
2. Shoot something without the set bonus/projectile damage buff -> ( /summon minecraft:Giant ) Great for testing cause its only just 100 hp with no armor.
3. record damage
4. this time wear the set bonus and/or buff yourself with projectile damage
5. shoot the same mob (summon another giant)
6. record damage
7. expect no damage increase

### Expected behavior

I would expect the set bonus damage and projectile damage buff to be added on to the crossbow's total damage.

### Screenshots

Set bonus https://youtu.be/-jKm4zybJY0

Projectile damage buff https://youtu.be/c8MMhQ_0Rvo

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

### Additional context

my playlist of found bugs https://www.youtube.com/playlist?list=PLml4tOym_pQXwoAOgYuyI291Zn7Fjftk8

**Comment by bglandolt** [comment]
Spartan Weaponry bolts use their own armor piercing damage - and still uses "arrow" as the damageType
but it never sets its custom damage type as a projectile (I presume, can't find anywhere in the code where it does)

However, this is a simple fix I can do through the Immersive Combat mod

**Comment by iEatShadows** [comment]
I believe this is fixed.
