### ISSUE TITLE
[BUG] Arrows duping (and exceeding the normal stack value)

### ISSUE THREAD

**Issue by Archidon547** [Rebirth-of-the-Night/Rebirth-Of-The-Night#857]
### Describe the bug

Arrows continuously increase in number, exceeding the stack limit

### To Reproduce

Use a Mythril bow with homing 2 enchant and Back to the chamber 5 enchant, a quiver with flint arrows, and a mob holding shield.
Shoot the shielded mob with the bow and quiver in hot bar

### Expected behavior

The homing arrow will continue targeting the shielded mob while the Back to the chamber enchant will add arrows to the player indefinitely

### Screenshots

The result after duping
![image](https://user-images.githubusercontent.com/104476286/165426231-d12d8d96-e45b-4777-bbac-eabb6d95f677.png)

### Modpack Version

3.0.1

### Server or singleplayer

Server

### Version the world was created on:

3.0.1

**Comment by kil0byt3** [comment]
That is a wild ass mod interaction. Thanks for the detailed report

**Comment by democat3457** [comment]
It's not even a mod interaction - I know the exact cause of this issue but there's no way to fix it (The mod assumes all arrows are vanilla when it's not)
