### ISSUE TITLE
[BUG] Picking up milk placed in the world with a bottle

### ISSUE THREAD

**Issue by ev-ev** [Rebirth-of-the-Night/Rebirth-Of-The-Night#858]
### Describe the bug

When picking up milk with a bottle that was placed in the world using a bucket, instead of the bottle getting filled with milk, it gets filled with water.

### To Reproduce

1. Place milk (goat in this case) in the world using a bucket
2. Try to bottle the milk with a glass bottle

### Expected behavior

Glass bottle gets filled with milk

### Screenshots

![image](https://user-images.githubusercontent.com/27211692/165502763-6f21c206-29c7-41b6-b432-016c84b029ac.png)
![image](https://user-images.githubusercontent.com/27211692/165502792-b1e3ec3f-c591-4f0a-aadb-6533917cb08d.png)

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by TheNelston** [comment]
cant fix, mod bug
