### ISSUE TITLE
[BUG] Desert myrmex using jungle trades

### ISSUE THREAD

**Issue by Chris95073** [Rebirth-of-the-Night/Rebirth-Of-The-Night#859]
### Describe the bug

When trading with myrmex, they will use the wrong trades. For example, a desert myrmex may ask for jungle resin.

### To Reproduce

1. Reach enough reputation with a myrmex hive to trade
2. Right click on a myrmex (might have to try a few different ones to find one with incorrect trades.

### Expected behavior

I expect my desert myrmex queen and her workers to trade using desert myrmex resin, but some of them trade with jungle resin instead

### Screenshots

![unknown-338](https://user-images.githubusercontent.com/99776074/165743489-69b44513-cae1-41e7-97af-93e01251ef61.png)

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

### Additional context

The rest of my queen's trades became normal once I leveled her up, but her initial trade stayed as jungle myrmex resin for jungle myrmex egg. Some of the workers were asking for dirt instead of sand, which is not supposed to happen for desert myrmex. I think the issue may be caused because of an issue with the tables from which the myrmex choose their trades.

**Comment by democat3457** [comment]
known bug with ice and fire, can't fix
