### ISSUE TITLE
[BUG] Magic Lantern Recipe Broken

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#863]
### Describe the bug

The Magic Lantern is unable to be crafted despite having all of the components in the Runic Workbench. 

### To Reproduce

1. Place all of the components required to craft the Magic Lantern into the Runic Workbench. 
2. Nothing will show up as the output. 

### Expected behavior

I expect the item to be obtainable through crafting. 

### Screenshots

![image](https://user-images.githubusercontent.com/50285548/166834648-bca3d139-171e-4be5-aa18-dfd29adcbf7c.png)

### Modpack Version

3.0.1

### Server or singleplayer

Server

### Version the world was created on:

3.0.1

### Other...

_N/A_

### Additional context

_N/A_

**Comment by democat3457** [comment]
can you do /ct hand on the magnifier tool

**Comment by democat3457** [comment]
Fixed
