### ISSUE TITLE
[BUG] Snow on top of a vine trap allows you to stand on it without falling through, effectively ruining the trap during winter.

### ISSUE THREAD

**Issue by FamiliarPings** [Rebirth-of-the-Night/Rebirth-Of-The-Night#867]
### Describe the bug

Snow layers on top of a vine trap allow mobs to just stand on top of the vines

![image](https://user-images.githubusercontent.com/85465423/167232932-f8473e1b-4cfd-4678-8ea7-fd8205485a69.png)

### Modpack Version

3.0.1

### Server or singleplayer

Server

### Version the world was created on:

3.0.1

**Comment by TheNelston** [comment]
should be fixed next update, added a new snow physics mod
