### ISSUE TITLE
Atlas n[BUG]

### ISSUE THREAD

**Issue by TudorS98** [Rebirth-of-the-Night/Rebirth-Of-The-Night#872]
### Describe the bug

My atlas seems to have generated a map that doesn't match the in-game reality (i.e., it puts sea where there should be land); see screenshot below.

### Screenshots

![image](https://user-images.githubusercontent.com/60627480/167657063-c5ef3290-cdaf-4b01-9bb5-6790cc1ea171.png)

### Modpack Version

3.0.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1

**Comment by iEatShadows** [comment]
it's just atlas itself, dunno if its a bug or not. Its been around for a long time and i dont think there's an actual fix.
You can send it to https://github.com/AntiqueAtlasTeam/AntiqueAtlas to see if they can do something about it. I'd say its intended cause its 'Antique'.

**Comment by democat3457** [comment]
Can you show the chunk borders there? maybe the chunk itself says its an ocean biome because it's mostly ocean

**Comment by democat3457** [comment]
For the suspected aforementioned reason and due to the lack of a response, I'm closing this issue for now - if a more major issue appears in a separate instance, feel free to comment and reopen this.
