### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by joshuameek** [Rebirth-of-the-Night/Rebirth-Of-The-Night#874]
### Describe the bug

Getting Antsy advancement not unlocking.

### To Reproduce

Reach 100 reputation in a jungle myrmex colony.

### Expected behavior

Should unlock upon reaching 100 reputation.

### Modpack Version

3.0.1

### Server or singleplayer

Server

### Version the world was created on:

3.0.1

**Comment by TheNelston** [comment]
it requires you to get a myrmex egg, so not bugged
