### ISSUE TITLE
minor, rice paddy movement issues[BUG]

### ISSUE THREAD

**Issue by Tomato-No-Mae** [Rebirth-of-the-Night/Rebirth-Of-The-Night#877]
### Describe the bug

minor, but creating a rice paddy directly under you causes weird movment

### To Reproduce

create a rice paddy on the block you're standing on

### Expected behavior

idk, not the movement that occurs

### Modpack Version

3.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1

**Comment by Tomato-No-Mae** [comment]
forgor to add a title my bad

**Comment by Foreck1** [comment]
This issue is related to growth craft itself which is no longer being updated for 1.12. Sadl, we can't fix it at all.
