### ISSUE TITLE
[BUG] filch Lizard bug still present in 3.0

### ISSUE THREAD

**Issue by Stargen45** [Rebirth-of-the-Night/Rebirth-Of-The-Night#883]
### Describe the bug

A year ago or 2 someone had a bug about flich lizards where on 2.77.5 the lizards would take two items but only one would be present on the lizard when hurt which deleted the other item. Not sure if it's fixable or bug on the mod end but just wanted address its in 3.0 still 

### To Reproduce

Have more than 1 item thats rare like a diamond or emerald. Find some flich lizards and you will see you are losing two items, hurting the lizard only drops one resulting in you losing one permanently

### Expected behavior

flich lizard only meant to steal one and drop one, its expected behavior happens in creative but not in survival 

### Modpack Version

3.1

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1

**Comment by democat3457** [comment]
related to #369

**Comment by democat3457** [comment]
actually im gonna move this issue to #369, marking as duplicate
