### ISSUE TITLE
[BUG] Mature xorcite clusters can give infinite xp

### ISSUE THREAD

**Issue by sneetsnart** [Rebirth-of-the-Night/Rebirth-Of-The-Night#886]
### Describe the bug

xorcite clusters will give xp every time right clicked, infinitely :kek:

### To Reproduce

break an xp giving block (biotite/exorite ore) immediately before right clicking a mature xorcite cluster, it seems to copy the xp data and give you that ores amount of xp every time right clicked

### Expected behavior

not a stupidly absurd xp farm

### Modpack Version

3.1

### Server or singleplayer

Server

### Version the world was created on:

3.1

**Comment by kil0byt3** [comment]
duplicate of #424

thank you for reporting!
