### ISSUE TITLE
[BUG] Vanilla enchanted bow visual 

### ISSUE THREAD

**Issue by ChewyGogurt** [Rebirth-of-the-Night/Rebirth-Of-The-Night#89]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
The vanilla bow with power 5 seems does not do the animation when drawed back. 

**To Reproduce**

Craft a bow with 3 sticks and 3 string, enchant it, try and shoot. 

**Expected behavior**
It kind of zooms out the bow but it still fires perfectly just you cant aim as well. 

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.76.1 (recent)
 - Server or Singleplayer: singleplayer 
 - Version the world was created on: 2.76.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
We'll look into this.

**Comment by kil0byt3** [comment]
Still an issue in 2.77
