### ISSUE TITLE
[BUG] Saplings/Acorns are not dropping

### ISSUE THREAD

**Issue by Fiveby21** [Rebirth-of-the-Night/Rebirth-Of-The-Night#891]
### Describe the bug

This has been an issue I've encountered in all versions of 3.0 and 3.1. Quite simply, saplings barely ever drop. It seems like a 10% chance, when I chop down a tree, that I get any saplings. 

### To Reproduce

1. Chop down 10 trees with an axe.
2. Count the number of times you receive a sapling

### Expected behavior

A tree drops an average of 1-2 saplings.

### Modpack Version

3.1.0

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.0

**Comment by Snowcone-Cola** [comment]
This is due to saplings only dropping in specific seasons, a featured planned for removal/has already been removed in 3.1.

**Comment by Fiveby21** [comment]
Okay I started a new game and I had the exact opposite result, most trees were dropping around 4 saplings. I wonder if it is a season thing?

**Comment by kil0byt3** [comment]
Should be fixed in https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/4d83d729bfd0e7bc508b869a758ff2a61095a5a3

> -tree seeds no longer drop according to season; should make seeds less bizarrely rare

**Comment by kil0byt3** [comment]
Oops, forgot we don't close until we release

**Comment by democat3457** [comment]
format from now on:

close if completed, but add upcoming fix to indicate the fix will arrive in next version
when next version releases, remove upcoming fix from all closed issues
