### ISSUE TITLE
[BUG] Mill Stone uses Lightning Sound effect

### ISSUE THREAD

**Issue by MegaGlub** [Rebirth-of-the-Night/Rebirth-Of-The-Night#902]
### Describe the bug

The Mill Stone from better with mods (betterwithmods:single_machine) uses the thunder / lightning sound effect at full volume when being used. It could also be the hand crank (betterwithmods:hand_crank), I suppose.

My ears are bleeding.

### To Reproduce

1. Place a Mill Stone and a Hand Crank together.
2. Turn down your computer's volume.
3. Right click on the Hand Crank.

### Expected behavior

The Mill Stone used to make an annoying, but not exceptionally loud sound. It should do that again.

### Modpack Version

3.1.0

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.0

**Comment by EliteMeats** [comment]
I can't seem to replicate this, can you attach a video or something?

**Comment by kil0byt3** [comment]
This is a thing for a bunch of people and definitely happens

I don’t know the cause but I know others can replicate this

**Comment by Stargen45** [comment]
It happens when you use help in it

**Comment by MegaGlub** [comment]
Just tested it, Stargen is right. Will upload a video shortly.

**Comment by MegaGlub** [comment]
https://youtu.be/kA8jiuQBo6w

(still uploading, may not be up for a bit)

tldw; It looks like some items cause the lightning sound, while some items don't. Hemp and Flax Flowers do cause the sound, while Coal and Sugar Cane do not. Empty Mill Stones also do not make lightning sounds.

**Comment by democat3457** [comment]
does this happen on 3.0.1

**Comment by kil0byt3** [comment]
likely caused by https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/blob/master/scripts/betterwithmods/betterwithmods_recipes_mill.zs#L194
and bugs in the BWM CrT integration

**Comment by democat3457** [comment]
thats what i thought, but i was looking in the bwm source and didnt find anything related to thunder or lightning

**Comment by democat3457** [comment]
maybe we can move that line to like the beginning and see how it goes

**Comment by kil0byt3** [comment]
@MegaGlub @Stargen45 it was a bug with BWM CraftTweaker integration (provided by ModTweaker) and is now fixed due to Demo fixing the bug
