### ISSUE TITLE
[BUG] Large Wicker Basket Error

### ISSUE THREAD

**Issue by Power625** [Rebirth-of-the-Night/Rebirth-Of-The-Night#906]
### Describe the bug

Opening up a large wicker basket in my hand causes an error to pop up. It was happening for a while then it suddenly stopped.

### To Reproduce

Haven't found a way to reproduce yet.

### Expected behavior

No error to pop up.

### Screenshots

Contents of basket when it was happening.
![wicker](https://user-images.githubusercontent.com/72326420/174902522-af62f4fd-92c2-452b-9f15-b630dd59b793.png)

### Modpack Version

3.1.0

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.0

### Additional context

https://pastes.dev/idCcOZ9MgK

**Comment by KaleThyself** [comment]
I haven't been able to figure out how to reproduce this error, nor have I seen anyone report anything similar to it in v.3.1.1a. Due to lack of follow up and its obscurity, this issue may be closed.
