### ISSUE TITLE
[BUG] nether not loading

### ISSUE THREAD

**Issue by RenjiAkairu** [Rebirth-of-the-Night/Rebirth-Of-The-Night#909]
### Describe the bug

when i go to nether first time
it show text take a bit to load but 30 minute i can't go to the nether
file world : [https://drive.google.com/file/d/1vIEyavMRpVYhiw4S-aH2dUYY4XW3b7x2/view?usp=sharing](url)

### Modpack Version

3.1.0

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.0

**Comment by iEatShadows** [comment]
Quit the world or restart the instance then enter the portal again.

**Comment by TheNelston** [comment]
kill the harvester, not a big

**Comment by RenjiAkairu** [comment]
where is a harvester i can't find 
TwT

**Comment by democat3457** [comment]
you summon it, check the guidebook
