### ISSUE TITLE
[BUG] Harvest Craft Gardens unplaceable

### ISSUE THREAD

**Issue by Tomato-No-Mae** [Rebirth-of-the-Night/Rebirth-Of-The-Night#919]
### Describe the bug

After breaking a harvest craft garden while sneaking, the garden itself will drop as an item, the intended use of this is for it to be broken again at a later date to save on inventory space while exploring, however after breaking one while sneaking, I cannot place it back on grass or dirt to break it regularly

### To Reproduce

1. sneak break a harvestcraft garden
2. attempt to place it back on the ground
3. cry

### Expected behavior

that it would be able to place

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1

**Comment by KaleThyself** [comment]
Compatibility says that you can only place these gardens on vanilla dirt/grass, not modded dirt/grass.

**Comment by democat3457** [comment]
there ya go then
