### ISSUE TITLE
[CRASH] Random crash with Onslaught despite no invasion

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#923]
### Describe the crash

Randomly, our server crashed while one player was underground fighting typical cave mobs and another was above ground sitting in their base. 

### To Reproduce

N/A

### Crash Logs

[crash-2022-07-02_13.49.59-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/9033797/crash-2022-07-02_13.49.59-server.txt)

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1

**Comment by democat3457** [comment]
Fixed in https://github.com/Rebirth-of-the-Night/onslaught/commit/cde4bf3ed103f5c6e7e6b13a14cc88028eb42681, mod update will be pushed out shortly
