### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by richcvbmm** [Rebirth-of-the-Night/Rebirth-Of-The-Night#924]
### Describe the crash

Ok so I have not played RotN in a few months and the last time I remember playing, my save was corrupted or something (minimap showing no texture error etc). I tried loading the backup today but 2 problems accrued, first of all, the error at the bottom of this text showed up and the game said I should create a backup and then yes or no, the after clicking yes said forge mod loader detecting that the backup level.dat is being used then again yes or no to creating the backup. after clicking yes, it tries loading the save but it shows for a second and then gives me a "Minecraft crashed!" error. when clicking "get link" it just changes to "[Failed]" and I can only click "Back to title screen" which works. Here is the "Missing Registries" error.

Missing Registries: 
orespawn:feature_registry
orespawn:replacements_registry

### To Reproduce

Literally, just load my save, I need help because I have no idea how to fix it.

### Crash Logs

The get link button when clicked just says "[Failed]" so here is a google drive link with the crash report and a few other useful things. https://drive.google.com/drive/folders/1hPoIQRIwaf01v0h0wz6Yb_AUlFUUY2Wk?usp=sharing

### Modpack Version

Other

### Server or singleplayer

Singleplayer

### Version the world was created on:

Other

### Other...

Like I said, its been months since I played on this save but the current version I tried loading it on now is "Version 3.0 BETA 6"

### Additional context

Here's a google drive link with stuff like my save and the crash report since the link button does not work. https://drive.google.com/drive/folders/1hPoIQRIwaf01v0h0wz6Yb_AUlFUUY2Wk?usp=sharing

**Comment by democat3457** [comment]
Worlds from 3.0 beta are not compatible with the current version.
