### ISSUE TITLE
[BUG] Tamed cockatrice not helping or defending itself

### ISSUE THREAD

**Issue by bonniebar** [Rebirth-of-the-Night/Rebirth-Of-The-Night#930]
### Describe the bug

So, I hatched a rotten egg and got a cockatrice. The beast is now an adult, and obeys my commands, but does not react to hostile mobs. I had to kill a boar to keep it alive! 

### To Reproduce

I don't know. I wasn't lucky enough to get a second cockatrice. Is it supposed to happen?

### Expected behavior

Cockatrice defends the owner, or at least its own life.

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

### Additional context

It actually got stuck in a wall as a baby, and didn't grow up until I broke said wall.

**Comment by democat3457** [comment]
I think its growth was stunted due to it living in a wall for some time.
