### ISSUE TITLE
[BUG] Lunar Water Subtracting 250mb on Conversion

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#937]
### Describe the bug

When attempting to convert white particle water in a cauldron into Lunar Water, the conversion subtracts 250mb (1 bottle) of liquid from the cauldron, causing an annoying 3-bottle-full cauldron of Lunar Water which requires bottles to harvest instead of a faster Quality Bucket. 

### To Reproduce

1. Complete the process of crafting Lunar Water. 
2. Look at the cauldron after tossing the lunar quintessence in. 

### Expected behavior

I expect the water conversion to be lossless. 

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

**Comment by democat3457** [comment]
oops i believe i know why

**Comment by democat3457** [comment]
Fixed with https://github.com/Rebirth-of-the-Night/Nyx/commit/4cfd892c310534224e179d3c8cbb2c63fb6b5fe4
