### ISSUE TITLE
[BUG] Book and Quill Recipe Incompatibility

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#941]
### Describe the bug

The book and quill item's recipe does not accept biomes o' plenty dyes such as `biomesoplenty:blue_dye`, `biomesoplenty:brown_dye`, `biomesoplenty:green_dye`, `biomesoplenty:white_dye`, and `biomesoplenty:black_dye`. This may affect other recipes, but I haven't tested them yet. 

### To Reproduce

1. Attempt to craft a book and quill with biomes o' plenty dyes. 

### Expected behavior

I expect all dye materials to have compatibility with a recipe that uses "any dye." 

### Modpack Version

3.1.1a

### Server or singleplayer

Server, Singleplayer

### Version the world was created on:

3.1.1a

**Comment by EliteMeats** [comment]
any other dyes, or just the ones you listed?

**Comment by KaleThyself** [comment]
> any other dyes, or just the ones you listed?

The only other dyes which are not HEI hidden are these ones besides the default Minecraft dyes.

**Comment by EliteMeats** [comment]
fixed
