### ISSUE TITLE
[BUG] Braziers Aren't Viable Heat Sources

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#943]
### Describe the bug

`futuremc:campfire` aka the Brazier does not count as a heat source for the Fluid Cauldron recipes despite appearing like one such as the Cincinnasite Fire Bowl which is able to be used. 

### To Reproduce

1. Place a Brazier under a Fluid Cauldron to cook stew.
2. The water will not boil. 

### Expected behavior

I expect the Brazier to be a valid heat source for the Fluid Cauldron. 

### Screenshots

![image](https://user-images.githubusercontent.com/50285548/179573571-e9889cd9-3842-4999-b83b-11ac99712eab.png)

### Modpack Version

3.1.1a

### Server or singleplayer

Server, Singleplayer

### Version the world was created on:

3.1.1a

### Additional context

While you're at it, having the Brazier as a valid heat source for the Cooking Cauldron/Crucible would be nice as well.

**Comment by democat3457** [comment]
fixed in dev (for a while now)
