### ISSUE TITLE
Server crash when loading certain area. [CRASH]

### ISSUE THREAD

**Issue by DeskDesk** [Rebirth-of-the-Night/Rebirth-Of-The-Night#946]
### Describe the crash

When loading an area of our world the server freezes, players can still move around but can't interact with anything. Doors don't open, chests can't be opened, villagers freeze, can't interact with JEI and chunks don't load. The problem is we can't find a crash log for this. The console on the server just stops reporting and eventually the server will boot you out with a connection lost. Server is still up on command center but is locked up. 
If we restart the server everyone can log in and do things as normal except for the person who loaded the bad area. If that person logs in the server immediately locks up and we need to restart the server. The only way we found to allow the player who is in the bad area to log in is to use NBT explorer to change his location to his respawn point which moves him out of that area and then upload that player data to the server. If that area is rendered again then we need to reload the player data with respawn location.

The problematic area was usable at one point as i had an atlas with me and mapped out the area without issues. This area has two villages and one village has two lords. The only thing that changes from when it was accessible and not accessible was that i traded with both of the village lords in one village and tamed a Amphithere and tied it to a post in that village.

We are willing to help troubleshoot this issue if we can get some guidance on what you want us to look for. 

I also have an atlas picture of the general area and am willing to upload videos or other things.

![atlas-2022-07-19_19 39 52](https://user-images.githubusercontent.com/7812220/179875192-f8490de9-53b3-4202-b1be-c84afbbecff0.jpg)

### To Reproduce

Render location.

### Crash Logs

It is not creating a crash report in the crash-reports folder.
We have had other crashes and crash reports for those crashes however we can't find one for this problem.

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

**Comment by iEatShadows** [comment]
looks like a village crash/freeze like #849 . Do a roll back before the crash/freeze happened and never go to those villages again.
