### ISSUE TITLE
[BUG] Onyx Pockets in Lava Lakes are Dormant

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#951]
### Describe the bug

After slaying the Wither, Onyx at the bottom of the Nether's lava lake in their obsidian pockets are still dormant.

### To Reproduce

1. Slay the Wither for progression. 
2. Go to the bottom of the Nether's lava lake to mine onyx wherever the Onyx Pockets form.
3. Look at the state the Onyx is in. 

### Expected behavior

I expect this Onyx to be as non-dormant as the others above the lava lake in their cozy sulfur pockets. 

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

**Comment by TheNelston** [comment]
what is the block id
