### ISSUE TITLE
[BUG]i cant break the arcane barrier 

### ISSUE THREAD

**Issue by Fego911** [Rebirth-of-the-Night/Rebirth-Of-The-Night#961]
### Describe the bug

I tried to break the arcane barrier block to enter the beneath in a server but it just can't break. I sat there for like 5 mins breaking it with efficiency 4 and it didn't have any affect on the block. 

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

**Comment by KaleThyself** [comment]
The Arcane Barrier in v.3.1.1a requires either the Arcane Focus or the Magic Bomb to break the first layer. Read the guidebook after closing this issue.

**Comment by democat3457** [comment]
As said above, read the guidebook.
