### ISSUE TITLE
[CRASH] server crash while starting up

### ISSUE THREAD

**Issue by someaznguy001** [Rebirth-of-the-Night/Rebirth-Of-The-Night#962]
### Describe the crash

so when i try to setup the server it will start up normally but then crash and stop then gives me a crash report 

### To Reproduce

clicking on the Run.bat

### Crash Logs

[crash-2022-07-24_16.09.54-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/9176928/crash-2022-07-24_16.09.54-server.txt)

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.0.1a

**Comment by democat3457** [comment]
Try a reinstall

**Comment by someaznguy001** [comment]
> 

of the server? i would lose the world right unless i can move it over modpacks seems fine the server just wont start

**Comment by democat3457** [comment]
you can copy the world folder out and then copy it back in after

and the reason a reinstall may help is because there appears to be a corrupted jar in your install, resulting in a missing java class

**Comment by someaznguy001** [comment]
> you can copy the world folder out and then copy it back in after
> 
> and the reason a reinstall may help is because there appears to be a corrupted jar in your install, resulting in a missing java class

that seems to have worked out thanks
