### ISSUE TITLE
[BUG] Wheat duplication using scaffolding direct interaction

### ISSUE THREAD

**Issue by DovelasThe** [Rebirth-of-the-Night/Rebirth-Of-The-Night#966]
### Describe the bug

Thatch created by using wheat on scaffolding can be crafted back into four wheat

Can also produce emeralds through shipping bin with duplicated wheat

### To Reproduce

Use wheat on placed scaffolding and craft thatch into more wheat than used

### Expected behavior

Should not be able to produce wheat out of sticks and wicker

### Screenshots

![image](https://user-images.githubusercontent.com/89428623/180892503-d7123ce1-5dcd-4e00-9ca1-d488f5298664.png)
![image](https://user-images.githubusercontent.com/89428623/180892529-c3f0a897-3991-4a07-85f6-4ab2db9b0d4d.png)
![image](https://user-images.githubusercontent.com/89428623/180892915-1c511f0c-5331-4be2-995d-24014ae94fb8.png)

### Modpack Version

3.1.1a

### Server or singleplayer

Server, Singleplayer

### Version the world was created on:

3.1.1a

**Comment by democat3457** [comment]
I believe this is an @Foreck1

**Comment by Foreck1** [comment]
Thatch to wheat will be removed.

**Comment by Foreck1** [comment]
535d8c2
