### ISSUE TITLE
Killing the Wroughtnought didn't display the message that Leylines were open[BUG]

### ISSUE THREAD

**Issue by Wolfenshaed** [Rebirth-of-the-Night/Rebirth-Of-The-Night#969]
### Describe the bug

Killing the Wroughtnought didn't prove the message that the Leylines were opened, we had previously killed the Sirens and the Harvester so we know that the messages were otherwise working okay. No-one was using the Sharpened Edge enchantment.

### To Reproduce

Unknown

### Expected behavior

We expected when it died for it show the message.

### Screenshots

![image](https://user-images.githubusercontent.com/110070615/181132658-a2b2e99c-51cc-4374-8ed8-3f5169c98ebb.png)
![image](https://user-images.githubusercontent.com/110070615/181132686-e9170e2a-7019-4028-9cfe-75c2a9383ffa.png)

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

**Comment by TheNelston** [comment]
fixed w/ new update 👍
