### ISSUE TITLE
[CRASH] Frostmaw cause server freeze

### ISSUE THREAD

**Issue by DaishiArslan** [Rebirth-of-the-Night/Rebirth-Of-The-Night#970]
### Describe the crash

Attacking the Frostmaw make the server freeze after a while (< 1min) and subsequent join will also freeze the server. The Frostmaw is also near an intact village but interaction with the village is completely fine before attacking the Frostmaw.
The server is hosted on a dedicated VPS running on Ubuntu 20.04 LTS.

### To Reproduce

Attack a Frostmaw and maybe need to be near a village.

### Crash Logs

[2022-07-26-5.log](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/9194392/2022-07-26-5.log)

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

**Comment by iEatShadows** [comment]
look around for another village, I would assume its a village bug not a frostmaw bug

**Comment by democat3457** [comment]
Logs give nothing useful, and I would assume it is village bug as well

**Comment by DaishiArslan** [comment]
If it's a village bug then is there any fix? cuz i've tried the corrupted chunk fix.

**Comment by DaishiArslan** [comment]
I've killed the Frostmaw but the issue persist so it must because of other reason.
