### ISSUE TITLE
crash on montain[CRASH]

### ISSUE THREAD

**Issue by chorriwuarri** [Rebirth-of-the-Night/Rebirth-Of-The-Night#975]
### Describe the crash

Is there any way I can fix this error?

I have tried in different worlds but if I get close to the mountains my game ends up crashing.

### Crash Logs

[crash-2022-08-03_11.12.17-server.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/9249964/crash-2022-08-03_11.12.17-server.txt)

### Modpack Version

Other

### Server or singleplayer

Singleplayer

### Version the world was created on:

Other

### Other...

master version on github

**Comment by Stargen45** [comment]
Why are you playing the github version?

**Comment by chorriwuarri** [comment]
in the stable version the time did not advance and I had to put the command every time I started the game, but I always forgot to do it, and I decided to try the github version, everything works fine except this crash

**Comment by democat3457** [comment]
Not supporting GitHub version for general player builds
