### ISSUE TITLE
[BUG] Soapstone iron ore blocks look weird next to soapstone

### ISSUE THREAD

**Issue by Power625** [Rebirth-of-the-Night/Rebirth-Of-The-Night#981]
### Describe the bug

Soapstone that surrounds iron ore blocks have some green texture facing the iron ore blocks.

### Expected behavior

No green texture.

### Screenshots

![pic](https://user-images.githubusercontent.com/72326420/185768613-4e5191ff-528b-4967-a468-f4e41294ea4e.png)

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

**Comment by EliteMeats** [comment]
this is a texture ID shifting bug, it can be fixed be reloading textures (f3 + t)
