### ISSUE TITLE
Cant grind items into quintessence with arcane mortar v3.0.1

### ISSUE THREAD

**Issue by LumpySocks** [Rebirth-of-the-Night/Rebirth-Of-The-Night#986]
### Describe the bug

not able to get quintessence from grinding different items, works fine in the mundane mortar but not the arcane. In the screenshot you can see it wont even give me the option for grinding it into creation quintessence.

### To Reproduce

just try and grind something in an arcane mortar. works fine with the low-level quintessence  but not the higher level ones that you get from killing bosses/mobs

### Expected behavior

that i would be able to grind it

### Screenshots

![unknown](https://user-images.githubusercontent.com/112859512/188414534-fe993867-3978-4b13-ae3c-44162abadf92.png)

### Modpack Version

3.0.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.1a

**Comment by democat3457** [comment]
does this exist on 3.1.1a

**Comment by KaleThyself** [comment]
From the screenshot above, I'm led to believe that this player is mistakenly using **just** one wheat to create a Creation quintessence which requires another item in the ingredient as well.
