### ISSUE TITLE
[BUG] Troll get freeze when using smashing attack while standing on tree branch

### ISSUE THREAD

**Issue by phambakimpro2** [Rebirth-of-the-Night/Rebirth-Of-The-Night#991]
### Describe the bug

a Troll spawns on tree branch, attempts to use smashing attack, breaks the tree but get permanently frozen

### To Reproduce

get a troll standing on a tree branch from Dynamic Tree mod, if it using smashing attack, destroy the tree but get permanently frozen

### Expected behavior

Destroy the tree but don't get frozen

### Screenshots

![troll bug](https://user-images.githubusercontent.com/81560078/189373313-a4c9497c-386f-4fbf-a7f5-99a1c9427e06.png)

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

### Additional context

i'm trying to recuit some bandits near a ruin village. A troll somehow spawns on a tree branch, become hostile when i get too close, uses a smashing attack, destroy the tree but freezes forever. Can still be attacked while frozen

**Comment by KaleThyself** [comment]
That's an intended feature of Ice and Fire. This issue may be closed.
