### ISSUE TITLE
[BUG] Portal won't teleport me into Nether and The End

### ISSUE THREAD

**Issue by Snecks09010** [Rebirth-of-the-Night/Rebirth-Of-The-Night#992]
### Describe the bug

Hello. I made a portal to nether and stood in it for about 10 minutes to move there, but no result. There is just a transition effect, you can safely exit the portal. I tried to do the same with nether and the end in another world in the creative, the same thing, when I try to go to the end, nothing happens. But aether and the twilight forest work. Is it possible to fix it somehow?

### To Reproduce

Enter the portal of nether and the end

### Expected behavior

So that you can go to nether and the end

### Modpack Version

3.1.1a

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.1a

**Comment by EliteMeats** [comment]
you must kill the harvester to enter the nether and mine mythril to enter the end, this is not a bug
