### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CapsLink** [Rebirth-of-the-Night/Rebirth-Of-The-Night#996]
### Describe the bug

pls tell me how to use the Burner Heater
i cant put anything into it :((((
I think I can make it out at this stage,  it should be workable 
Although this method is not the only one
this issue is asking for help, maybe not be a bug

### To Reproduce

when i want to use coal or wood, i found they cant be putted in. then i try many things such as under coal and some powders but no use

### Expected behavior

I just want to know I could be told what would make  the machine work

### Screenshots

![1](https://user-images.githubusercontent.com/115172469/194375717-d87d02d9-7576-4dbc-a464-df3a4785139c.png)
![2](https://user-images.githubusercontent.com/115172469/194375804-ed8942b9-a065-4072-a552-48cc9f3e862b.png)

### Modpack Version

3.1.1a

### Server or singleplayer

Server

### Version the world was created on:

3.1.1a

### Other...

tow people

### Additional context

no

**Comment by sneetsnart** [comment]
use coal coke or mossthane in all four slots, not a bug

**Comment by CapsLink** [comment]
i finally found Black of coal coke and massthane can put in the slot, thx XD

**Comment by CapsLink** [comment]
i think these things can be described in more detail. maybe write them in the notebook is good
